export const WORDS = [
  {
    word: "Concept",
    meaning: "Kavram; bir düşünceyi, nesneyi veya olguyu zihinde temsil eden genel fikir.",
    example: "The concept became clearer after the discussion.",
    hint: "Zihninde şekli tam belli olmayan ama anlamı olan bir fikir balonu düşün.",
  },
  {
    word: "Abstract",
    meaning: "Soyut; doğrudan duyularla algılanamayan, daha çok düşünceyle kavranan.",
    example: "Love is an abstract idea for many people.",
    hint: "Elinle tutamadığın ama aklında hissedebildiğin bir şeyi hayal et.",
  },
  {
    word: "Theory",
    meaning: "Kuram; gözlem ve kanıtlara dayanarak olayları açıklamaya çalışan sistemli açıklama.",
    example: "Her theory explains how the system works.",
    hint: "Bir yapbozun parçalarını bir araya getirip “Bence böyle oluyor” dediğin resmi düşün.",
  },
  {
    word: "Principle",
    meaning: "İlke; davranışları ve kararları yönlendiren temel kural veya ana fikir.",
    example: "Honesty is a key principle in his work.",
    hint: "Yolunu kaybettiğinde sana yön gösteren bir pusula kuralı hayal et.",
  },
  {
    word: "Logic",
    meaning: "Mantık; doğru düşünme ve akıl yürütme kurallarını inceleyen yöntem ve düzen.",
    example: "Use logic to solve the problem step by step.",
    hint: "Taşları sırayla dizince sonuca ulaştığın bir domino hattı düşün.",
  },
  {
    word: "Reasoning",
    meaning: "Akıl yürütme; çıkarım yaparak sonuca ulaşma süreci.",
    example: "Her reasoning was easy to follow.",
    hint: "İpuçlarını birleştirip gizemi çözen bir dedektif gibi düşün.",
  },
  {
    word: "Perspective",
    meaning: "Bakış açısı; bir konuyu değerlendirme biçimi, görüş ve yaklaşım.",
    example: "Try to see it from a different perspective.",
    hint: "Aynı manzaraya farklı pencerelerden bakan iki kişiyi hayal et.",
  },
  {
    word: "Context",
    meaning: "Bağlam; bir ifade veya olayın anlamını belirleyen çevresel ve durumsal bütün.",
    example: "In this context, the word means something else.",
    hint: "Bir kelimeyi tek başına değil, onu saran cümle çerçevesiyle görmeyi düşün.",
  },
  {
    word: "Paradox",
    meaning: "Paradoks; ilk bakışta çelişkili görünen, ancak üzerinde düşününce anlam taşıyabilen durum.",
    example: "It’s a paradox that less can be more.",
    hint: "Aynı anda hem doğru gibi hem de garip gelen bir bilmece kutusu düşün.",
  },
  {
    word: "Hypothesis",
    meaning: "Hipotez; doğruluğu test edilmek üzere ortaya atılan geçici açıklama veya varsayım.",
    example: "We tested the hypothesis with new data.",
    hint: "“Bence böyle olabilir” deyip deneyle kontrol ettiğin bir tahmini hayal et.",
  },
  {
    word: "Assumption",
    meaning: "Varsayım; kanıtlanmadan doğru kabul edilen düşünce veya ön kabul.",
    example: "That assumption may not be correct.",
    hint: "Haritaya bakmadan “Yol buradan gider” diye içinden geçirdiğin fikri düşün.",
  },
  {
    word: "Evidence",
    meaning: "Kanıt; bir iddiayı destekleyen veri, bulgu veya gerekçe.",
    example: "There is strong evidence for the claim.",
    hint: "Bir dosyada toplanmış fotoğraflar ve notlar gibi, gerçeği destekleyen izleri hayal et.",
  },
  {
    word: "Interpretation",
    meaning: "Yorumlama; bir olaya, metne veya veriye anlam verme ve açıklama süreci.",
    example: "Her interpretation of the poem was unique.",
    hint: "Aynı şarkıyı dinleyip herkesin farklı bir his çıkarmasını düşün.",
  },
  {
    word: "Bias",
    meaning: "Önyargı; bir kişi veya duruma ilişkin, yeterli bilgi olmadan oluşan eğilimli yargı.",
    example: "We should be aware of our bias when judging others.",
    hint: "Gözlüğünün camı renkliyken her şeyi o renkten görmeyi hayal et.",
  },
  {
    word: "Identity",
    meaning: "Kimlik; bir kişinin veya şeyin ayırt edici özelliklerini belirleyen bütün.",
    example: "Her identity is shaped by her experiences.",
    hint: "Seni “sen” yapan özelliklerin yazılı olduğu görünmez bir kart düşün.",
  },
  {
    word: "Ethics",
    meaning: "Etik; doğru-yanlış ve iyi-kötü üzerine ilke ve değerleri inceleyen düşünce alanı.",
    example: "Ethics matters when we build new technology.",
    hint: "Karar verirken içindeki “doğru olan ne?” sesini hayal et.",
  },
  {
    word: "Value",
    meaning: "Değer; bir şeyin önemini belirleyen ilke, ölçüt veya anlam.",
    example: "Respect is a value we should protect.",
    hint: "Kalbinde “bu çok önemli” dediğin şeyler için küçük bir hazine sandığı düşün.",
  },
  {
    word: "Purpose",
    meaning: "Amaç; bir eylemin ulaşmak istediği hedef veya niyet.",
    example: "The purpose of the meeting was to plan the project.",
    hint: "Okun ucunun gittiği hedef tahtasını hayal et.",
  },
  {
    word: "Complexity",
    meaning: "Karmaşıklık; bir sistemin çok sayıda parça ve ilişki içermesi nedeniyle zor anlaşılması durumu.",
    example: "The complexity of the problem surprised us.",
    hint: "Birbirine dolaşmış kulaklık kablolarını düşün: çözdükçe düzen ortaya çıkar.",
  },
  {
    word: "Uncertainty",
    meaning: "Belirsizlik; sonucun veya bilginin net olmadığı durum.",
    example: "We made a decision despite the uncertainty.",
    hint: "Sisli bir yolda ilerlerken ileriyi tam görememeyi hayal et.",
  },
  {
    word: "Innovation",
    meaning: "Yenilik; yeni bir fikir veya yöntemi geliştirip uygulanabilir hâle getirme.",
    example: "Innovation can change how people live.",
    hint: "Eski bir alete yeni bir süper güç eklediğini hayal et.",
  },
  {
    word: "Strategy",
    meaning: "Strateji; bir hedefe ulaşmak için belirlenen planlı ve uzun vadeli yaklaşım.",
    example: "Their strategy focused on small daily improvements.",
    hint: "Bir satranç oyununda birkaç hamle sonrasını düşünerek plan yapmayı hayal et.",
  },
  {
    word: "Framework",
    meaning: "Çerçeve; bir konuyu düzenlemek ve anlamlandırmak için kullanılan yapı veya sistem.",
    example: "This framework helps teams organize their work.",
    hint: "Dağınık fikirleri içine yerleştirdiğin bir raf sistemi düşün.",
  },
  {
    word: "Criteria",
    meaning: "Kriterler; değerlendirme yapmak için kullanılan ölçütler ve koşullar bütünü.",
    example: "We chose the best option based on clear criteria.",
    hint: "Bir yarışmada puan veren hakemlerin kontrol listesini hayal et.",
  },

  {
    word: "Awareness",
    meaning: "Farkındalık; kişinin kendisinin, çevresinin ve durumların bilincinde olma hâli.",
    example: "Meditation increased her awareness of emotions.",
    hint: "Etrafındaki sesleri ve hisleri aynı anda fark ettiğin sakin bir anı düşün.",
  },
  {
    word: "Consciousness",
    meaning: "Bilinç; kişinin kendisinin ve çevresinin farkında olma durumu.",
    example: "Scientists still study human consciousness.",
    hint: "Uyandığını ve “Ben buradayım” dediğin o net anı hayal et.",
  },
  {
    word: "Perception",
    meaning: "Algı; duyular aracılığıyla bilgiyi alma ve yorumlama süreci.",
    example: "Color perception can differ from person to person.",
    hint: "Aynı renge bakıp herkesin biraz farklı görmesini düşün.",
  },
  {
    word: "Reality",
    meaning: "Gerçeklik; var olan ve doğru kabul edilen durumların bütünü.",
    example: "Reality is sometimes different from expectations.",
    hint: "Hayallerle gerçeklerin kesiştiği o çizgiyi hayal et.",
  },
  {
    word: "Existence",
    meaning: "Varoluş; bir şeyin var olma durumu.",
    example: "Philosophers question the meaning of existence.",
    hint: "“Ben neden buradayım?” diye düşündüğün derin bir anı hayal et.",
  },
  {
    word: "Meaning",
    meaning: "Anlam; bir kelime, olay veya durumun ifade ettiği düşünce.",
    example: "This word has a deep meaning.",
    hint: "Basit bir cümlenin sende büyük bir his uyandırmasını düşün.",
  },
  {
    word: "Insight",
    meaning: "İçgörü; bir konuyu derinlemesine ve ani bir şekilde anlama yetisi.",
    example: "She had an insight during the discussion.",
    hint: "Bir anda ampulün yandığı o “Aaa!” anını hayal et.",
  },
  {
    word: "Reflection",
    meaning: "Düşünme; geçmiş deneyimler üzerine bilinçli değerlendirme yapma süreci.",
    example: "Reflection helps personal growth.",
    hint: "Sessizce oturup gününü gözden geçirdiğin bir anı düşün.",
  },
  {
    word: "Contradiction",
    meaning: "Çelişki; iki düşüncenin aynı anda doğru olamaması durumu.",
    example: "His statement was full of contradiction.",
    hint: "Aynı anda hem evet hem hayır demek zorunda kaldığını hayal et.",
  },
  {
    word: "Balance",
    meaning: "Denge; zıt unsurlar arasında uyumlu durum.",
    example: "Work-life balance is important.",
    hint: "İki tarafı eşit duran bir teraziyi düşün.",
  },
  {
    word: "Harmony",
    meaning: "Uyum; farklı unsurların birlikte düzenli çalışması durumu.",
    example: "The team worked in harmony.",
    hint: "Farklı enstrümanların tek bir güzel melodi oluşturmasını düşün.",
  },
  {
    word: "Contrast",
    meaning: "Karşıtlık; belirgin farkların bir arada bulunması durumu.",
    example: "The contrast between ideas was clear.",
    hint: "Siyah ve beyazın yan yana durmasını hayal et.",
  },
  {
    word: "Depth",
    meaning: "Derinlik; yüzeyin ötesinde anlam veya karmaşıklık barındırma durumu.",
    example: "The book has emotional depth.",
    hint: "Yüzeyi sakin ama altı dolu bir denizi düşün.",
  },
  {
    word: "Abstraction",
    meaning: "Soyutlama; ayrıntıları azaltarak temel özelliklere odaklanma süreci.",
    example: "Abstraction is common in art and science.",
    hint: "Gereksiz detayları silip ana fikri bırakmayı hayal et.",
  },
  {
    word: "Interpretive",
    meaning: "Yorumlayıcı; anlamı açıklama ve değerlendirmeye dayalı yaklaşım.",
    example: "The course takes an interpretive approach.",
    hint: "Bir tabloya bakıp herkesin farklı bir hikâye görmesini düşün.",
  },
  {
    word: "Limitation",
    meaning: "Sınırlama; bir şeyin ulaşabileceği noktanın kısıtlanması durumu.",
    example: "Time is a major limitation.",
    hint: "Önünde görünmez bir çizgi olduğunu hayal et.",
  },
  {
    word: "Possibility",
    meaning: "Olasılık; gerçekleşme ihtimali bulunan durum.",
    example: "There is a possibility of change.",
    hint: "Henüz açılmamış birçok kapıyı hayal et.",
  },
  {
    word: "Potential",
    meaning: "Potansiyel; gelecekte gelişme veya gerçekleşme kapasitesi.",
    example: "She has great potential.",
    hint: "İçinde büyümeyi bekleyen bir tohum düşün.",
  },
  {
    word: "Transformation",
    meaning: "Dönüşüm; bir şeyin biçim veya yapı değiştirmesi süreci.",
    example: "The project led to a major transformation.",
    hint: "Tırtılın kelebeğe dönüşmesini hayal et.",
  },
  {
    word: "Progress",
    meaning: "İlerleme; zamanla gelişme ve ileri gitme durumu.",
    example: "Small steps lead to progress.",
    hint: "Her gün biraz daha ileri giden bir yolculuğu düşün.",
  },
  {
    word: "Evolution",
    meaning: "Evrim; zaman içinde kademeli değişim ve gelişim süreci.",
    example: "Technology evolves rapidly.",
    hint: "Yavaş ama sürekli değişen bir çizgiyi hayal et.",
  },
  {
    word: "Significance",
    meaning: "Önem; bir şeyin taşıdığı değer ve etki düzeyi.",
    example: "This discovery has great significance.",
    hint: "Küçük ama çok değerli bir anahtarı düşün.",
  },
  {
    word: "Justification",
    meaning: "Gerekçelendirme; bir düşünceyi destekleyen nedenleri sunma.",
    example: "He provided justification for his decision.",
    hint: "“Neden?” sorusuna verdiğin güçlü cevabı hayal et.",
  },
  {
    word: "Coherence",
    meaning: "Tutarlılık; fikirlerin mantıklı ve uyumlu biçimde bir arada olması.",
    example: "The argument lacked coherence.",
    hint: "Parçaları uyumla birleşen bir hikâyeyi düşün.",
  },
  {
    word: "Ambiguity",
    meaning: "Belirsizlik; birden fazla anlama açık olma durumu.",
    example: "The sentence creates ambiguity.",
    hint: "Hem öyle hem böyle yorumlanabilen bir ifade düşün.",
  },
  {
    word: "Inference",
    meaning: "Çıkarım; eldeki bilgilerden mantıklı bir sonuç çıkarma.",
    example: "We made an inference from the data.",
    hint: "İzlere bakıp sonucu tahmin etmeyi hayal et.",
  },
  {
    word: "Synthesis",
    meaning: "Sentez; farklı fikirleri birleştirerek yeni bir bütün oluşturma.",
    example: "The paper is a synthesis of many studies.",
    hint: "Farklı parçaları birleştirip yeni bir resim oluşturmayı düşün.",
  },
  {
    word: "Evaluation",
    meaning: "Değerlendirme; bir durumu ölçütlere göre inceleme süreci.",
    example: "Evaluation is part of learning.",
    hint: "Bir kontrol listesiyle artıları eksileri tartmayı hayal et.",
  },
  {
    word: "Judgement",
    meaning: "Yargı; bir konu hakkında sonuca varma eylemi.",
    example: "Try not to rush your judgement.",
    hint: "Karar vermeden önce derin bir nefes almayı düşün.",
  },
  {
    word: "Wisdom",
    meaning: "Bilgelik; bilgi ve deneyimi doğru kararlarla birleştirme yetisi.",
    example: "Wisdom comes with experience.",
    hint: "Az konuşup yerinde konuşan birini hayal et.",
  },
];
