export const DAILY_LIFE_WORDS = [
  {
    word: "Wake",
    difficulty: "beginner",
    meaning: "Uyanmak; uykudan uyanma eylemi.",
    example: "I wake up at 7 a.m. every day.",
    hint: "Sabah gözlerini açtığın o ilk anı düşün.",
  },
  {
    word: "Sleep",
    difficulty: "beginner",
    meaning: "Uyku; uyuma durumu.",
    example: "I need more sleep tonight.",
    hint: "Yatağa girip gözlerini kapattığın an.",
  },
  {
    word: "Morning",
    difficulty: "beginner",
    meaning: "Sabah; günün erken saatleri.",
    example: "My morning starts with a glass of water.",
    hint: "Günün başladığı, hava hâlâ serinken olan zaman.",
  },
  {
    word: "Evening",
    difficulty: "beginner",
    meaning: "Akşam; gün batımından sonraki zaman.",
    example: "We watch a movie in the evening.",
    hint: "Güneş battıktan sonra rahatladığın saatler.",
  },
  {
    word: "Night",
    difficulty: "beginner",
    meaning: "Gece; günün karanlık kısmı.",
    example: "The streets are quiet at night.",
    hint: "Her yerin sakinleştiği karanlık zaman.",
  },
  {
    word: "Today",
    difficulty: "beginner",
    meaning: "Bugün; içinde bulunulan gün.",
    example: "I feel busy today.",
    hint: "Takvimde tam şu an yaşadığın gün.",
  },
  {
    word: "Tomorrow",
    difficulty: "beginner",
    meaning: "Yarın; bugünden sonraki gün.",
    example: "I will call you tomorrow.",
    hint: "Bugünün bir sonraki adımı gibi düşün.",
  },
  {
    word: "Yesterday",
    difficulty: "beginner",
    meaning: "Dün; bugünden önceki gün.",
    example: "I met him yesterday.",
    hint: "Bir gün geriye sar, o gün.",
  },
  {
    word: "Early",
    difficulty: "beginner",
    meaning: "Erken; zamanın başlangıcında.",
    example: "I arrived early for class.",
    hint: "Herkes gelmeden önce orada olmak.",
  },
  {
    word: "Late",
    difficulty: "beginner",
    meaning: "Geç; beklenen zamandan sonra.",
    example: "Sorry, I am late.",
    hint: "Saatin biraz kaçtığı an.",
  },
  {
    word: "Time",
    difficulty: "beginner",
    meaning: "Zaman; süre ve an kavramı.",
    example: "Time passes quickly.",
    hint: "Saatine baktığında hissettiğin şey.",
  },
  {
    word: "Hour",
    difficulty: "beginner",
    meaning: "Saat; 60 dakikalık zaman birimi.",
    example: "The meeting lasts one hour.",
    hint: "Bir ders süresi gibi düşün.",
  },
  {
    word: "Minute",
    difficulty: "beginner",
    meaning: "Dakika; 60 saniyelik zaman birimi.",
    example: "Wait a minute, please.",
    hint: "Kısa bir bekleyiş, bir nefeslik an.",
  },
  {
    word: "Busy",
    difficulty: "beginner",
    meaning: "Meşgul; işi çok olan.",
    example: "I am busy this afternoon.",
    hint: "Üst üste işler geldiğinde söylediğin şey.",
  },
  {
    word: "Free",
    difficulty: "beginner",
    meaning: "Boş; müsait, zamanı olan.",
    example: "I am free after work.",
    hint: "İşin bitip rahatladığın an.",
  },
  {
    word: "Work",
    difficulty: "beginner",
    meaning: "Çalışmak; bir iş yürütmek.",
    example: "I work from home on Fridays.",
    hint: "Günün belli saatlerini ayırdığın uğraş.",
  },
  {
    word: "Study",
    difficulty: "beginner",
    meaning: "Çalışmak; öğrenmek için emek vermek.",
    example: "I study English every day.",
    hint: "Kendine küçük bir hedef koyup ilerlemek.",
  },
  {
    word: "Rest",
    difficulty: "beginner",
    meaning: "Dinlenmek; yorgunluğu gidermek.",
    example: "I rest for a while after lunch.",
    hint: "Kısa bir mola verip enerji toplamak.",
  },
  {
    word: "Walk",
    difficulty: "beginner",
    meaning: "Yürümek; adım atarak ilerlemek.",
    example: "I walk to the store.",
    hint: "Kısa mesafe için arabasız gitmek.",
  },
  {
    word: "Run",
    difficulty: "beginner",
    meaning: "Koşmak; hızlı hareket etmek.",
    example: "I run in the park.",
    hint: "Ayakkabını giyip tempo yaptığın an.",
  },
  {
    word: "Eat",
    difficulty: "beginner",
    meaning: "Yemek yemek; besin tüketmek.",
    example: "I eat breakfast at home.",
    hint: "Masanın başına oturup ilk lokmayı almak.",
  },
  {
    word: "Drink",
    difficulty: "beginner",
    meaning: "İçmek; sıvı tüketmek.",
    example: "I drink coffee in the morning.",
    hint: "Bir yudumla kendine gelmek.",
  },
  {
    word: "Cook",
    difficulty: "beginner",
    meaning: "Pişirmek; yemek hazırlamak.",
    example: "I cook pasta for dinner.",
    hint: "Mutfakta basit bir şeyler yapmak.",
  },
  {
    word: "Breakfast",
    difficulty: "beginner",
    meaning: "Kahvaltı; günün ilk öğünü.",
    example: "Breakfast is my favorite meal.",
    hint: "Çay/kahve ve küçük tabaklarla başlayan öğün.",
  },
  {
    word: "Lunch",
    difficulty: "beginner",
    meaning: "Öğle yemeği; gün ortası öğünü.",
    example: "We have lunch at noon.",
    hint: "Günün ortasında kısa bir yemek molası.",
  },
  {
    word: "Dinner",
    difficulty: "beginner",
    meaning: "Akşam yemeği; günün son ana öğünü.",
    example: "Dinner is at 8 p.m.",
    hint: "Günün sonunda sofraya oturmak.",
  },
  {
    word: "Snack",
    difficulty: "beginner",
    meaning: "Atıştırmalık; küçük ara öğün.",
    example: "I grab a snack between meals.",
    hint: "Açlık bastırınca hızlı bir şey yemek.",
  },
  {
    word: "Water",
    difficulty: "beginner",
    meaning: "Su; içme suyu.",
    example: "Please drink more water.",
    hint: "Yanında taşıdığın şişeyi hatırla.",
  },
  {
    word: "Coffee",
    difficulty: "beginner",
    meaning: "Kahve; kafeinli içecek.",
    example: "I like coffee without sugar.",
    hint: "Kokusuyla bile uyandıran içecek.",
  },
  {
    word: "Tea",
    difficulty: "beginner",
    meaning: "Çay; demlenmiş içecek.",
    example: "Tea is popular in Turkey.",
    hint: "İnce belli bardakla gelen klasik.",
  },
  {
    word: "Shower",
    difficulty: "beginner",
    meaning: "Duş; yıkanma eylemi.",
    example: "I take a shower after the gym.",
    hint: "Üzerindeki yorgunluğu suyla atmak.",
  },
  {
    word: "Wash",
    difficulty: "beginner",
    meaning: "Yıkamak; temizlemek.",
    example: "I wash my hands before eating.",
    hint: "Temizlik için su ve sabunla yapılan hareket.",
  },
  {
    word: "Brush",
    difficulty: "beginner",
    meaning: "Fırçalamak; özellikle dişleri temizlemek.",
    example: "I brush my teeth twice a day.",
    hint: "Diş fırçasını eline aldığın rutin.",
  },
  {
    word: "Clean",
    difficulty: "beginner",
    meaning: "Temizlemek; kirden arındırmak.",
    example: "I clean my room on Sundays.",
    hint: "Eşyaları toparlayıp ferahlık yapmak.",
  },
  {
    word: "Get",
    difficulty: "beginner",
    meaning: "Almak; edinmek.",
    example: "I get some milk from the market.",
    hint: "Gidip bir şeyi eline almak.",
  },
  {
    word: "Go",
    difficulty: "beginner",
    meaning: "Gitmek; bir yere hareket etmek.",
    example: "I go to work by bus.",
    hint: "Bir yerden başka bir yere yönelmek.",
  },
  {
    word: "Come",
    difficulty: "beginner",
    meaning: "Gelmek; bulunduğun yere yaklaşmak.",
    example: "Come here for a second.",
    hint: "Yanına çağırdığında kullandığın kelime.",
  },
  {
    word: "Leave",
    difficulty: "intermediate",
    meaning: "Ayrılmak; bir yerden çıkmak.",
    example: "I leave the office at 6.",
    hint: "Bir yerden çıkıp yola koyulmak.",
  },
  {
    word: "Arrive",
    difficulty: "intermediate",
    meaning: "Varış yapmak; bir yere ulaşmak.",
    example: "I arrive home around 7.",
    hint: "Kapıdan içeri girdiğin an.",
  },
  {
    word: "Start",
    difficulty: "beginner",
    meaning: "Başlamak; başlangıç yapmak.",
    example: "I start my day with stretching.",
    hint: "İlk adımı atmak.",
  },
  {
    word: "Finish",
    difficulty: "beginner",
    meaning: "Bitirmek; tamamlamak.",
    example: "I finish my homework early.",
    hint: "Son noktayı koymak.",
  },
  {
    word: "Open",
    difficulty: "beginner",
    meaning: "Açmak; kapalıyı açmak.",
    example: "Please open the window.",
    hint: "Bir şeyi açıp hava almak gibi düşün.",
  },
  {
    word: "Close",
    difficulty: "beginner",
    meaning: "Kapatmak; açık olanı kapatmak.",
    example: "Close the door, please.",
    hint: "Sessizlik için kapıyı kapatma.",
  },
  {
    word: "Turn on",
    difficulty: "beginner",
    meaning: "Açmak; cihazı çalıştırmak.",
    example: "Turn on the light.",
    hint: "Işığı yakmak gibi düşün.",
  },
  {
    word: "Turn off",
    difficulty: "beginner",
    meaning: "Kapatmak; cihazı durdurmak.",
    example: "Turn off the TV.",
    hint: "Cihazı kapatıp dinlenmek.",
  },
  {
    word: "Listen",
    difficulty: "beginner",
    meaning: "Dinlemek; işitmeye odaklanmak.",
    example: "I listen to music on the way.",
    hint: "Kulaklığını takıp sese odaklanmak.",
  },
  {
    word: "Watch",
    difficulty: "beginner",
    meaning: "İzlemek; görerek takip etmek.",
    example: "We watch videos at night.",
    hint: "Ekrana bakıp içerik tüketmek.",
  },
  {
    word: "Read",
    difficulty: "beginner",
    meaning: "Okumak; metni anlamak.",
    example: "I read a book before sleep.",
    hint: "Sayfayı çevirip takip etmek.",
  },
  {
    word: "Write",
    difficulty: "beginner",
    meaning: "Yazmak; yazılı ifade etmek.",
    example: "I write notes in class.",
    hint: "Bir şeyi not defterine geçirmek.",
  },
  {
    word: "Call",
    difficulty: "beginner",
    meaning: "Aramak; telefon etmek.",
    example: "I call my mom every day.",
    hint: "Telefonu eline alıp birini aramak.",
  },
  {
    word: "Text",
    difficulty: "beginner",
    meaning: "Mesaj atmak; kısa mesaj göndermek.",
    example: "I text my friend after class.",
    hint: "Hızlıca yazıp gönderdiğin mesaj.",
  },
  {
    word: "Meet",
    difficulty: "beginner",
    meaning: "Buluşmak; bir araya gelmek.",
    example: "We meet at the café.",
    hint: "Aynı yerde aynı zamanda görüşmek.",
  },
  {
    word: "Wait",
    difficulty: "beginner",
    meaning: "Beklemek; bir süre durmak.",
    example: "Please wait here.",
    hint: "Sıranın gelmesini beklemek.",
  },
  {
    word: "Buy",
    difficulty: "beginner",
    meaning: "Satın almak; para ile edinmek.",
    example: "I buy bread from the bakery.",
    hint: "Kasada ödeme yapıp almak.",
  },
  {
    word: "Pay",
    difficulty: "beginner",
    meaning: "Ödemek; ücret vermek.",
    example: "I pay by card.",
    hint: "Kartla ya da nakitle hesabı kapatmak.",
  },
  {
    word: "Save",
    difficulty: "intermediate",
    meaning: "Biriktirmek; saklamak.",
    example: "I save money for a trip.",
    hint: "Azar azar kenara koymak.",
  },
  {
    word: "Money",
    difficulty: "beginner",
    meaning: "Para; ödeme aracı.",
    example: "I don't have cash.",
    hint: "Cüzdanındaki temel şey.",
  },
  {
    word: "Bus",
    difficulty: "beginner",
    meaning: "Otobüs; toplu taşıma aracı.",
    example: "I take the bus to work.",
    hint: "Durakta bekleyip bindiğin araç.",
  },
  {
    word: "Car",
    difficulty: "beginner",
    meaning: "Araba; motorlu taşıt.",
    example: "My car is parked outside.",
    hint: "Kendi aracınla bir yere gitmek.",
  },
  {
    word: "Taxi",
    difficulty: "beginner",
    meaning: "Taksi; ücretli ulaşım aracı.",
    example: "Let's take a taxi.",
    hint: "Hızlıca bir yere yetişmek için çağırılan araç.",
  },
  {
    word: "Street",
    difficulty: "beginner",
    meaning: "Sokak; yerleşim yolu.",
    example: "Our street is quiet.",
    hint: "Evinin önündeki yol.",
  },
  {
    word: "Home",
    difficulty: "beginner",
    meaning: "Ev; yaşanılan yer.",
    example: "I feel happy at home.",
    hint: "En rahat hissettiğin yer.",
  },
  {
    word: "Office",
    difficulty: "beginner",
    meaning: "Ofis; çalışma yeri.",
    example: "The office is near the station.",
    hint: "Çalıştığın masa ve ekip alanı.",
  },
  {
    word: "School",
    difficulty: "beginner",
    meaning: "Okul; eğitim kurumu.",
    example: "My school starts at 9.",
    hint: "Derslerin olduğu bina.",
  },
  {
    word: "Class",
    difficulty: "beginner",
    meaning: "Sınıf; ders yapılan grup/oda.",
    example: "Our class is on the second floor.",
    hint: "Ders dinlediğin yer.",
  },
  {
    word: "Room",
    difficulty: "beginner",
    meaning: "Oda; ev içi bölüm.",
    example: "My room is small.",
    hint: "Kendi alanın, kapısı olan bölüm.",
  },
  {
    word: "Kitchen",
    difficulty: "beginner",
    meaning: "Mutfak; yemek yapılan bölüm.",
    example: "The kitchen smells nice.",
    hint: "Yemek kokusunun geldiği yer.",
  },
  {
    word: "Bathroom",
    difficulty: "beginner",
    meaning: "Banyo; yıkanma alanı.",
    example: "The bathroom is clean.",
    hint: "Duş ve lavabo olan yer.",
  },
  {
    word: "Bed",
    difficulty: "beginner",
    meaning: "Yatak; uyuma eşyası.",
    example: "My bed is comfortable.",
    hint: "Uykuya daldığın yer.",
  },
  {
    word: "Phone",
    difficulty: "beginner",
    meaning: "Telefon; iletişim cihazı.",
    example: "My phone battery is low.",
    hint: "Elinden düşmeyen cihaz.",
  },
  {
    word: "Key",
    difficulty: "beginner",
    meaning: "Anahtar; kilit açan araç.",
    example: "I can't find my key.",
    hint: "Kapıyı açmak için lazım olan küçük şey.",
  },
  {
    word: "Bag",
    difficulty: "beginner",
    meaning: "Çanta; eşya taşımaya yarayan.",
    example: "My bag is heavy today.",
    hint: "İçine her şeyi doldurduğun çanta.",
  },
  {
    word: "Clothes",
    difficulty: "beginner",
    meaning: "Kıyafet; giyim eşyaları.",
    example: "I need clean clothes.",
    hint: "Dolabındaki giydiklerin.",
  },
  {
    word: "Shoes",
    difficulty: "beginner",
    meaning: "Ayakkabı; ayağa giyilen.",
    example: "My shoes are wet.",
    hint: "Dışarı çıkarken giydiğin şey.",
  },
  {
    word: "Weather",
    difficulty: "beginner",
    meaning: "Hava durumu; atmosfer koşulları.",
    example: "The weather is nice today.",
    hint: "Dışarı çıkmadan önce baktığın şey.",
  },
  {
    word: "Sunny",
    difficulty: "beginner",
    meaning: "Güneşli; güneşin olduğu.",
    example: "It is sunny outside.",
    hint: "Güneş gözlüğü taktıran hava.",
  },
  {
    word: "Rainy",
    difficulty: "beginner",
    meaning: "Yağmurlu; yağmurun olduğu.",
    example: "It is rainy today.",
    hint: "Şemsiye aratan hava.",
  },
  {
    word: "Cold",
    difficulty: "beginner",
    meaning: "Soğuk; düşük sıcaklıkta.",
    example: "It is cold in the morning.",
    hint: "Üşütüp mont giydiren hava.",
  },
  {
    word: "Hot",
    difficulty: "beginner",
    meaning: "Sıcak; yüksek sıcaklıkta.",
    example: "It is hot today.",
    hint: "Terleten hava.",
  },
  {
    word: "Quick",
    difficulty: "beginner",
    meaning: "Hızlı; kısa sürede olan.",
    example: "That was quick.",
    hint: "Çabucak bitince söylediğin şey.",
  },
  {
    word: "Slow",
    difficulty: "beginner",
    meaning: "Yavaş; uzun sürede olan.",
    example: "The internet is slow.",
    hint: "Beklettikçe sinir eden tempo.",
  },
  {
    word: "Simple",
    difficulty: "beginner",
    meaning: "Basit; karmaşık olmayan.",
    example: "It is a simple task.",
    hint: "Gözünde büyütmeden yapılabilen.",
  },
  {
    word: "Easy",
    difficulty: "beginner",
    meaning: "Kolay; zor olmayan.",
    example: "This exercise is easy.",
    hint: "İlk denemede yapabildiğin.",
  },
  {
    word: "Hard",
    difficulty: "beginner",
    meaning: "Zor; güç olan.",
    example: "This level is hard.",
    hint: "Biraz uğraştıran durum.",
  },
  {
    word: "Again",
    difficulty: "beginner",
    meaning: "Tekrar; yeniden.",
    example: "Say it again, please.",
    hint: "Bir daha duymak istediğinde.",
  },
  {
    word: "Always",
    difficulty: "beginner",
    meaning: "Her zaman; daima.",
    example: "I always drink water.",
    hint: "Rutin olarak yaptığın şey.",
  },
  {
    word: "Often",
    difficulty: "beginner",
    meaning: "Sık sık; çoğu zaman.",
    example: "I often go for a walk.",
    hint: "Ara ara değil, bayağı düzenli.",
  },
  {
    word: "Sometimes",
    difficulty: "beginner",
    meaning: "Bazen; ara sıra.",
    example: "I sometimes cook at home.",
    hint: "Her zaman değil, arada.",
  },
  {
    word: "Never",
    difficulty: "beginner",
    meaning: "Asla; hiçbir zaman.",
    example: "I never smoke.",
    hint: "Hiç yapmadığını vurgulamak.",
  },
  {
    word: "Soon",
    difficulty: "beginner",
    meaning: "Yakında; kısa süre içinde.",
    example: "See you soon.",
    hint: "Çok bekletmeden olacak gibi.",
  },
  {
    word: "Now",
    difficulty: "beginner",
    meaning: "Şimdi; bu an.",
    example: "I need it now.",
    hint: "Hemen, gecikmeden demek.",
  },
  {
    word: "Later",
    difficulty: "beginner",
    meaning: "Sonra; daha ileride.",
    example: "I'll do it later.",
    hint: "Şimdi değil, birazdan demek.",
  },
  {
    word: "Here",
    difficulty: "beginner",
    meaning: "Burada; bu yerde.",
    example: "Put it here.",
    hint: "Elinin altındaki noktayı işaret etmek.",
  },
  {
    word: "There",
    difficulty: "beginner",
    meaning: "Orada; o yerde.",
    example: "Your bag is there.",
    hint: "Biraz uzaktaki yeri göstermek.",
  },
  {
    word: "Before",
    difficulty: "beginner",
    meaning: "Önce; daha erken zamanda.",
    example: "Wash your hands before dinner.",
    hint: "Bir şeyden daha önce yapılan adım.",
  },
  {
    word: "After",
    difficulty: "beginner",
    meaning: "Sonra; daha geç zamanda.",
    example: "I rest after work.",
    hint: "Bir iş bittiğinde gelen kısım.",
  },
  {
    word: "Together",
    difficulty: "beginner",
    meaning: "Birlikte; beraber.",
    example: "Let's study together.",
    hint: "Yan yana yapınca daha kolay hissedilen.",
  },
  {
    word: "Alone",
    difficulty: "beginner",
    meaning: "Yalnız; tek başına.",
    example: "I live alone.",
    hint: "Tek başına kaldığında kullanılan.",
  },
  {
    word: "Outside",
    difficulty: "beginner",
    meaning: "Dışarıda; dış mekânda.",
    example: "It is cold outside.",
    hint: "Evin dışı, açık hava.",
  },
  {
    word: "Inside",
    difficulty: "beginner",
    meaning: "İçeride; iç mekânda.",
    example: "Stay inside today.",
    hint: "Evin içi, kapalı alan.",
  },
  {
    word: "Routine",
    difficulty: "advanced",
    meaning:
      "Rutin; günlük hayatta düzenli olarak tekrar edilen alışkanlıklar bütünü.",
    example: "My daily routine starts with a short walk.",
    hint: "Her gün neredeyse otomatik yaptığın şeyleri düşün.",
  },
  {
    word: "Procrastinate",
    difficulty: "advanced",
    meaning:
      "Ertelemek; yapılması gereken bir işi bilinçli olarak geciktirmek.",
    example: "I tend to procrastinate when I feel stressed.",
    hint: "Yapman gereken şeyi sürekli yarına bırakmak.",
  },
  {
    word: "Efficient",
    difficulty: "advanced",
    meaning: "Verimli; minimum zaman ve çabayla maksimum sonuç sağlayan.",
    example: "She found a more efficient way to manage her day.",
    hint: "Aynı işi daha kısa sürede yapmak.",
  },
  {
    word: "Overwhelmed",
    difficulty: "advanced",
    meaning:
      "Bunalmış; çok fazla iş veya sorumluluk altında ezilmiş hissetmek.",
    example: "I felt overwhelmed by my daily tasks.",
    hint: "Her şey üst üste gelmiş gibi hissettiğin an.",
  },
  {
    word: "Prioritize",
    difficulty: "advanced",
    meaning: "Önceliklendirmek; işleri önem sırasına koymak.",
    example: "I need to prioritize my responsibilities better.",
    hint: "Hangisi daha önemli diye karar vermek.",
  },
  {
    word: "Habitual",
    difficulty: "advanced",
    meaning: "Alışkanlık haline gelmiş; sürekli tekrar edilen davranış.",
    example: "Checking my phone before sleep is habitual.",
    hint: "Fark etmeden tekrar ettiğin alışkanlıklar.",
  },
  {
    word: "Neglect",
    difficulty: "advanced",
    meaning: "İhmal etmek; gereken ilgiyi veya bakımı göstermemek.",
    example: "He neglected his health because of work.",
    hint: "Göz ardı edilen sorumluluklar.",
  },
  {
    word: "Balance",
    difficulty: "advanced",
    meaning: "Denge; iş, özel hayat ve dinlenme arasında uyum sağlama durumu.",
    example: "Maintaining balance in daily life is important.",
    hint: "Hayatın farklı alanlarını eşit tutmak.",
  },
  {
    word: "Consistent",
    difficulty: "advanced",
    meaning: "Tutarlı; düzenli ve aynı şekilde devam eden.",
    example: "Being consistent helps build good habits.",
    hint: "Ara vermeden devam etmek.",
  },
  {
    word: "Resilient",
    difficulty: "advanced",
    meaning: "Dayanıklı; zorluklara rağmen ayakta kalabilen.",
    example: "She stayed resilient despite daily stress.",
    hint: "Zor günlerden sonra toparlanabilmek.",
  },
  {
    word: "Mindful",
    difficulty: "advanced",
    meaning: "Farkındalıklı; bilinçli ve dikkatli şekilde anda olmak.",
    example: "He tries to be mindful during daily activities.",
    hint: "O an ne yaptığının farkında olmak.",
  },
  {
    word: "Productive",
    difficulty: "advanced",
    meaning: "Üretken; zamanı etkili kullanarak sonuç üreten.",
    example: "Today was a very productive day.",
    hint: "Günün sonunda ‘bir şeyler başardım’ demek.",
  },
  {
    word: "Adapt",
    difficulty: "advanced",
    meaning: "Uyum sağlamak; yeni koşullara göre değişmek.",
    example: "I had to adapt to a new daily schedule.",
    hint: "Değişen şartlara ayak uydurmak.",
  },
  {
    word: "Obligation",
    difficulty: "advanced",
    meaning: "Yükümlülük; yapılması gereken resmi veya kişisel sorumluluk.",
    example: "Family obligations affect my daily routine.",
    hint: "Kaçınılmaz sorumluluklar.",
  },
  {
    word: "Draining",
    difficulty: "advanced",
    meaning: "Yorucu; zihinsel veya fiziksel enerjiyi tüketen.",
    example: "Long meetings can be draining.",
    hint: "Enerjini emen aktiviteler.",
  },
  {
    word: "Fulfill",
    difficulty: "advanced",
    meaning: "Yerine getirmek; bir görevi veya sorumluluğu tamamlamak.",
    example: "He fulfilled his daily duties.",
    hint: "Üzerine düşeni yapmak.",
  },
  {
    word: "Distraction",
    difficulty: "advanced",
    meaning: "Dikkat dağıtıcı; odağı bozan şey.",
    example: "Noise is a major distraction for me.",
    hint: "Odaklanmanı bölen şeyler.",
  },
  {
    word: "Sustainable",
    difficulty: "advanced",
    meaning: "Sürdürülebilir; uzun vadede devam ettirilebilen.",
    example: "He built a sustainable daily routine.",
    hint: "Uzun süre sürdürülebilecek alışkanlıklar.",
  },
  {
    word: "Self-discipline",
    difficulty: "advanced",
    meaning: "Öz disiplin; kişinin kendini kontrol edebilme yetisi.",
    example: "Self-discipline is essential in daily life.",
    hint: "Kimse bakmıyorken bile doğru olanı yapmak.",
  },
  {
    word: "Reflect",
    difficulty: "advanced",
    meaning: "Düşünmek; geçmiş deneyimleri değerlendirerek anlam çıkarmak.",
    example: "I reflect on my day before going to bed.",
    hint: "Günü zihninde yeniden gözden geçirmek.",
  },
] as const;
