export const EDUCATION_WORDS = [
  {
    word: "Study",
    meaning: "Düzenli olarak öğrenmek amacıyla yapılan çalışma süreci.",
    example: "I study English for 20 minutes every day.",
    hint: "Her gün kısa da olsa çalışmayı hedefle.",
  },
  {
    word: "Learn",
    meaning: "Bilgi veya beceriyi edinme ve geliştirme eylemi.",
    example: "I learn new words by reading simple stories.",
    hint: "Yeni bir şey öğrendiğinde küçük bir not al.",
  },
  {
    word: "Teach",
    meaning: "Bilgiyi başkasına aktarma ve öğretme eylemi.",
    example: "She teaches math at a local school.",
    hint: "Bir konuyu anlatabiliyorsan gerçekten öğrenmişsindir.",
  },
  {
    word: "School",
    meaning: "Eğitim ve öğretimin yapıldığı kurum.",
    example: "My school starts at 8:30 in the morning.",
    hint: "Okulu, öğrenmenin başladığı yer gibi düşün.",
  },
  {
    word: "Class",
    meaning: "Belirli bir derse katılan öğrenci grubu veya ders saati.",
    example: "Our class is learning basic grammar today.",
    hint: "Sınıfı, aynı hedefe yürüyen ekip gibi hayal et.",
  },
  {
    word: "Lesson",
    meaning: "Planlı şekilde işlenen ders içeriği.",
    example: "The lesson was about past tense.",
    hint: "Dersi küçük parçalar hâlinde düşün; daha kolay olur.",
  },
  {
    word: "Homework",
    meaning: "Dersin pekiştirilmesi için verilen ev çalışması.",
    example: "I finished my homework before dinner.",
    hint: "Ödevi erteleme; 10 dakikada başla.",
  },
  {
    word: "Exam",
    meaning: "Bilgi ve beceriyi ölçmeye yönelik resmî sınav.",
    example: "We have an exam on Friday.",
    hint: "Sınavdan önce kısa tekrar yapmayı unutma.",
  },
  {
    word: "Test",
    meaning: "Belirli bir konuyu ölçmeye yönelik değerlendirme.",
    example: "I took a short test after the lesson.",
    hint: "Testi mini sınav gibi düşün.",
  },
  {
    word: "Quiz",
    meaning: "Genellikle kısa ve pratik amaçlı yapılan mini sınav.",
    example: "We had a quiz on vocabulary.",
    hint: "Quizler, öğrendiklerini hızlıca görmenin yolu.",
  },
  {
    word: "Grade",
    meaning: "Değerlendirme sonucu verilen not.",
    example: "I got a good grade in science.",
    hint: "Notu sonuç olarak gör; süreç daha önemli.",
  },
  {
    word: "Score",
    meaning: "Bir değerlendirmede elde edilen puan.",
    example: "His score improved this month.",
    hint: "Puanını takip ederek gelişimini gör.",
  },
  {
    word: "Teacher",
    meaning: "Eğitim veren ve yönlendiren kişi.",
    example: "The teacher explained the topic clearly.",
    hint: "Öğretmenini bir rehber gibi düşün.",
  },
  {
    word: "Student",
    meaning: "Eğitim alan ve öğrenen kişi.",
    example: "The student asked a great question.",
    hint: "Sen öğrencisin; hata yapmak öğrenmenin parçası.",
  },
  {
    word: "Classroom",
    meaning: "Dersin işlendiği fiziksel ortam.",
    example: "The classroom was quiet during the test.",
    hint: "Sınıf ortamını odaklanma alanı gibi gör.",
  },
  {
    word: "Board",
    meaning: "Ders anlatımında kullanılan yazı tahtası.",
    example: "The answer was written on the board.",
    hint: "Tahtaya yazılanları kendi defterine sadeleştir.",
  },
  {
    word: "Notebook",
    meaning: "Not almak için kullanılan defter.",
    example: "I wrote my notes in a notebook.",
    hint: "Küçük bir defter, büyük bir fark yaratır.",
  },
  {
    word: "Textbook",
    meaning: "Dersin temel içeriğini sunan ders kitabı.",
    example: "The textbook has many examples.",
    hint: "Ders kitabını harita gibi kullan.",
  },
  {
    word: "Dictionary",
    meaning: "Kelimelerin anlamlarını açıklayan sözlük.",
    example: "I checked the word in a dictionary.",
    hint: "Bilmediğin kelimeyi hemen sözlükten bak.",
  },
  {
    word: "Library",
    meaning: "Kitapların ve kaynakların bulunduğu kütüphane.",
    example: "I borrowed a book from the library.",
    hint: "Kütüphane, sessiz bir çalışma sığınağıdır.",
  },
  {
    word: "Read",
    meaning: "Yazılı bir metni anlamak amacıyla okumak.",
    example: "I read a short article in English.",
    hint: "Her gün az da olsa oku; hızın artar.",
  },
  {
    word: "Write",
    meaning: "Düşünceleri yazıyla ifade etmek.",
    example: "I write a few sentences every day.",
    hint: "Yazarken basit cümlelerle başla.",
  },
  {
    word: "Listen",
    meaning: "Duyarak anlamaya çalışmak.",
    example: "I listen to English podcasts on my way home.",
    hint: "Kısa videolar dinleyerek alış.",
  },
  {
    word: "Speak",
    meaning: "Sözlü olarak ifade etmek.",
    example: "I speak slowly when I am nervous.",
    hint: "Hata yapmaktan çekinme; konuşmak pratik ister.",
  },
  {
    word: "Understand",
    meaning: "Anlamını kavramak ve çözmek.",
    example: "I understand the main idea now.",
    hint: "Anlamadığında dur ve tekrar oku.",
  },
  {
    word: "Practice",
    meaning: "Beceri kazanmak için düzenli tekrar yapmak.",
    example: "I practice pronunciation every night.",
    hint: "Pratik, öğrenmenin motorudur.",
  },
  {
    word: "Review",
    meaning: "Önceden öğrenilenleri tekrar gözden geçirmek.",
    example: "I review my notes before the exam.",
    hint: "Uyumadan önce kısa tekrar çok etkili.",
  },
  {
    word: "Memorize",
    meaning: "Bilgiyi ezberleyerek akılda tutmak.",
    example: "I try to memorize five words a day.",
    hint: "Ezber yerine örnek cümleyle hatırla.",
  },
  {
    word: "Note",
    meaning: "Hatırlamak için yazılan kısa bilgi.",
    example: "I made a note of the new rule.",
    hint: "Notları kısa ve anlaşılır tut.",
  },
  {
    word: "Highlight",
    meaning: "Önemli yerleri işaretlemek.",
    example: "I highlight key words in the text.",
    hint: "Önemli kısımları renkle vurgula.",
  },
  {
    word: "Pencil",
    meaning: "Yazı yazmaya yarayan kurşun kalem.",
    example: "I use a pencil for math.",
    hint: "Kalemini hazır tut; notlar kaçmasın.",
  },
  {
    word: "Pen",
    meaning: "Mürekkeple yazı yazmaya yarayan kalem.",
    example: "She signed the paper with a pen.",
    hint: "Daha net yazılar için tükenmez kalem.",
  },
  {
    word: "Eraser",
    meaning: "Kurşun kalem izini silmeye yarayan silgi.",
    example: "I used an eraser to fix my mistake.",
    hint: "Hata silinebilir; öğrenme devam eder.",
  },
  {
    word: "Ruler",
    meaning: "Ölçmeye ve düz çizgi çizmeye yarayan cetvel.",
    example: "He drew a line with a ruler.",
    hint: "Cetvel, düzenli notlar için iyi bir yardımcı.",
  },
  {
    word: "Marker",
    meaning: "Belirgin yazı yazmaya yarayan keçeli kalem.",
    example: "I wrote the title with a marker.",
    hint: "Başlıkları marker ile ayırabilirsin.",
  },
  {
    word: "Paper",
    meaning: "Yazı yazılan veya basılan kâğıt.",
    example: "I printed the homework on paper.",
    hint: "Kâğıdı düzenli kullan; sayfan rahatlar.",
  },
  {
    word: "Page",
    meaning: "Bir kitabın veya defterin sayfası.",
    example: "Read page ten for tomorrow.",
    hint: "Sayfa sayfa ilerle; küçük hedefler koy.",
  },
  {
    word: "Chapter",
    meaning: "Kitabın ana bölümlerinden biri.",
    example: "This chapter is about adjectives.",
    hint: "Bölümü küçük parçalara ayırıp oku.",
  },
  {
    word: "Paragraph",
    meaning: "Bir metinde aynı fikri taşıyan cümle grubu.",
    example: "Write one paragraph about your hobby.",
    hint: "Her paragrafta ana fikri yakala.",
  },
  {
    word: "Sentence",
    meaning: "Anlamlı bir düşünceyi ifade eden söz dizimi.",
    example: "This sentence uses the past tense.",
    hint: "Kısa cümle kur; zamanla uzat.",
  },
  {
    word: "Word",
    meaning: "Anlam taşıyan kelime birimi.",
    example: "I learned a new word today.",
    hint: "Kelimeyi tek başına değil, cümlede öğren.",
  },
  {
    word: "Letter",
    meaning: "Alfabenin bir harfi.",
    example: "The word starts with the letter A.",
    hint: "Harfleri iyi öğrenmek telaffuza yardımcı olur.",
  },
  {
    word: "Grammar",
    meaning: "Dil bilgisi kurallarının bütünü.",
    example: "Grammar helps you write correctly.",
    hint: "Grameri korkulacak şey değil, düzen gibi düşün.",
  },
  {
    word: "Spelling",
    meaning: "Kelimelerin doğru yazımı.",
    example: "Spelling is important in emails.",
    hint: "Yazımını kontrol etmek için yavaş yaz.",
  },
  {
    word: "Pronounce",
    meaning: "Kelimeleri doğru şekilde telaffuz etmek.",
    example: "Try to pronounce the word clearly.",
    hint: "Önce yavaş, sonra doğal söyle.",
  },
  {
    word: "Accent",
    meaning: "Konuşmada vurguların ve ses özelliklerinin toplamı.",
    example: "Her accent is easy to understand.",
    hint: "Aksan normaldir; anlaşılır olmak yeter.",
  },
  {
    word: "Meaning",
    meaning: "Bir kelime veya ifadenin taşıdığı anlam.",
    example: "What is the meaning of this word?",
    hint: "Anlamı örnekle birleştir; kalıcı olur.",
  },
  {
    word: "Example",
    meaning: "Bir kuralı veya kelimeyi açıklayan örnek.",
    example: "Can you give an example sentence?",
    hint: "Kendi örneğini yazarsan daha iyi hatırlarsın.",
  },
  {
    word: "Question",
    meaning: "Cevap almak amacıyla sorulan ifade.",
    example: "I have a question about this topic.",
    hint: "Soru sormak öğrenmenin en hızlı yolu.",
  },
  {
    word: "Answer",
    meaning: "Bir soruya verilen yanıt.",
    example: "Your answer is correct.",
    hint: "Cevabını yüksek sesle söyleyerek pekiştir.",
  },
  {
    word: "Topic",
    meaning: "Konuşulan veya çalışılan konu.",
    example: "Today's topic is time management.",
    hint: "Konuyu netleştir; odaklanman kolaylaşır.",
  },
  {
    word: "Subject",
    meaning: "Eğitimde belirli bir ders alanı.",
    example: "Math is my favorite subject.",
    hint: "Sevdiğin dersi seç, motivasyonun artsın.",
  },
  {
    word: "Math",
    meaning: "Sayılar ve işlemlerle ilgili bilim dalı.",
    example: "Math can be fun with practice.",
    hint: "Matematikte adım adım ilerle.",
  },
  {
    word: "Science",
    meaning: "Doğa ve evreni inceleyen bilim alanı.",
    example: "Science explains how things work.",
    hint: "Bilimde merak en büyük güç.",
  },
  {
    word: "History",
    meaning: "Geçmiş olayları inceleyen alan.",
    example: "We studied history last semester.",
    hint: "Tarihi hikâye gibi oku; akılda kalır.",
  },
  {
    word: "Geography",
    meaning: "Yeryüzü ve yerleşimlerle ilgili alan.",
    example: "Geography helps you understand the world.",
    hint: "Haritaya bakarak çalışmak çok işe yarar.",
  },
  {
    word: "Art",
    meaning: "Yaratıcı ifade ve estetik alanı.",
    example: "Art class is relaxing.",
    hint: "Sanatta doğru-yanlış yok; dene.",
  },
  {
    word: "Music",
    meaning: "Ses ve ritimle ilgili sanat dalı.",
    example: "Music helps me focus while studying.",
    hint: "Müzikle kelime öğrenmek keyifli olur.",
  },
  {
    word: "Computer",
    meaning: "Bilgisayar; dijital öğrenme aracı.",
    example: "I use my computer for research.",
    hint: "Öğrenme uygulamalarını bilgisayarda da deneyebilirsin.",
  },
  {
    word: "Project",
    meaning: "Belirli bir hedefe yönelik çalışma.",
    example: "Our project is about renewable energy.",
    hint: "Projeyi küçük görevlere böl.",
  },
  {
    word: "Assignment",
    meaning: "Öğretmen tarafından verilen görev.",
    example: "The assignment is due tomorrow.",
    hint: "Görevi erken başlat; stres azalır.",
  },
  {
    word: "Research",
    meaning: "Bilgi toplama ve inceleme çalışması.",
    example: "I did research for my presentation.",
    hint: "Araştırmada güvenilir kaynak seç.",
  },
  {
    word: "Presentation",
    meaning: "Bir konuyu dinleyiciye sunma.",
    example: "I gave a presentation in class.",
    hint: "Sunumdan önce aynada prova yap.",
  },
  {
    word: "Lecture",
    meaning: "Öğretmenin anlatım yaptığı ders.",
    example: "The lecture lasted one hour.",
    hint: "Dersi dinlerken ana başlıkları yakala.",
  },
  {
    word: "Seminar",
    meaning: "Tartışma ve sunum ağırlıklı ders etkinliği.",
    example: "We joined a seminar on learning methods.",
    hint: "Seminerlerde soru sormaktan çekinme.",
  },
  {
    word: "Course",
    meaning: "Belirli bir süre devam eden ders programı.",
    example: "I enrolled in an online course.",
    hint: "Kursu düzenli takip edersen çok ilerlersin.",
  },
  {
    word: "Schedule",
    meaning: "Planlanmış zaman çizelgesi.",
    example: "Check the schedule for next week.",
    hint: "Haftalık bir plan yapmak işini kolaylaştırır.",
  },
  {
    word: "Timetable",
    meaning: "Ders saatlerini gösteren çizelge.",
    example: "My timetable is busy on Mondays.",
    hint: "Ders programını görünür bir yere as.",
  },
  {
    word: "Calendar",
    meaning: "Tarih ve planlamayı gösteren takvim.",
    example: "I marked the exam date on my calendar.",
    hint: "Takvim kullanmak disiplin kazandırır.",
  },
  {
    word: "Break",
    meaning: "Ders arası mola.",
    example: "Take a short break after studying.",
    hint: "Kısa mola, uzun odak demektir.",
  },
  {
    word: "Lunch",
    meaning: "Öğle yemeği.",
    example: "We have lunch at noon.",
    hint: "Öğle yemeğinden sonra kısa yürüyüş iyi gelir.",
  },
  {
    word: "Backpack",
    meaning: "Kitap ve malzemeleri taşıyan çanta.",
    example: "I packed my backpack for school.",
    hint: "Çantanı akşamdan hazırla.",
  },
  {
    word: "Desk",
    meaning: "Çalışma masası.",
    example: "My desk is next to the window.",
    hint: "Masayı sade tut; zihnin de sadeleşir.",
  },
  {
    word: "Chair",
    meaning: "Oturmak için kullanılan sandalye.",
    example: "Sit on the chair and start writing.",
    hint: "Rahat bir sandalye odaklanmanı artırır.",
  },
  {
    word: "Screen",
    meaning: "Bilgisayar veya tablet ekranı.",
    example: "I watched the lesson on my screen.",
    hint: "Ekran süreni planla; gözlerini dinlendir.",
  },
  {
    word: "Online",
    meaning: "İnternet üzerinden gerçekleştirilen.",
    example: "The course is online this semester.",
    hint: "Online dersleri tekrar izlemek avantajdır.",
  },
  {
    word: "Website",
    meaning: "İnternet sitesi.",
    example: "This website has free practice tests.",
    hint: "İyi bir website, çok kaynak sunar.",
  },
  {
    word: "App",
    meaning: "Mobil uygulama.",
    example: "I use an app to learn vocabulary.",
    hint: "Uygulamayı her gün kısa süre kullan.",
  },
  {
    word: "Video",
    meaning: "Görsel-işitsel içerik.",
    example: "I watched a video about grammar.",
    hint: "Kısa video dersler motivasyon sağlar.",
  },
  {
    word: "Audio",
    meaning: "Ses kaydı veya ses içeriği.",
    example: "Listen to the audio and repeat.",
    hint: "Sesle çalışmak telaffuzu geliştirir.",
  },
  {
    word: "Download",
    meaning: "İnternetten cihaza indirmek.",
    example: "Download the file for later.",
    hint: "İndirip çevrimdışı da çalışabilirsin.",
  },
  {
    word: "Upload",
    meaning: "Dosyayı internete yüklemek.",
    example: "Upload your homework to the platform.",
    hint: "Ödevini yüklemeden önce kontrol et.",
  },
  {
    word: "Login",
    meaning: "Bir sisteme giriş yapmak.",
    example: "I cannot login with this password.",
    hint: "Giriş bilgilerini güvenli tut.",
  },
  {
    word: "Password",
    meaning: "Giriş için kullanılan gizli şifre.",
    example: "Change your password regularly.",
    hint: "Şifreni güçlü seç; kolay tahmin edilmesin.",
  },
  {
    word: "Email",
    meaning: "Elektronik posta mesajı.",
    example: "I sent an email to my teacher.",
    hint: "Kısa ve nazik e-posta yazmayı öğren.",
  },
  {
    word: "Tutorial",
    meaning: "Adım adım öğretici içerik.",
    example: "This tutorial explains the basics.",
    hint: "Kısa bir tutorial, hızlı öğrenme sağlar.",
  },
  {
    word: "Workshop",
    meaning: "Uygulamalı öğrenme etkinliği.",
    example: "We attended a writing workshop.",
    hint: "Atölyede denemek öğrenmeyi hızlandırır.",
  },
  {
    word: "Certificate",
    meaning: "Bir eğitimi tamamladığını gösteren belge.",
    example: "I received a certificate after the course.",
    hint: "Sertifikayı hedef olarak koy; motive eder.",
  },
  {
    word: "Diploma",
    meaning: "Bir okuldan mezuniyeti gösteren resmî belge.",
    example: "She got her diploma last year.",
    hint: "Diploma, uzun bir emeğin sonucudur.",
  },
  {
    word: "Degree",
    meaning: "Üniversite düzeyinde alınan akademik derece.",
    example: "He is working on a degree in engineering.",
    hint: "Derece, belirli bir alanı tamamladığını gösterir.",
  },
  {
    word: "Scholarship",
    meaning: "Eğitim masrafları için verilen burs.",
    example: "She applied for a scholarship.",
    hint: "Burs fırsatlarını düzenli takip et.",
  },
  {
    word: "Campus",
    meaning: "Üniversite yerleşkesi.",
    example: "The campus has a big library.",
    hint: "Kampüs, öğrenme kadar sosyallik de demektir.",
  },
  {
    word: "Lab",
    meaning: "Deneylerin yapıldığı laboratuvar.",
    example: "We did an experiment in the lab.",
    hint: "Labda güvenlik kurallarına dikkat et.",
  },
  {
    word: "Experiment",
    meaning: "Bir fikri test etmeye yönelik deney.",
    example: "The experiment worked well.",
    hint: "Deneyi gözlemle; sonuçları yaz.",
  },
  {
    word: "Group",
    meaning: "Birlikte çalışan topluluk.",
    example: "We worked in a group of four.",
    hint: "Grup çalışmasında görev paylaş.",
  },
  {
    word: "Team",
    meaning: "Ortak amaç için çalışan ekip.",
    example: "Our team finished the project early.",
    hint: "Takım olmak, birlikte ilerlemek demektir.",
  },
  {
    word: "Discuss",
    meaning: "Bir konuyu konuşup değerlendirmek.",
    example: "Let's discuss the main idea.",
    hint: "Tartışırken saygılı ve açık ol.",
  },
  {
    word: "Share",
    meaning: "Bilgiyi veya materyali paylaşmak.",
    example: "Please share your notes with me.",
    hint: "Paylaşınca öğrenme büyür.",
  },
  {
    word: "Improve",
    meaning: "Geliştirmek ve daha iyi hâle getirmek.",
    example: "I want to improve my listening skills.",
    hint: "Küçük gelişmelerin farkına var.",
  },
  {
    word: "Progress",
    meaning: "Zaman içinde kaydedilen ilerleme.",
    example: "I can see my progress this week.",
    hint: "İlerlemeni haftalık takip et.",
  },
] as const;
