export const EMOTIONS_WORDS = [
  {
    word: "Happy",
    difficulty: "beginner",
    meaning: "Mutlu; sevinçli ve iyi hissetme durumu.",
    example: "I feel happy today.",
    hint: "Yüzünde istemsiz bir gülümseme belirdiğini düşün.",
  },
  {
    word: "Sad",
    difficulty: "beginner",
    meaning: "Üzgün; moralin bozuk olduğu durum.",
    example: "She feels sad after the movie.",
    hint: "İçinin biraz sıkıldığı anlar.",
  },
  {
    word: "Angry",
    difficulty: "beginner",
    meaning: "Kızgın; öfkeli hissetme durumu.",
    example: "He is angry about the delay.",
    hint: "Sinirinin yükseldiği bir anı hatırla.",
  },
  {
    word: "Calm",
    difficulty: "beginner",
    meaning: "Sakin; huzurlu ve rahat.",
    example: "She stays calm in stressful moments.",
    hint: "Derin bir nefes aldığın an.",
  },
  {
    word: "Excited",
    difficulty: "beginner",
    meaning: "Heyecanlı; sabırsız ve istekli.",
    example: "I am excited about the trip.",
    hint: "Kalbin biraz daha hızlı atıyor.",
  },
  {
    word: "Nervous",
    difficulty: "beginner",
    meaning: "Gergin; endişeli ve huzursuz.",
    example: "He feels nervous before exams.",
    hint: "Ellerinin biraz terlediğini düşün.",
  },
  {
    word: "Relaxed",
    difficulty: "beginner",
    meaning: "Rahatlamış; stresin az olduğu durum.",
    example: "I feel relaxed after work.",
    hint: "Omuzlarının gevşediğini hisset.",
  },
  {
    word: "Proud",
    difficulty: "intermediate",
    meaning: "Gururlu; kendinle memnun olma durumu.",
    example: "She is proud of her success.",
    hint: "Başardığın bir şeyi hatırla.",
  },
  {
    word: "Shy",
    difficulty: "beginner",
    meaning: "Çekingen; utangaç.",
    example: "He is shy around new people.",
    hint: "Kalabalıkta konuşmaktan çekindiğin an.",
  },
  {
    word: "Confident",
    difficulty: "intermediate",
    meaning: "Kendine güvenen; emin.",
    example: "She feels confident at work.",
    hint: "Kendinden emin durduğunu düşün.",
  },
  {
    word: "Brave",
    difficulty: "beginner",
    meaning: "Cesur; korkuya rağmen harekete geçen.",
    example: "He is brave in difficult times.",
    hint: "Korkmana rağmen devam ettiğin an.",
  },
  {
    word: "Kind",
    difficulty: "beginner",
    meaning: "Nazik; iyi kalpli.",
    example: "She is kind to everyone.",
    hint: "Birine yardım ettiğin an.",
  },
  {
    word: "Friendly",
    difficulty: "beginner",
    meaning: "Canayakın; sıcakkanlı.",
    example: "He is friendly with guests.",
    hint: "Kolayca sohbet başlattığın an.",
  },
  {
    word: "Quiet",
    difficulty: "beginner",
    meaning: "Sessiz; az konuşan.",
    example: "She is quiet in meetings.",
    hint: "Daha çok dinlediğin anlar.",
  },
  {
    word: "Talkative",
    difficulty: "beginner",
    meaning: "Konuşkan; çok konuşan.",
    example: "He is very talkative.",
    hint: "Sohbetin hiç bitmediği an.",
  },
  {
    word: "Patient",
    difficulty: "intermediate",
    meaning: "Sabırlı; beklemeye dayanıklı.",
    example: "She is patient with children.",
    hint: "Beklerken sakin kaldığını düşün.",
  },
  {
    word: "Impatient",
    difficulty: "intermediate",
    meaning: "Sabırsız; beklemekte zorlanan.",
    example: "He gets impatient easily.",
    hint: "Zaman geçmiyor gibi hissettiğin an.",
  },
  {
    word: "Lazy",
    difficulty: "beginner",
    meaning: "Tembel; harekete geçmek istemeyen.",
    example: "I feel lazy today.",
    hint: "Kalkmak istemediğin bir gün.",
  },
  {
    word: "Active",
    difficulty: "beginner",
    meaning: "Hareketli; enerjik.",
    example: "She is active in the morning.",
    hint: "Yerinde duramadığın an.",
  },
  {
    word: "Serious",
    difficulty: "beginner",
    meaning: "Ciddi; şaka yapmayan.",
    example: "He looks serious today.",
    hint: "Odaklandığın bir an.",
  },
  {
    word: "Funny",
    difficulty: "beginner",
    meaning: "Eğlenceli; güldüren.",
    example: "She is really funny.",
    hint: "Gülmene sebep olan biri.",
  },
  {
    word: "Positive",
    difficulty: "beginner",
    meaning: "Pozitif; olumlu düşünen.",
    example: "He has a positive attitude.",
    hint: "İyi tarafı gördüğün an.",
  },
  {
    word: "Negative",
    difficulty: "beginner",
    meaning: "Negatif; olumsuz düşünen.",
    example: "She feels negative today.",
    hint: "Hep kötü ihtimali düşündüğün an.",
  },
  {
    word: "Optimistic",
    difficulty: "intermediate",
    meaning: "İyimser; umutlu.",
    example: "He is optimistic about life.",
    hint: "Geleceğe umutla baktığın an.",
  },
  {
    word: "Pessimistic",
    difficulty: "intermediate",
    meaning: "Kötümser; umutsuz.",
    example: "She sounds pessimistic.",
    hint: "Sonucun kötü olacağını düşündüğün an.",
  },
  {
    word: "Sensitive",
    difficulty: "intermediate",
    meaning: "Hassas; kolay etkilenen.",
    example: "He is sensitive to criticism.",
    hint: "Küçük şeylere alındığın an.",
  },
  {
    word: "Strong",
    difficulty: "beginner",
    meaning: "Güçlü; dayanıklı.",
    example: "She is strong emotionally.",
    hint: "Zor durumda ayakta kaldığın an.",
  },
  {
    word: "Weak",
    difficulty: "beginner",
    meaning: "Zayıf; dayanıklılığı az.",
    example: "He feels weak today.",
    hint: "Enerjinin düştüğü an.",
  },
  {
    word: "Curious",
    difficulty: "intermediate",
    meaning: "Meraklı; öğrenmek isteyen.",
    example: "I am curious about this topic.",
    hint: "Bir şeyin nedenini sorduğun an.",
  },
  {
    word: "Bored",
    difficulty: "beginner",
    meaning: "Sıkılmış; ilgisiz.",
    example: "She feels bored at home.",
    hint: "Zaman geçmiyor gibi hissettiğin an.",
  },
  {
    word: "Interested",
    difficulty: "intermediate",
    meaning: "İlgili; merak duyan.",
    example: "He is interested in art.",
    hint: "Dikkatini çeken bir konu.",
  },
  {
    word: "Tired",
    difficulty: "beginner",
    meaning: "Yorgun; enerjisi az.",
    example: "I am tired after work.",
    hint: "Gözlerinin kapandığı an.",
  },
  {
    word: "Energetic",
    difficulty: "intermediate",
    meaning: "Enerjik; canlı.",
    example: "She feels energetic today.",
    hint: "Çok hareketli hissettiğin an.",
  },
  {
    word: "Lonely",
    difficulty: "beginner",
    meaning: "Yalnız; tek başına hisseden.",
    example: "He feels lonely sometimes.",
    hint: "Kimseyle konuşmadığın an.",
  },
  {
    word: "Loved",
    difficulty: "beginner",
    meaning: "Sevilmiş; değer verilen.",
    example: "She feels loved by her family.",
    hint: "Değerli hissettiğin an.",
  },
  {
    word: "Hopeful",
    difficulty: "intermediate",
    meaning: "Umutlu; beklentisi olan.",
    example: "I feel hopeful about tomorrow.",
    hint: "İyi bir şey olacağını düşündüğün an.",
  },
  {
    word: "Afraid",
    difficulty: "beginner",
    meaning: "Korkmuş; endişeli.",
    example: "He is afraid of heights.",
    hint: "Biraz ürktüğün an.",
  },
  {
    word: "Surprised",
    difficulty: "beginner",
    meaning: "Şaşırmış; beklemediği bir durum yaşayan.",
    example: "She was surprised by the gift.",
    hint: "Beklenmedik bir şey oldu.",
  },
  {
    word: "Satisfied",
    difficulty: "intermediate",
    meaning: "Memnun; tatmin olmuş.",
    example: "I am satisfied with the result.",
    hint: "İçin rahatladığı an.",
  },
  {
    word: "Jealous",
    difficulty: "intermediate",
    meaning: "Kıskanç; başkasını çekemeyen.",
    example: "He feels jealous sometimes.",
    hint: "Başkasında olanı istediğin an.",
  },
  {
    word: "Grateful",
    difficulty: "intermediate",
    meaning: "Minnettar; şükreden.",
    example: "She feels grateful for help.",
    hint: "Teşekkür etmek istediğin an.",
  },
  {
    word: "Polite",
    difficulty: "beginner",
    meaning: "Kibar; nazik.",
    example: "He is polite to elders.",
    hint: "Lütfen dediğin an.",
  },
  {
    word: "Rude",
    difficulty: "beginner",
    meaning: "Kaba; kırıcı.",
    example: "She was rude to him.",
    hint: "Sözlerin sertleştiği an.",
  },
  {
    word: "Honest",
    difficulty: "intermediate",
    meaning: "Dürüst; doğruyu söyleyen.",
    example: "He is honest with friends.",
    hint: "Gerçeği saklamadığın an.",
  },
  {
    word: "Creative",
    difficulty: "intermediate",
    meaning: "Yaratıcı; yeni fikirler üreten.",
    example: "She is very creative.",
    hint: "Farklı bir fikir bulduğun an.",
  },
  {
    word: "Careful",
    difficulty: "beginner",
    meaning: "Dikkatli; temkinli.",
    example: "Be careful with the glass.",
    hint: "Acele etmediğin an.",
  },
  {
    word: "Careless",
    difficulty: "intermediate",
    meaning: "Dikkatsiz; umursamaz.",
    example: "He was careless with money.",
    hint: "Detayları kaçırdığın an.",
  },
  {
    word: "Trusting",
    difficulty: "intermediate",
    meaning: "Güvenen; kolay inanan.",
    example: "She is trusting by nature.",
    hint: "İnsanlara çabuk güvendiğin an.",
  },
  {
    word: "Doubtful",
    difficulty: "intermediate",
    meaning: "Şüpheli; emin olmayan.",
    example: "He feels doubtful about it.",
    hint: "Kararsız kaldığın an.",
  },
  {
    word: "Motivated",
    difficulty: "intermediate",
    meaning: "Motive olmuş; istekli.",
    example: "I feel motivated today.",
    hint: "Bir şey yapmak için hevesli olduğun an.",
  },
  {
    word: "Lazy",
    difficulty: "beginner",
    meaning: "Tembel; isteksiz.",
    example: "He feels lazy on Sundays.",
    hint: "Hareket etmek istemediğin an.",
  },
  {
    word: "Helpful",
    difficulty: "beginner",
    meaning: "Yardımsever; destek olan.",
    example: "She is helpful to others.",
    hint: "Birine el uzattığın an.",
  },
  {
    word: "Thoughtful",
    difficulty: "intermediate",
    meaning: "Düşünceli; başkalarını önemseyen.",
    example: "He is thoughtful and kind.",
    hint: "Başkasını düşündüğün an.",
  },
  {
    word: "Cheerful",
    difficulty: "beginner",
    meaning: "Neşeli; keyifli.",
    example: "She looks cheerful today.",
    hint: "Keyfinin yerinde olduğu an.",
  },
  {
    word: "Moody",
    difficulty: "intermediate",
    meaning: "Huysuz; ruh hali sık değişen.",
    example: "He feels moody today.",
    hint: "Ruh halinin hızlı değiştiği an.",
  },
  {
    word: "Quiet",
    difficulty: "beginner",
    meaning: "Sessiz; sakin.",
    example: "The child is quiet.",
    hint: "Az konuşulan an.",
  },
  {
    word: "Open",
    difficulty: "beginner",
    meaning: "Açık; duygularını paylaşan.",
    example: "She is open about feelings.",
    hint: "İçini rahatça döktüğün an.",
  },
  {
    word: "Closed",
    difficulty: "beginner",
    meaning: "Kapalı; duygularını saklayan.",
    example: "He is closed emotionally.",
    hint: "İçine attığın an.",
  },
  {
    word: "Supportive",
    difficulty: "intermediate",
    meaning: "Destekleyici; yanında olan.",
    example: "She is supportive of friends.",
    hint: "Birine moral verdiğin an.",
  },
  {
    word: "Loyal",
    difficulty: "intermediate",
    meaning: "Sadık; bağlı.",
    example: "He is loyal to his team.",
    hint: "Bırakmadığın birini düşün.",
  },
  {
    word: "Stubborn",
    difficulty: "intermediate",
    meaning: "İnatçı; fikrini değiştirmeyen.",
    example: "He is stubborn sometimes.",
    hint: "Direttiğin bir an.",
  },
  {
    word: "Flexible",
    difficulty: "intermediate",
    meaning: "Esnek; uyumlu.",
    example: "She is flexible with plans.",
    hint: "Kolayca uyum sağladığın an.",
  },
  {
    word: "Gentle",
    difficulty: "intermediate",
    meaning: "Yumuşak; nazik.",
    example: "He has a gentle voice.",
    hint: "Sakin ve yumuşak bir ton.",
  },
  {
    word: "Calm",
    difficulty: "beginner",
    meaning: "Sakin; huzurlu.",
    example: "Stay calm and breathe.",
    hint: "Telaşsız bir an.",
  },
  {
    word: "Focused",
    difficulty: "intermediate",
    meaning: "Odaklanmış; dikkatini veren.",
    example: "She is focused on work.",
    hint: "Dikkatini topladığın an.",
  },
  {
    word: "Distracted",
    difficulty: "intermediate",
    meaning: "Dikkati dağılmış.",
    example: "He feels distracted today.",
    hint: "Aklının başka yerde olduğu an.",
  },
  {
    word: "Secure",
    difficulty: "intermediate",
    meaning: "Güvende; emin.",
    example: "She feels secure at home.",
    hint: "Rahat ve güvende hissettiğin an.",
  },
  {
    word: "Insecure",
    difficulty: "intermediate",
    meaning: "Güvensiz; kendinden emin olmayan.",
    example: "He feels insecure sometimes.",
    hint: "Kendini sorguladığın an.",
  },
  {
    word: "Satisfied",
    difficulty: "intermediate",
    meaning: "Tatmin olmuş; memnun.",
    example: "I am satisfied with my work.",
    hint: "Sonuçtan mutlu olduğun an.",
  },
  {
    word: "Peaceful",
    difficulty: "intermediate",
    meaning: "Huzurlu; sakin.",
    example: "The place feels peaceful.",
    hint: "İç huzurunu hissettiğin an.",
  },
  {
    word: "Melancholic",
    difficulty: "advanced",
    meaning: "Melankolik; derin, hafif hüzünlü ve düşünceli bir ruh hâli.",
    example: "He felt melancholic while walking alone at night.",
    hint: "Sessiz bir akşam, hafif bir hüzün ve düşüncelere dalmak.",
  },
  {
    word: "Resentful",
    difficulty: "advanced",
    meaning:
      "Kin dolu; geçmişte yaşanan bir haksızlıktan dolayı içten içe öfkeli olma durumu.",
    example: "She grew resentful after being ignored for years.",
    hint: "İçinde biriken ama dışarı vurulmayan bir kırgınlık düşün.",
  },
  {
    word: "Euphoric",
    difficulty: "advanced",
    meaning: "Öforik; aşırı mutlu, coşkulu ve enerjik hissetme durumu.",
    example: "He felt euphoric after hearing the good news.",
    hint: "Kalbin hızlı atıyor, her şey mükemmel gibi hissediliyor.",
  },
  {
    word: "Apathetic",
    difficulty: "advanced",
    meaning: "Apatik; ilgi, istek veya duygu eksikliği yaşama durumu.",
    example: "She became apathetic toward things she once loved.",
    hint: "Hiçbir şeyin seni heyecanlandırmadığı o boşluk hissi.",
  },
  {
    word: "Anxious",
    difficulty: "advanced",
    meaning:
      "Endişeli; gelecekle ilgili belirsizlikten kaynaklanan huzursuzluk.",
    example: "He felt anxious before the important meeting.",
    hint: "İçinde hafif bir gerginlik ve bekleme hissi var.",
  },
  {
    word: "Overwhelmed",
    difficulty: "advanced",
    meaning:
      "Bunalmış; duygusal veya zihinsel olarak fazla yük altında hissetme durumu.",
    example: "She felt overwhelmed by her responsibilities.",
    hint: "Aynı anda çok fazla şeyle baş etmeye çalışıyorsun.",
  },
  {
    word: "Content",
    difficulty: "advanced",
    meaning: "Tatmin olmuş; sahip olduklarıyla huzurlu ve memnun olma durumu.",
    example: "He felt content with his simple life.",
    hint: "Her şey yeterli ve yerli yerinde gibi geliyor.",
  },
  {
    word: "Irritated",
    difficulty: "advanced",
    meaning: "Sinirlenmiş; küçük şeylere karşı bile tahammülsüz olma durumu.",
    example: "She felt irritated by the constant noise.",
    hint: "En ufak şey bile seni rahatsız ediyor.",
  },
  {
    word: "Nostalgic",
    difficulty: "advanced",
    meaning: "Nostaljik; geçmişe özlem ve duygusal bağlılık hissetme durumu.",
    example: "The old song made him feel nostalgic.",
    hint: "Eski bir anı aklına geliyor ve içini yumuşak bir özlem kaplıyor.",
  },
  {
    word: "Insecure",
    difficulty: "advanced",
    meaning:
      "Güvensiz; kendine veya bir duruma karşı yeterince güven duyamama hâli.",
    example: "She felt insecure about her abilities.",
    hint: "Kendini sorguladığın o iç ses.",
  },
  {
    word: "Relieved",
    difficulty: "advanced",
    meaning:
      "Rahatlamış; endişe veya stresin ortadan kalkmasıyla gelen ferahlık.",
    example: "He felt relieved after the exam ended.",
    hint: "Omuzlarından büyük bir yük kalkmış gibi.",
  },
  {
    word: "Frustrated",
    difficulty: "advanced",
    meaning:
      "Hayal kırıklığına uğramış; istenen sonuca ulaşılamadığında hissedilen gerginlik.",
    example: "She felt frustrated by the lack of progress.",
    hint: "Çabalıyorsun ama sonuç alamıyorsun.",
  },
  {
    word: "Empathetic",
    difficulty: "advanced",
    meaning:
      "Empatik; başkalarının duygularını anlayabilme ve hissedebilme yetisi.",
    example: "He is very empathetic toward his friends.",
    hint: "Karşındakinin yerine kendini koyuyorsun.",
  },
  {
    word: "Detached",
    difficulty: "advanced",
    meaning: "Mesafeli; duygusal olarak uzak ve kopuk olma durumu.",
    example: "She remained emotionally detached.",
    hint: "Olan biteni uzaktan izliyormuş gibi hissetmek.",
  },
  {
    word: "Vulnerable",
    difficulty: "advanced",
    meaning: "Savunmasız; duygusal olarak açık ve incinebilir olma hâli.",
    example: "He felt vulnerable sharing his feelings.",
    hint: "Kalbin açık ama biraz korunmasız.",
  },
  {
    word: "Conflicted",
    difficulty: "advanced",
    meaning: "Çelişkili; birden fazla duygu arasında kalmış olma durumu.",
    example: "She felt conflicted about her decision.",
    hint: "İki farklı duygu seni farklı yönlere çekiyor.",
  },
  {
    word: "Ashamed",
    difficulty: "advanced",
    meaning:
      "Utanmış; yapılan bir davranıştan dolayı pişmanlık ve mahcubiyet hissetme durumu.",
    example: "He felt ashamed of his actions.",
    hint: "Keşke yapmasaydım dediğin bir an.",
  },
  {
    word: "Hopeful",
    difficulty: "advanced",
    meaning: "Umutlu; geleceğe dair olumlu beklenti içinde olma durumu.",
    example: "She remained hopeful despite the challenges.",
    hint: "Henüz her şey bitmiş değil hissi.",
  },
  {
    word: "Restless",
    difficulty: "advanced",
    meaning: "Huzursuz; yerinde duramama ve içsel rahatlık eksikliği.",
    example: "He felt restless throughout the night.",
    hint: "İçinde tarif edemediğin bir kıpırtı var.",
  },
  {
    word: "Fulfilled",
    difficulty: "advanced",
    meaning:
      "Tatmin olmuş; duygusal olarak tamamlanmış ve doyuma ulaşmış hissetme durumu.",
    example: "She felt fulfilled by helping others.",
    hint: "İçten gelen bir tamamlanmışlık hissi.",
  },
];
