export const EMOTIONS_WORDS = [
  {
    word: "Happy",
    meaning: "Mutlu; sevinçli ve iyi hissetme durumu.",
    example: "I feel happy today.",
    hint: "Yüzünde istemsiz bir gülümseme belirdiğini düşün.",
  },
  {
    word: "Sad",
    meaning: "Üzgün; moralin bozuk olduğu durum.",
    example: "She feels sad after the movie.",
    hint: "İçinin biraz sıkıldığı anlar.",
  },
  {
    word: "Angry",
    meaning: "Kızgın; öfkeli hissetme durumu.",
    example: "He is angry about the delay.",
    hint: "Sinirinin yükseldiği bir anı hatırla.",
  },
  {
    word: "Calm",
    meaning: "Sakin; huzurlu ve rahat.",
    example: "She stays calm in stressful moments.",
    hint: "Derin bir nefes aldığın an.",
  },
  {
    word: "Excited",
    meaning: "Heyecanlı; sabırsız ve istekli.",
    example: "I am excited about the trip.",
    hint: "Kalbin biraz daha hızlı atıyor.",
  },
  {
    word: "Nervous",
    meaning: "Gergin; endişeli ve huzursuz.",
    example: "He feels nervous before exams.",
    hint: "Ellerinin biraz terlediğini düşün.",
  },
  {
    word: "Relaxed",
    meaning: "Rahatlamış; stresin az olduğu durum.",
    example: "I feel relaxed after work.",
    hint: "Omuzlarının gevşediğini hisset.",
  },
  {
    word: "Proud",
    meaning: "Gururlu; kendinle memnun olma durumu.",
    example: "She is proud of her success.",
    hint: "Başardığın bir şeyi hatırla.",
  },
  {
    word: "Shy",
    meaning: "Çekingen; utangaç.",
    example: "He is shy around new people.",
    hint: "Kalabalıkta konuşmaktan çekindiğin an.",
  },
  {
    word: "Confident",
    meaning: "Kendine güvenen; emin.",
    example: "She feels confident at work.",
    hint: "Kendinden emin durduğunu düşün.",
  },
  {
    word: "Brave",
    meaning: "Cesur; korkuya rağmen harekete geçen.",
    example: "He is brave in difficult times.",
    hint: "Korkmana rağmen devam ettiğin an.",
  },
  {
    word: "Kind",
    meaning: "Nazik; iyi kalpli.",
    example: "She is kind to everyone.",
    hint: "Birine yardım ettiğin an.",
  },
  {
    word: "Friendly",
    meaning: "Canayakın; sıcakkanlı.",
    example: "He is friendly with guests.",
    hint: "Kolayca sohbet başlattığın an.",
  },
  {
    word: "Quiet",
    meaning: "Sessiz; az konuşan.",
    example: "She is quiet in meetings.",
    hint: "Daha çok dinlediğin anlar.",
  },
  {
    word: "Talkative",
    meaning: "Konuşkan; çok konuşan.",
    example: "He is very talkative.",
    hint: "Sohbetin hiç bitmediği an.",
  },
  {
    word: "Patient",
    meaning: "Sabırlı; beklemeye dayanıklı.",
    example: "She is patient with children.",
    hint: "Beklerken sakin kaldığını düşün.",
  },
  {
    word: "Impatient",
    meaning: "Sabırsız; beklemekte zorlanan.",
    example: "He gets impatient easily.",
    hint: "Zaman geçmiyor gibi hissettiğin an.",
  },
  {
    word: "Lazy",
    meaning: "Tembel; harekete geçmek istemeyen.",
    example: "I feel lazy today.",
    hint: "Kalkmak istemediğin bir gün.",
  },
  {
    word: "Active",
    meaning: "Hareketli; enerjik.",
    example: "She is active in the morning.",
    hint: "Yerinde duramadığın an.",
  },
  {
    word: "Serious",
    meaning: "Ciddi; şaka yapmayan.",
    example: "He looks serious today.",
    hint: "Odaklandığın bir an.",
  },
  {
    word: "Funny",
    meaning: "Eğlenceli; güldüren.",
    example: "She is really funny.",
    hint: "Gülmene sebep olan biri.",
  },
  {
    word: "Positive",
    meaning: "Pozitif; olumlu düşünen.",
    example: "He has a positive attitude.",
    hint: "İyi tarafı gördüğün an.",
  },
  {
    word: "Negative",
    meaning: "Negatif; olumsuz düşünen.",
    example: "She feels negative today.",
    hint: "Hep kötü ihtimali düşündüğün an.",
  },
  {
    word: "Optimistic",
    meaning: "İyimser; umutlu.",
    example: "He is optimistic about life.",
    hint: "Geleceğe umutla baktığın an.",
  },
  {
    word: "Pessimistic",
    meaning: "Kötümser; umutsuz.",
    example: "She sounds pessimistic.",
    hint: "Sonucun kötü olacağını düşündüğün an.",
  },
  {
    word: "Sensitive",
    meaning: "Hassas; kolay etkilenen.",
    example: "He is sensitive to criticism.",
    hint: "Küçük şeylere alındığın an.",
  },
  {
    word: "Strong",
    meaning: "Güçlü; dayanıklı.",
    example: "She is strong emotionally.",
    hint: "Zor durumda ayakta kaldığın an.",
  },
  {
    word: "Weak",
    meaning: "Zayıf; dayanıklılığı az.",
    example: "He feels weak today.",
    hint: "Enerjinin düştüğü an.",
  },
  {
    word: "Curious",
    meaning: "Meraklı; öğrenmek isteyen.",
    example: "I am curious about this topic.",
    hint: "Bir şeyin nedenini sorduğun an.",
  },
  {
    word: "Bored",
    meaning: "Sıkılmış; ilgisiz.",
    example: "She feels bored at home.",
    hint: "Zaman geçmiyor gibi hissettiğin an.",
  },
  {
    word: "Interested",
    meaning: "İlgili; merak duyan.",
    example: "He is interested in art.",
    hint: "Dikkatini çeken bir konu.",
  },
  {
    word: "Tired",
    meaning: "Yorgun; enerjisi az.",
    example: "I am tired after work.",
    hint: "Gözlerinin kapandığı an.",
  },
  {
    word: "Energetic",
    meaning: "Enerjik; canlı.",
    example: "She feels energetic today.",
    hint: "Çok hareketli hissettiğin an.",
  },
  {
    word: "Lonely",
    meaning: "Yalnız; tek başına hisseden.",
    example: "He feels lonely sometimes.",
    hint: "Kimseyle konuşmadığın an.",
  },
  {
    word: "Loved",
    meaning: "Sevilmiş; değer verilen.",
    example: "She feels loved by her family.",
    hint: "Değerli hissettiğin an.",
  },
  {
    word: "Hopeful",
    meaning: "Umutlu; beklentisi olan.",
    example: "I feel hopeful about tomorrow.",
    hint: "İyi bir şey olacağını düşündüğün an.",
  },
  {
    word: "Afraid",
    meaning: "Korkmuş; endişeli.",
    example: "He is afraid of heights.",
    hint: "Biraz ürktüğün an.",
  },
  {
    word: "Surprised",
    meaning: "Şaşırmış; beklemediği bir durum yaşayan.",
    example: "She was surprised by the gift.",
    hint: "Beklenmedik bir şey oldu.",
  },
  {
    word: "Satisfied",
    meaning: "Memnun; tatmin olmuş.",
    example: "I am satisfied with the result.",
    hint: "İçin rahatladığı an.",
  },
  {
    word: "Jealous",
    meaning: "Kıskanç; başkasını çekemeyen.",
    example: "He feels jealous sometimes.",
    hint: "Başkasında olanı istediğin an.",
  },
  {
    word: "Grateful",
    meaning: "Minnettar; şükreden.",
    example: "She feels grateful for help.",
    hint: "Teşekkür etmek istediğin an.",
  },
  {
    word: "Polite",
    meaning: "Kibar; nazik.",
    example: "He is polite to elders.",
    hint: "Lütfen dediğin an.",
  },
  {
    word: "Rude",
    meaning: "Kaba; kırıcı.",
    example: "She was rude to him.",
    hint: "Sözlerin sertleştiği an.",
  },
  {
    word: "Honest",
    meaning: "Dürüst; doğruyu söyleyen.",
    example: "He is honest with friends.",
    hint: "Gerçeği saklamadığın an.",
  },
  {
    word: "Creative",
    meaning: "Yaratıcı; yeni fikirler üreten.",
    example: "She is very creative.",
    hint: "Farklı bir fikir bulduğun an.",
  },
  {
    word: "Careful",
    meaning: "Dikkatli; temkinli.",
    example: "Be careful with the glass.",
    hint: "Acele etmediğin an.",
  },
  {
    word: "Careless",
    meaning: "Dikkatsiz; umursamaz.",
    example: "He was careless with money.",
    hint: "Detayları kaçırdığın an.",
  },
  {
    word: "Trusting",
    meaning: "Güvenen; kolay inanan.",
    example: "She is trusting by nature.",
    hint: "İnsanlara çabuk güvendiğin an.",
  },
  {
    word: "Doubtful",
    meaning: "Şüpheli; emin olmayan.",
    example: "He feels doubtful about it.",
    hint: "Kararsız kaldığın an.",
  },
  {
    word: "Motivated",
    meaning: "Motive olmuş; istekli.",
    example: "I feel motivated today.",
    hint: "Bir şey yapmak için hevesli olduğun an.",
  },
  {
    word: "Lazy",
    meaning: "Tembel; isteksiz.",
    example: "He feels lazy on Sundays.",
    hint: "Hareket etmek istemediğin an.",
  },
  {
    word: "Helpful",
    meaning: "Yardımsever; destek olan.",
    example: "She is helpful to others.",
    hint: "Birine el uzattığın an.",
  },
  {
    word: "Thoughtful",
    meaning: "Düşünceli; başkalarını önemseyen.",
    example: "He is thoughtful and kind.",
    hint: "Başkasını düşündüğün an.",
  },
  {
    word: "Cheerful",
    meaning: "Neşeli; keyifli.",
    example: "She looks cheerful today.",
    hint: "Keyfinin yerinde olduğu an.",
  },
  {
    word: "Moody",
    meaning: "Huysuz; ruh hali sık değişen.",
    example: "He feels moody today.",
    hint: "Ruh halinin hızlı değiştiği an.",
  },
  {
    word: "Quiet",
    meaning: "Sessiz; sakin.",
    example: "The child is quiet.",
    hint: "Az konuşulan an.",
  },
  {
    word: "Open",
    meaning: "Açık; duygularını paylaşan.",
    example: "She is open about feelings.",
    hint: "İçini rahatça döktüğün an.",
  },
  {
    word: "Closed",
    meaning: "Kapalı; duygularını saklayan.",
    example: "He is closed emotionally.",
    hint: "İçine attığın an.",
  },
  {
    word: "Supportive",
    meaning: "Destekleyici; yanında olan.",
    example: "She is supportive of friends.",
    hint: "Birine moral verdiğin an.",
  },
  {
    word: "Loyal",
    meaning: "Sadık; bağlı.",
    example: "He is loyal to his team.",
    hint: "Bırakmadığın birini düşün.",
  },
  {
    word: "Stubborn",
    meaning: "İnatçı; fikrini değiştirmeyen.",
    example: "He is stubborn sometimes.",
    hint: "Direttiğin bir an.",
  },
  {
    word: "Flexible",
    meaning: "Esnek; uyumlu.",
    example: "She is flexible with plans.",
    hint: "Kolayca uyum sağladığın an.",
  },
  {
    word: "Gentle",
    meaning: "Yumuşak; nazik.",
    example: "He has a gentle voice.",
    hint: "Sakin ve yumuşak bir ton.",
  },
  {
    word: "Calm",
    meaning: "Sakin; huzurlu.",
    example: "Stay calm and breathe.",
    hint: "Telaşsız bir an.",
  },
  {
    word: "Focused",
    meaning: "Odaklanmış; dikkatini veren.",
    example: "She is focused on work.",
    hint: "Dikkatini topladığın an.",
  },
  {
    word: "Distracted",
    meaning: "Dikkati dağılmış.",
    example: "He feels distracted today.",
    hint: "Aklının başka yerde olduğu an.",
  },
  {
    word: "Secure",
    meaning: "Güvende; emin.",
    example: "She feels secure at home.",
    hint: "Rahat ve güvende hissettiğin an.",
  },
  {
    word: "Insecure",
    meaning: "Güvensiz; kendinden emin olmayan.",
    example: "He feels insecure sometimes.",
    hint: "Kendini sorguladığın an.",
  },
  {
    word: "Satisfied",
    meaning: "Tatmin olmuş; memnun.",
    example: "I am satisfied with my work.",
    hint: "Sonuçtan mutlu olduğun an.",
  },
  {
    word: "Peaceful",
    meaning: "Huzurlu; sakin.",
    example: "The place feels peaceful.",
    hint: "İç huzurunu hissettiğin an.",
  },
];
