export const FOOD_WORDS = [
  {
    word: "Recipe",
    difficulty: "intermediate",
    meaning: "Tarif; belirli bir yemeği hazırlamak için gerekli malzemeleri ve izlenecek adımları açıklayan yönerge.",
    example: "I followed a simple recipe for tomato soup.",
    hint: "Bir sayfada adım adım yazılmış, mutfakta sana rehberlik eden kısa talimatları gözünde canlandır.",
  },
  {
    word: "Ingredient",
    difficulty: "intermediate",
    meaning: "Malzeme; bir yemeğin hazırlanmasında kullanılan her bir bileşen.",
    example: "Fresh ingredients make a big difference in taste.",
    hint: "Tezgâhın üzerinde dizili un, yumurta, süt gibi parçaları; hepsinin birleşip bir yemeğe dönüştüğünü düşün.",
  },
  {
    word: "Flavor",
    difficulty: "intermediate",
    meaning: "Lezzet; bir yiyecek veya içeceğin tat ve koku bileşiminin oluşturduğu duyusal özellik.",
    example: "This sauce has a rich flavor.",
    hint: "İlk lokmada ‘işte bu’ dedirten o tadı hayal et.",
  },
  {
    word: "Taste",
    difficulty: "beginner",
    meaning: "Tat; dilin algıladığı temel duyusal özellik (tatlı, tuzlu, ekşi, acı vb.).",
    example: "I like the taste of fresh basil.",
    hint: "Dilin üzerinde kalan o kısa ama net hissi düşün.",
  },
  {
    word: "Spice",
    difficulty: "intermediate",
    meaning: "Baharat; yiyeceğe aroma ve tat vermek için kullanılan bitkisel kökenli kurutulmuş ürün.",
    example: "Add a little spice to the soup.",
    hint: "Küçük bir tutamın bile bütün yemeği değiştirdiğini hayal et.",
  },
  {
    word: "Salt",
    difficulty: "beginner",
    meaning: "Tuz; yiyeceğe tat vermek ve bazı gıdaları korumak için kullanılan mineral.",
    example: "Please pass the salt.",
    hint: "Masadaki küçük tuzluğu; bir çevirişte yemeğe denge kattığını düşün.",
  },
  {
    word: "Pepper",
    difficulty: "beginner",
    meaning: "Karabiber; yiyeceğe keskinlik ve aroma katan baharat.",
    example: "I sprinkled pepper on my eggs.",
    hint: "Taze öğütülmüş karabiberin kokusunu hayal et.",
  },
  {
    word: "Oil",
    difficulty: "beginner",
    meaning: "Yağ; pişirme ve tatlandırma amacıyla kullanılan sıvı veya yarı katı yağlı madde.",
    example: "Heat the oil in a pan.",
    hint: "Tavaya dökülen ince bir yağ tabakasının parlayışını düşün.",
  },
  {
    word: "Butter",
    difficulty: "beginner",
    meaning: "Tereyağı; süt yağından elde edilen, pişirmede ve sürmede kullanılan yağ ürünü.",
    example: "Butter makes the bread taste better.",
    hint: "Sıcakta yavaşça eriyip mis gibi koku yayan sarı bir parça hayal et.",
  },
  {
    word: "Boil",
    difficulty: "intermediate",
    meaning: "Kaynatmak; bir sıvıyı kaynama noktasına getirerek pişirmek veya ısıtmak.",
    example: "Boil the pasta for ten minutes.",
    hint: "Tencerede kabarcık kabarcık yükselen suyu ve çıkan buharı gözünde canlandır.",
  },
  {
    word: "Fry",
    difficulty: "intermediate",
    meaning: "Kızartmak; yiyeceği yağ içinde veya yağla yüksek ısıda pişirmek.",
    example: "We fry the onions until golden.",
    hint: "Cızır cızır sesini ve kenarların kızarmasını hayal et.",
  },
  {
    word: "Bake",
    difficulty: "intermediate",
    meaning: "Fırınlamak; yiyeceği fırında kuru ısıyla pişirmek.",
    example: "I bake bread on Sundays.",
    hint: "Fırından gelen sıcak ekmek kokusunu düşün.",
  },
  {
    word: "Grill",
    difficulty: "intermediate",
    meaning: "Izgara yapmak; yiyeceği ızgara üzerinde doğrudan ısıyla pişirmek.",
    example: "They grill chicken with lemon.",
    hint: "Izgara çizgilerini ve hafif is kokusunu hayal et.",
  },
  {
    word: "Slice",
    difficulty: "intermediate",
    meaning: "Dilimlemek; bir yiyeceği ince ve düz parçalar hâlinde kesmek.",
    example: "Slice the tomatoes thinly.",
    hint: "Bıçağın ritmik hareketiyle ince dilimler çıktığını düşün.",
  },
  {
    word: "Chop",
    difficulty: "intermediate",
    meaning: "Doğramak; yiyeceği küçük parçalara ayıracak şekilde kesmek.",
    example: "Chop the vegetables for the salad.",
    hint: "Tahtaya vuran bıçak sesiyle küçük parçaların biriktiğini hayal et.",
  },
  {
    word: "Mix",
    difficulty: "intermediate",
    meaning: "Karıştırmak; malzemeleri homojen olacak şekilde bir araya getirmek.",
    example: "Mix the flour and water in a bowl.",
    hint: "Bir kâsede döne döne birleşen malzemeleri gözünde canlandır.",
  },
  {
    word: "Stir",
    difficulty: "intermediate",
    meaning: "Karıştırmak; özellikle sıvı veya yarı sıvı karışımı kaşıkla çevirerek hareket ettirmek.",
    example: "Stir the sauce slowly.",
    hint: "Kaşığın tencerede ağır ağır döndüğünü düşün.",
  },
  {
    word: "Serve",
    difficulty: "intermediate",
    meaning: "Servis etmek; yiyecek veya içeceği sunmak ve masaya getirmek.",
    example: "They serve breakfast until 11 a.m.",
    hint: "Tabağın masaya konduğu o ‘hazır’ anını hayal et.",
  },
  {
    word: "Menu",
    difficulty: "intermediate",
    meaning: "Menü; bir işletmede sunulan yiyecek ve içeceklerin listesi.",
    example: "The menu has many vegetarian options.",
    hint: "Sayfaları çevirirken iştahını kabartan seçenekleri düşün.",
  },
  {
    word: "Order",
    difficulty: "intermediate",
    meaning: "Sipariş vermek; bir yiyecek veya içeceğin hazırlanmasını talep etmek.",
    example: "We order two coffees and a sandwich.",
    hint: "Garsona söyleyip birkaç dakika sonra masaya gelen lezzeti hayal et.",
  },
  {
    word: "Reservation",
    difficulty: "intermediate",
    meaning: "Rezervasyon; belirli bir tarih ve saat için yer ayırtma işlemi.",
    example: "I made a reservation for dinner.",
    hint: "İsminin yazıldığı, senin için ayrılmış bir masayı düşün.",
  },
  {
    word: "Bill",
    difficulty: "intermediate",
    meaning: "Hesap; bir restoranda alınan ürün ve hizmetlerin toplam ücretini gösteren belge veya tutar.",
    example: "Could we have the bill, please?",
    hint: "Yemeğin sonundaki küçük kâğıt; toplamı görüp plan yaptığın anı hayal et.",
  },
  {
    word: "Tip",
    difficulty: "intermediate",
    meaning: "Bahşiş; hizmet karşılığında gönüllü olarak verilen ek ödeme.",
    example: "We left a tip for the waiter.",
    hint: "Memnun kaldığın hizmete küçük bir teşekkür bıraktığını düşün.",
  },
  {
    word: "Dessert",
    difficulty: "intermediate",
    meaning: "Tatlı; genellikle yemeğin sonunda tüketilen, tatlı lezzette yiyecek.",
    example: "Chocolate cake is my favorite dessert.",
    hint: "Son lokmada gelen o tatlı kapanışı hayal et.",
  },

  {
    word: "Breakfast",
    difficulty: "beginner",
    meaning: "Kahvaltı; günün başında tüketilen ilk öğün.",
    example: "I usually have breakfast at home.",
    hint: "Sabah masasında çay, ekmek ve hafif bir başlangıç hayal et.",
  },
  {
    word: "Lunch",
    difficulty: "beginner",
    meaning: "Öğle yemeği; gün ortasında tüketilen ana öğün.",
    example: "We eat lunch around noon.",
    hint: "Günün ortasında kısa bir mola ve sıcak bir tabak düşün.",
  },
  {
    word: "Dinner",
    difficulty: "beginner",
    meaning: "Akşam yemeği; günün sonunda tüketilen ana öğün.",
    example: "Dinner is ready at seven.",
    hint: "Gün bitmiş, masada herkes toplanmış; sıcak bir yemek hayal et.",
  },
  {
    word: "Snack",
    difficulty: "beginner",
    meaning: "Atıştırmalık; ana öğünler arasında tüketilen küçük yiyecek.",
    example: "I grab a snack in the afternoon.",
    hint: "Açlığı bastıran küçük ama keyifli bir lokmayı düşün.",
  },
  {
    word: "Plate",
    difficulty: "intermediate",
    meaning: "Tabak; yiyeceklerin servis edildiği düz mutfak gereci.",
    example: "The plate is full of food.",
    hint: "Önüne konmuş, renkli yemeklerle dolu bir tabak hayal et.",
  },
  {
    word: "Bowl",
    difficulty: "intermediate",
    meaning: "Kâse; genellikle çorba veya sıvı yiyecekler için kullanılan derin kap.",
    example: "She served soup in a bowl.",
    hint: "İçinde sıcak çorba olan derin bir kâse düşün.",
  },
  {
    word: "Fork",
    difficulty: "intermediate",
    meaning: "Çatal; yiyecekleri tutmak ve yemek için kullanılan sofra gereci.",
    example: "Use a fork to eat pasta.",
    hint: "Masada tabağın yanında duran metal bir çatalı hayal et.",
  },
  {
    word: "Knife",
    difficulty: "intermediate",
    meaning: "Bıçak; yiyecekleri kesmek için kullanılan kesici alet.",
    example: "Cut the meat with a knife.",
    hint: "Yemeği düzgün parçalara ayıran keskin bir bıçak düşün.",
  },
  {
    word: "Spoon",
    difficulty: "intermediate",
    meaning: "Kaşık; sıvı veya yumuşak yiyecekleri yemek için kullanılan gereç.",
    example: "I eat soup with a spoon.",
    hint: "Kaşığın çorbaya daldığı anı hayal et.",
  },
  {
    word: "Cup",
    difficulty: "intermediate",
    meaning: "Fincan; sıcak veya soğuk içecekler için kullanılan küçük kap.",
    example: "She drank tea from a cup.",
    hint: "Elinde sıcak bir içecekle ısındığını düşün.",
  },
  {
    word: "Glass",
    difficulty: "intermediate",
    meaning: "Bardak; genellikle soğuk içecekler için kullanılan kap.",
    example: "He filled the glass with water.",
    hint: "Şeffaf bir bardakta suyun doluşunu hayal et.",
  },
  {
    word: "Drink",
    difficulty: "beginner",
    meaning: "İçecek; içmek için hazırlanan sıvı madde.",
    example: "This drink is very refreshing.",
    hint: "Serinleten bir yudum aldığını düşün.",
  },
  {
    word: "Water",
    difficulty: "beginner",
    meaning: "Su; yaşam için gerekli, renksiz ve tatsız sıvı.",
    example: "Drink more water during the day.",
    hint: "Bir bardak soğuk suyun ferahlığını hayal et.",
  },
  {
    word: "Tea",
    difficulty: "beginner",
    meaning: "Çay; demlenerek hazırlanan sıcak içecek.",
    example: "I like to drink tea in the morning.",
    hint: "Dumanı tüten bir çay bardağını düşün.",
  },
  {
    word: "Coffee",
    difficulty: "beginner",
    meaning: "Kahve; kavrulmuş kahve çekirdeklerinden elde edilen içecek.",
    example: "Coffee helps me wake up.",
    hint: "Kokusuyla bile uyandıran bir fincan kahve hayal et.",
  },
  {
    word: "Soup",
    difficulty: "beginner",
    meaning: "Çorba; genellikle sıcak servis edilen sıvı yiyecek.",
    example: "Soup is perfect for cold days.",
    hint: "Kaşıkla içilen sıcak ve rahatlatıcı bir tabak düşün.",
  },
  {
    word: "Salad",
    difficulty: "intermediate",
    meaning: "Salata; çiğ veya pişmiş sebzelerden yapılan hafif yiyecek.",
    example: "I ordered a green salad.",
    hint: "Renkli sebzelerle dolu taze bir tabak hayal et.",
  },
  {
    word: "Bread",
    difficulty: "beginner",
    meaning: "Ekmek; undan yapılan temel gıda maddesi.",
    example: "Fresh bread smells amazing.",
    hint: "Fırından yeni çıkmış ekmeğin kokusunu düşün.",
  },
  {
    word: "Rice",
    difficulty: "beginner",
    meaning: "Pirinç; birçok yemekte kullanılan temel tahıl.",
    example: "Rice goes well with vegetables.",
    hint: "Beyaz ve tane tane bir pilav hayal et.",
  },
  {
    word: "Pasta",
    difficulty: "intermediate",
    meaning: "Makarna; undan yapılan ve kaynatılarak pişirilen yiyecek.",
    example: "Pasta is easy to cook.",
    hint: "Sosla kaplanmış sıcak makarnayı düşün.",
  },
  {
    word: "Meat",
    difficulty: "beginner",
    meaning: "Et; hayvan dokusundan elde edilen besin.",
    example: "This dish contains meat.",
    hint: "Ana yemeğin merkezinde duran bir parça eti hayal et.",
  },
  {
    word: "Chicken",
    difficulty: "beginner",
    meaning: "Tavuk; yaygın olarak tüketilen beyaz et türü.",
    example: "Chicken is a popular choice.",
    hint: "Izgarada pişmiş tavuk kokusunu düşün.",
  },
  {
    word: "Fish",
    difficulty: "beginner",
    meaning: "Balık; deniz veya tatlı suda yaşayan canlılardan elde edilen besin.",
    example: "Fish is very healthy.",
    hint: "Deniz kokulu, hafif bir yemek hayal et.",
  },
  {
    word: "Vegetable",
    difficulty: "intermediate",
    meaning: "Sebze; bitkilerin yenilebilir kısımları.",
    example: "Vegetables are good for health.",
    hint: "Renkli ve taze sebzelerle dolu bir sepet düşün.",
  },
  {
    word: "Fruit",
    difficulty: "intermediate",
    meaning: "Meyve; genellikle tatlı olan bitkisel gıda.",
    example: "Fruit is a natural snack.",
    hint: "Sulu ve ferahlatıcı bir meyveyi hayal et.",
  },
  {
    word: "Sweet",
    difficulty: "beginner",
    meaning: "Tatlı; şekerli lezzete sahip yiyecek.",
    example: "I crave something sweet.",
    hint: "Küçük bir mutluluk gibi gelen tatlı tadı düşün.",
  },
  {
    word: "Spicy",
    difficulty: "intermediate",
    meaning: "Acılı; baharatlı ve yakıcı tat içeren.",
    example: "This dish is too spicy for me.",
    hint: "Ağzında hafif bir yanma bırakan tadı hayal et.",
  },
  {
    word: "Fresh",
    difficulty: "intermediate",
    meaning: "Taze; yeni hazırlanmış veya yeni toplanmış.",
    example: "Fresh food tastes better.",
    hint: "Yeni yapılmış, canlı renkli yiyecekleri düşün.",
  },
  {
    word: "Cook",
    difficulty: "beginner",
    meaning: "Pişirmek; yiyeceği yenilebilir hâle getirmek.",
    example: "I like to cook at home.",
    hint: "Mutfağa girip bir şeyler hazırladığını hayal et.",
  },
  {
    word: "Kitchen",
    difficulty: "beginner",
    meaning: "Mutfak; yemek hazırlanan alan.",
    example: "The kitchen smells great.",
    hint: "Tencere ve tabak sesleriyle dolu bir mutfak düşün.",
  },
];
