export const HEALTH_WORDS = [
  {
    word: "Healthy",
    difficulty: "beginner",
    meaning: "Sağlıklı; sağlığı yerinde olan veya sağlığı destekleyen.",
    example: "Eating vegetables helps you stay healthy.",
    hint: "Kendini enerjik, hafif ve iyi hissettiğin bir günü hayal et.",
  },
  {
    word: "Lifestyle",
    difficulty: "intermediate",
    meaning: "Yaşam tarzı; bir kişinin günlük yaşam biçimi ve alışkanlıkları.",
    example: "He changed his lifestyle after moving to a new city.",
    hint: "Gün içinde nasıl yaşadığını: uyku, yemek, hareket… hepsini bir bütün olarak düşün.",
  },
  {
    word: "Habit",
    difficulty: "beginner",
    meaning: "Alışkanlık; düzenli olarak tekrarlanan davranış.",
    example: "Brushing your teeth is a good habit.",
    hint: "Her gün fark etmeden yaptığın küçük bir şeyi gözünde canlandır.",
  },
  {
    word: "Routine",
    difficulty: "beginner",
    meaning: "Rutin; düzenli olarak uygulanan günlük düzen.",
    example: "My morning routine includes a short walk.",
    hint: "Sabah uyanınca hep aynı sırayla yaptığın adımları düşün.",
  },
  {
    word: "Exercise",
    difficulty: "intermediate",
    meaning: "Egzersiz; vücudu güçlendirmek için yapılan fiziksel çalışma.",
    example: "Exercise improves your mood and energy.",
    hint: "Vücudunu canlandıran, terlettiği halde iyi hissettiren bir hareketi hayal et.",
  },
  {
    word: "Workout",
    difficulty: "intermediate",
    meaning: "Antrenman; planlı egzersiz seansı.",
    example: "She does a quick workout at home.",
    hint: "Kısa bir süre içinde nefesini hızlandıran bir antrenmanı düşün.",
  },
  {
    word: "Gym",
    difficulty: "beginner",
    meaning: "Spor salonu; egzersiz yapılan yer.",
    example: "I go to the gym three times a week.",
    hint: "Ağırlıklar, koşu bandı ve hareket eden insanlar olan bir salonu hayal et.",
  },
  {
    word: "Walk",
    difficulty: "beginner",
    meaning: "Yürümek; adım atarak ilerlemek.",
    example: "We walk to the park after dinner.",
    hint: "Sakin bir sokakta rahat adımlarla yürüdüğünü düşün.",
  },
  {
    word: "Run",
    difficulty: "beginner",
    meaning: "Koşmak; hızlı şekilde ilerlemek.",
    example: "He runs every morning before work.",
    hint: "Rüzgârın yüzüne çarptığı, ritimli adımlarla koştuğun bir anı hayal et.",
  },
  {
    word: "Stretch",
    difficulty: "intermediate",
    meaning: "Esnetmek; kasları germek ve uzatmak.",
    example: "Stretch your legs before you start.",
    hint: "Kollarını yukarı uzatıp vücudunun açıldığını hissettiğin anı düşün.",
  },
  {
    word: "Warm-up",
    difficulty: "intermediate",
    meaning: "Isınma; egzersiz öncesi vücudu hazırlama.",
    example: "A warm-up helps prevent injuries.",
    hint: "Hareketlere başlamadan önce yavaşça ısındığını hayal et.",
  },
  {
    word: "Cool-down",
    difficulty: "intermediate",
    meaning: "Soğuma; egzersiz sonrası vücudu sakinleştirme.",
    example: "Do a cool-down after your workout.",
    hint: "Koşudan sonra yavaşlayıp nefesini düzene soktuğun anı düşün.",
  },
  {
    word: "Yoga",
    difficulty: "beginner",
    meaning: "Yoga; nefes, esneme ve denge odaklı egzersiz.",
    example: "Yoga helps me relax after a long day.",
    hint: "Sessiz bir ortamda derin nefes alıp esnediğini hayal et.",
  },
  {
    word: "Meditation",
    difficulty: "intermediate",
    meaning: "Meditasyon; zihni sakinleştirmeye yönelik odaklanma uygulaması.",
    example: "Meditation can reduce stress.",
    hint: "Gözlerini kapatıp sadece nefesine odaklandığın bir anı düşün.",
  },
  {
    word: "Breath",
    difficulty: "beginner",
    meaning: "Nefes; soluk alıp verme.",
    example: "Take a deep breath and relax.",
    hint: "Derin bir nefes alıp omuzlarının gevşediğini hayal et.",
  },
  {
    word: "Breathe",
    difficulty: "beginner",
    meaning: "Nefes almak; soluk alıp vermek.",
    example: "Breathe slowly when you feel nervous.",
    hint: "Nefesini yavaşlatıp kalbinin sakinleştiğini düşün.",
  },
  {
    word: "Sleep",
    difficulty: "beginner",
    meaning: "Uyku; dinlenme hâli.",
    example: "Good sleep improves your focus.",
    hint: "Yumuşak bir yastığa başını koyup rahatça uyuduğunu hayal et.",
  },
  {
    word: "Rest",
    difficulty: "beginner",
    meaning: "Dinlenmek; yorgunluğu azaltmak için ara vermek.",
    example: "Rest for a few minutes before you continue.",
    hint: "Kısa bir mola verip bedeninin toparlandığını düşün.",
  },
  {
    word: "Nap",
    difficulty: "beginner",
    meaning: "Kısa uyku; gün içinde yapılan kısa dinlenme uykusu.",
    example: "A short nap can boost your energy.",
    hint: "Öğleden sonra 15 dakikalık tatlı bir uyuklamayı hayal et.",
  },
  {
    word: "Energy",
    difficulty: "beginner",
    meaning: "Enerji; hareket ve iş yapma gücü.",
    example: "I feel more energy after a healthy breakfast.",
    hint: "Güne zinde başlayıp her şeye yetiştiğin bir sabahı düşün.",
  },
  {
    word: "Tired",
    difficulty: "beginner",
    meaning: "Yorgun; dinlenmeye ihtiyaç duyan.",
    example: "I feel tired after a long day.",
    hint: "Göz kapaklarının ağırlaştığı o yorgun anı hayal et.",
  },
  {
    word: "Fatigue",
    difficulty: "intermediate",
    meaning: "Yorgunluk; uzun süren bitkinlik hâli.",
    example: "Fatigue can affect your performance.",
    hint: "Vücudunun ‘dur’ dediği, gücünün azaldığı bir anı düşün.",
  },
  {
    word: "Stress",
    difficulty: "beginner",
    meaning: "Stres; zihinsel veya fiziksel gerginlik durumu.",
    example: "Stress can make it hard to sleep.",
    hint: "Omuzlarının gerildiği yoğun bir günü hayal et.",
  },
  {
    word: "Relax",
    difficulty: "beginner",
    meaning: "Rahatlamak; gerginliği azaltmak.",
    example: "Music helps me relax.",
    hint: "Derin nefes alıp gevşediğin sakin bir anı düşün.",
  },
  {
    word: "Balance",
    difficulty: "beginner",
    meaning: "Denge; vücudun veya yaşamın uyumlu hâli.",
    example: "Balance is important for a healthy lifestyle.",
    hint: "Her şeyin kararında olduğu, düzenli bir yaşamı gözünde canlandır.",
  },
  {
    word: "Diet",
    difficulty: "intermediate",
    meaning: "Diyet; beslenme düzeni.",
    example: "He follows a balanced diet.",
    hint: "Tabakta farklı besinlerin dengeli durduğu bir öğünü hayal et.",
  },
  {
    word: "Nutrition",
    difficulty: "intermediate",
    meaning: "Beslenme; vücudun ihtiyaçlarına uygun gıda alma süreci.",
    example: "Nutrition affects your overall health.",
    hint: "Vücudunu ‘doğru yakıtla’ beslediğini düşün.",
  },
  {
    word: "Calorie",
    difficulty: "intermediate",
    meaning: "Kalori; besinlerin enerji ölçü birimi.",
    example: "This snack has fewer calories.",
    hint: "Yediğin bir şeyin sana enerji verdiğini hayal et.",
  },
  {
    word: "Protein",
    difficulty: "intermediate",
    meaning: "Protein; kas ve doku yapımı için gerekli besin öğesi.",
    example: "Protein helps build muscle.",
    hint: "Kaslarının güçlendiğini hissettiğin bir antrenman sonrası düşün.",
  },
  {
    word: "Vitamin",
    difficulty: "intermediate",
    meaning: "Vitamin; vücut işlevleri için gerekli organik bileşik.",
    example: "Oranges are rich in vitamin C.",
    hint: "Parlak turuncu bir portakalı soyduğunu hayal et.",
  },
  {
    word: "Mineral",
    difficulty: "intermediate",
    meaning: "Mineral; vücudun ihtiyaç duyduğu inorganik besin öğesi.",
    example: "Milk contains important minerals.",
    hint: "Günlük beslenmenin küçük ama önemli parçalarını düşün.",
  },
  {
    word: "Hydration",
    difficulty: "intermediate",
    meaning: "Hidrasyon; vücudun yeterli sıvı alması durumu.",
    example: "Hydration is important during exercise.",
    hint: "Su içince ferahladığın o hissi gözünde canlandır.",
  },
  {
    word: "Hydrate",
    difficulty: "intermediate",
    meaning: "Sıvı almak; vücudu suyla desteklemek.",
    example: "Remember to hydrate during the day.",
    hint: "Yanında bir su şişesi taşıyıp sık sık yudumladığını düşün.",
  },
  {
    word: "Water",
    difficulty: "beginner",
    meaning: "Su; yaşamsal sıvı.",
    example: "Drink water regularly.",
    hint: "Serin bir bardak su içip ferahladığını hayal et.",
  },
  {
    word: "Bottle",
    difficulty: "beginner",
    meaning: "Şişe; sıvı taşımaya yarayan kap.",
    example: "I carry a water bottle to work.",
    hint: "Çantanda duran su şişesini ve gün boyu ona uzanmayı düşün.",
  },
  {
    word: "Breakfast",
    difficulty: "beginner",
    meaning: "Kahvaltı; günün ilk öğünü.",
    example: "Breakfast gives me energy in the morning.",
    hint: "Sıcak çay ve hafif bir kahvaltı sofrasını hayal et.",
  },
  {
    word: "Lunch",
    difficulty: "beginner",
    meaning: "Öğle yemeği; gün ortası öğünü.",
    example: "We have lunch at noon.",
    hint: "Öğle arasında kısa bir mola verip yemek yediğini düşün.",
  },
  {
    word: "Dinner",
    difficulty: "beginner",
    meaning: "Akşam yemeği; günün son ana öğünü.",
    example: "Dinner is ready at seven.",
    hint: "Akşam evde sıcak bir yemek kokusunu hayal et.",
  },
  {
    word: "Snack",
    difficulty: "beginner",
    meaning: "Atıştırmalık; ara öğün.",
    example: "I grab a healthy snack in the afternoon.",
    hint: "Küçük bir şey yiyip enerjinin yükseldiğini düşün.",
  },
  {
    word: "Fruit",
    difficulty: "beginner",
    meaning: "Meyve; yenilebilir tatlı ürün.",
    example: "Fruit is a healthy choice.",
    hint: "Renkli meyvelerle dolu bir tabağı hayal et.",
  },
  {
    word: "Vegetable",
    difficulty: "beginner",
    meaning: "Sebze; sağlıklı besin grubu.",
    example: "Vegetables are good for your body.",
    hint: "Yeşil, taze sebzelerin çıtırtısını düşün.",
  },
  {
    word: "Salad",
    difficulty: "beginner",
    meaning: "Salata; karışık sebzelerden oluşan yiyecek.",
    example: "I ate a salad for lunch.",
    hint: "Renk renk malzemelerle dolu bir kâseyi hayal et.",
  },
  {
    word: "Soup",
    difficulty: "beginner",
    meaning: "Çorba; sulu sıcak yemek.",
    example: "Soup is comforting on cold days.",
    hint: "Soğuk bir günde sıcak çorbanın içini ısıttığını düşün.",
  },
  {
    word: "Sugar",
    difficulty: "beginner",
    meaning: "Şeker; tatlandırıcı madde.",
    example: "Too much sugar is not good for health.",
    hint: "Tatlı bir şey yedikten sonra gelen hızlı enerji hissini düşün.",
  },
  {
    word: "Salt",
    difficulty: "beginner",
    meaning: "Tuz; yiyeceğe tat veren mineral.",
    example: "Use less salt in your meals.",
    hint: "Yemeğe az tuz ekleyince tadın daha dengeli olduğunu hayal et.",
  },
  {
    word: "Fiber",
    difficulty: "intermediate",
    meaning: "Lif; sindirimi destekleyen besin öğesi.",
    example: "Fiber helps your digestion.",
    hint: "Tam tahıllı bir ekmeğin tok tutan hissini düşün.",
  },
  {
    word: "Appetite",
    difficulty: "intermediate",
    meaning: "İştah; yeme isteği.",
    example: "My appetite increases after exercise.",
    hint: "Spor sonrası ‘acıkma’ hissinin güçlendiğini hayal et.",
  },
  {
    word: "Digest",
    difficulty: "intermediate",
    meaning: "Sindirmek; yiyeceği vücudun işlemesi.",
    example: "It takes time to digest a big meal.",
    hint: "Yemekten sonra karnının yavaşça rahatladığını düşün.",
  },
  {
    word: "Health",
    difficulty: "beginner",
    meaning: "Sağlık; bedenin ve zihnin iyi olma hâli.",
    example: "Health is more important than speed.",
    hint: "Kendini iyi hissettiğin, rahat hareket ettiğin bir günü hayal et.",
  },
  {
    word: "Body",
    difficulty: "beginner",
    meaning: "Vücut; insan bedeni.",
    example: "Your body needs rest and water.",
    hint: "Bedeninin sana gün boyu eşlik eden bir ‘ekip arkadaşı’ olduğunu düşün.",
  },
  {
    word: "Mind",
    difficulty: "beginner",
    meaning: "Zihin; düşünme ve algılama sistemi.",
    example: "A calm mind helps you focus.",
    hint: "Kafanın içinin sessizleştiği, berrak bir anı hayal et.",
  },
  {
    word: "Mood",
    difficulty: "beginner",
    meaning: "Ruh hâli; duygusal durum.",
    example: "A walk can improve your mood.",
    hint: "Kısa bir yürüyüşten sonra yüzünün güldüğünü düşün.",
  },
  {
    word: "Hygiene",
    difficulty: "intermediate",
    meaning: "Hijyen; sağlığı korumaya yönelik temizlik uygulamaları.",
    example: "Good hygiene prevents illness.",
    hint: "Temiz, ferah bir hisle gününü sürdürdüğünü hayal et.",
  },
  {
    word: "Clean",
    difficulty: "beginner",
    meaning: "Temiz; kirden arınmış.",
    example: "Keep your hands clean.",
    hint: "Yeni yıkanmış ellerin ferahlığını düşün.",
  },
  {
    word: "Wash",
    difficulty: "beginner",
    meaning: "Yıkamak; suyla temizlemek.",
    example: "Wash your hands before eating.",
    hint: "Musluktan akan suyun ellerini temizlediğini hayal et.",
  },
  {
    word: "Soap",
    difficulty: "beginner",
    meaning: "Sabun; temizleyici madde.",
    example: "Soap removes dirt and germs.",
    hint: "Sabunun köpürdüğünü ve mis gibi koktuğunu düşün.",
  },
  {
    word: "Shower",
    difficulty: "beginner",
    meaning: "Duş; suyla yıkanma.",
    example: "I take a shower after the gym.",
    hint: "Sıcak suyun üstünden akıp rahatlatmasını hayal et.",
  },
  {
    word: "Toothbrush",
    difficulty: "beginner",
    meaning: "Diş fırçası; diş temizleme aracı.",
    example: "I bought a new toothbrush.",
    hint: "Sabah diş fırçalarken ağzının tazelenmesini düşün.",
  },
  {
    word: "Toothpaste",
    difficulty: "beginner",
    meaning: "Diş macunu; diş temizleyici ürün.",
    example: "This toothpaste tastes minty.",
    hint: "Nane gibi taze bir tatla ağzının ferahladığını hayal et.",
  },
  {
    word: "Floss",
    difficulty: "beginner",
    meaning: "Diş ipi; diş arası temizliği için ip.",
    example: "Flossing keeps your gums healthy.",
    hint: "Dişlerinin arasının pırıl pırıl temizlendiğini düşün.",
  },
  {
    word: "Sanitizer",
    difficulty: "intermediate",
    meaning: "Dezenfektan; mikropları azaltan sıvı/jel.",
    example: "Use sanitizer when you can’t wash your hands.",
    hint: "Ellerini hızlıca temizleyip rahatladığını hayal et.",
  },
  {
    word: "Mask",
    difficulty: "beginner",
    meaning: "Maske; yüzü kapatan koruyucu ürün.",
    example: "He wore a mask on the bus.",
    hint: "Kalabalıkta kendini daha güvende hissettiğini düşün.",
  },
  {
    word: "Doctor",
    difficulty: "beginner",
    meaning: "Doktor; tıbbi tedavi uzmanı.",
    example: "The doctor gave me advice.",
    hint: "Muayenede güven veren bir ses tonunu hayal et.",
  },
  {
    word: "Nurse",
    difficulty: "beginner",
    meaning: "Hemşire; sağlık hizmetlerinde görevli personel.",
    example: "The nurse checked my temperature.",
    hint: "Hastanede yardımcı olan, sakin birini düşün.",
  },
  {
    word: "Hospital",
    difficulty: "beginner",
    meaning: "Hastane; sağlık hizmeti kurumu.",
    example: "The hospital is near my home.",
    hint: "Beyaz koridorlar ve düzenli bir ortamı hayal et.",
  },
  {
    word: "Clinic",
    difficulty: "intermediate",
    meaning: "Klinik; sağlık hizmeti verilen küçük merkez.",
    example: "I went to a clinic for a checkup.",
    hint: "Kısa bir kontrol için gittiğin küçük bir sağlık merkezini düşün.",
  },
  {
    word: "Checkup",
    difficulty: "intermediate",
    meaning: "Kontrol; sağlık durumunu değerlendirme muayenesi.",
    example: "I get a checkup every year.",
    hint: "Yılda bir kez ‘her şey yolunda mı?’ diye baktırdığını hayal et.",
  },
  {
    word: "Appointment",
    difficulty: "intermediate",
    meaning: "Randevu; belirli bir zaman için görüşme planı.",
    example: "I made an appointment with the dentist.",
    hint: "Takvimine bir saat yazıp o gününü planladığını düşün.",
  },
  {
    word: "Medicine",
    difficulty: "beginner",
    meaning: "İlaç; tedavi amaçlı kullanılan madde.",
    example: "Take your medicine after meals.",
    hint: "İyileşmek için düzenli aldığın bir ilacı hayal et.",
  },
  {
    word: "Pill",
    difficulty: "beginner",
    meaning: "Hap; küçük ilaç tabletı.",
    example: "I took a pill for my headache.",
    hint: "Su ile kolayca yuttuğun küçük bir tableti düşün.",
  },
  {
    word: "Syrup",
    difficulty: "beginner",
    meaning: "Şurup; sıvı ilaç.",
    example: "This cough syrup tastes sweet.",
    hint: "Öksürük için içtiğin tatlı bir şurubu hayal et.",
  },
  {
    word: "Vaccine",
    difficulty: "intermediate",
    meaning: "Aşı; bağışıklık kazandıran tıbbi uygulama.",
    example: "Vaccines protect against diseases.",
    hint: "Vücuduna ‘koruma kalkanı’ eklediğini düşün.",
  },
  {
    word: "Symptom",
    difficulty: "intermediate",
    meaning: "Belirti; hastalığın işareti.",
    example: "Fever is a common symptom.",
    hint: "Vücudunun ‘bir şey var’ diye sinyal verdiği küçük işaretleri düşün.",
  },
  {
    word: "Pain",
    difficulty: "beginner",
    meaning: "Ağrı; rahatsızlık veren duygu.",
    example: "I felt pain in my back.",
    hint: "Canını sıkan bir noktayı fark ettiğin anı hayal et.",
  },
  {
    word: "Headache",
    difficulty: "beginner",
    meaning: "Baş ağrısı; baş bölgesinde ağrı.",
    example: "I have a headache today.",
    hint: "Başının ağırlaştığı o hissi düşün.",
  },
  {
    word: "Fever",
    difficulty: "beginner",
    meaning: "Ateş; vücut sıcaklığının yükselmesi.",
    example: "He has a fever and needs rest.",
    hint: "Alnının sıcaklaştığı ve üşüdüğün bir anı hayal et.",
  },
  {
    word: "Cough",
    difficulty: "beginner",
    meaning: "Öksürük; boğazdan gelen refleks.",
    example: "She has a cough in winter.",
    hint: "Boğazını gıdıklayan o öksürük hissini düşün.",
  },
  {
    word: "Cold",
    difficulty: "beginner",
    meaning: "Soğuk algınlığı; yaygın üst solunum enfeksiyonu.",
    example: "I caught a cold last week.",
    hint: "Burnun tıkandığı, mendil taşıdığın günleri hayal et.",
  },
  {
    word: "Allergy",
    difficulty: "intermediate",
    meaning: "Alerji; bağışıklık sisteminin aşırı tepkisi.",
    example: "My allergy gets worse in spring.",
    hint: "Bahar gelince hapşırdığın çiçekli günleri düşün.",
  },
  {
    word: "Injury",
    difficulty: "intermediate",
    meaning: "Yaralanma; fiziksel zarar görme.",
    example: "He got an injury while playing football.",
    hint: "Bir yerini incitip dikkatli yürüdüğün anı hayal et.",
  },
  {
    word: "Wound",
    difficulty: "intermediate",
    meaning: "Yara; dokuda oluşan hasar.",
    example: "Clean the wound carefully.",
    hint: "Küçük bir çizik ve üzerine bant yapıştırdığını düşün.",
  },
  {
    word: "Bandage",
    difficulty: "intermediate",
    meaning: "Bandaj; yarayı saran koruyucu materyal.",
    example: "The bandage kept the cut clean.",
    hint: "Yaranın üstünü kapatıp güvende hissettiğin anı hayal et.",
  },
  {
    word: "Muscle",
    difficulty: "intermediate",
    meaning: "Kas; hareket sağlayan doku.",
    example: "My muscles feel sore after training.",
    hint: "Antrenman sonrası kaslarının ‘çalıştım’ diye sızladığını düşün.",
  },
  {
    word: "Bone",
    difficulty: "intermediate",
    meaning: "Kemik; iskelet yapısını oluşturan doku.",
    example: "Bones support the body.",
    hint: "Vücudunun sağlam bir iskeletle ayakta durduğunu hayal et.",
  },
  {
    word: "Heart",
    difficulty: "beginner",
    meaning: "Kalp; kan dolaşımını sağlayan organ.",
    example: "My heart beats faster when I run.",
    hint: "Koşunca kalbinin hızlandığını ve bunu hissettiğini düşün.",
  },
  {
    word: "Lung",
    difficulty: "intermediate",
    meaning: "Akciğer; solunum organı.",
    example: "Healthy lungs help you breathe better.",
    hint: "Derin nefes alıp göğsünün dolduğunu hayal et.",
  },
  {
    word: "Stomach",
    difficulty: "beginner",
    meaning: "Mide; sindirim organı.",
    example: "My stomach feels better now.",
    hint: "Karnının rahatladığı o huzurlu hissi düşün.",
  },
  {
    word: "Skin",
    difficulty: "beginner",
    meaning: "Cilt; vücudu kaplayan doku.",
    example: "Skin needs moisture and care.",
    hint: "Yumuşak ve bakımlı bir cildi hayal et.",
  },
  {
    word: "Blood",
    difficulty: "intermediate",
    meaning: "Kan; damarların içindeki sıvı.",
    example: "Blood carries oxygen in the body.",
    hint: "Vücudunda dolaşan ‘yaşam akışını’ düşün.",
  },
  {
    word: "Pressure",
    difficulty: "intermediate",
    meaning: "Basınç; uygulanan kuvvetin etkisi.",
    example: "My blood pressure is normal.",
    hint: "Kendini sakin hissedince her şeyin dengelendiğini hayal et.",
  },
  {
    word: "Pulse",
    difficulty: "intermediate",
    meaning: "Nabız; kalp atım sayısı.",
    example: "The nurse checked my pulse.",
    hint: "Bileğine dokunup atışlarını saydığın anı düşün.",
  },
  {
    word: "Temperature",
    difficulty: "intermediate",
    meaning: "Sıcaklık; ısı derecesi.",
    example: "They measured my temperature.",
    hint: "Termometreyle ölçüm yapıldığını hayal et.",
  },
  {
    word: "Weight",
    difficulty: "intermediate",
    meaning: "Kilo; vücut ağırlığı.",
    example: "My weight stayed the same this month.",
    hint: "Tartıya çıkıp rakamı gördüğün anı düşün.",
  },
  {
    word: "Height",
    difficulty: "intermediate",
    meaning: "Boy; vücut uzunluğu.",
    example: "His height is written on his ID card.",
    hint: "Duvara yaslanıp boyunun ölçüldüğünü hayal et.",
  },
  {
    word: "Scale",
    difficulty: "intermediate",
    meaning: "Tartı; ağırlık ölçme aracı.",
    example: "The scale is in the bathroom.",
    hint: "Banyoda duran küçük tartıyı gözünde canlandır.",
  },
  {
    word: "Step",
    difficulty: "beginner",
    meaning: "Adım; yürüyüşte atılan hareket birimi.",
    example: "I reached ten thousand steps today.",
    hint: "Gün boyu birikerek artan adım sayını hayal et.",
  },
  {
    word: "Pedometer",
    difficulty: "intermediate",
    meaning: "Adımsayar; adım sayan cihaz/uygulama.",
    example: "My pedometer tracks my daily steps.",
    hint: "Telefonunun adımlarını saydığını ve seni motive ettiğini düşün.",
  },
  {
    word: "Posture",
    difficulty: "intermediate",
    meaning: "Duruş; vücudun oturma/ayakta durma şekli.",
    example: "Good posture helps your back.",
    hint: "Omuzlarını geriye alıp daha dik durduğunu hayal et.",
  },
  {
    word: "Back",
    difficulty: "beginner",
    meaning: "Sırt; vücudun arka kısmı.",
    example: "My back feels better after stretching.",
    hint: "Esnetince sırtının rahatladığını düşün.",
  },
  {
    word: "Sunscreen",
    difficulty: "intermediate",
    meaning: "Güneş kremi; UV ışınlarına karşı koruyucu ürün.",
    example: "I use sunscreen on sunny days.",
    hint: "Güneşli bir günde cildini koruduğunu hayal et.",
  },
] as const;
