export const NATURE_WORDS = [
  {
    word: "Forest",
    difficulty: "beginner",
    meaning: "Orman; yoğun ağaç topluluklarından oluşan geniş doğal alan.",
    example: "We walked through the forest in the afternoon.",
    hint: "Etrafında uzun ağaçlar, kuş sesleri ve yaprak kokusu olan bir yürüyüş hayal et.",
  },
  {
    word: "River",
    difficulty: "beginner",
    meaning: "Nehir; belirli bir yatakta akarak denize, göle veya başka bir akarsuya ulaşan büyük su kütlesi.",
    example: "The river flows quietly past the town.",
    hint: "Sürekli akan serin bir su şeridini ve kıyısındaki taşları düşün.",
  },
  {
    word: "Lake",
    difficulty: "beginner",
    meaning: "Göl; karalarla çevrili, durağan veya yavaş hareket eden doğal su birikintisi.",
    example: "The lake looked calm at sunrise.",
    hint: "Sabah ışığında aynaya benzeyen durgun bir su yüzeyi hayal et.",
  },
  {
    word: "Mountain",
    difficulty: "beginner",
    meaning: "Dağ; çevresine göre belirgin biçimde yükselen büyük yer şekli.",
    example: "They climbed the mountain before winter.",
    hint: "Bulutlara yakın, zirvesi serin ve rüzgârlı bir yüksekliği gözünde canlandır.",
  },
  {
    word: "Valley",
    difficulty: "intermediate",
    meaning: "Vadi; iki yükselti arasında uzanan, genellikle akarsu tarafından şekillendirilmiş çukur alan.",
    example: "A small village sits in the valley.",
    hint: "İki tepenin arasında yeşil bir koridor gibi uzanan sakin bir alan düşün.",
  },
  {
    word: "Ocean",
    difficulty: "intermediate",
    meaning: "Okyanus; kıtalar arasında uzanan, dünyanın en büyük tuzlu su kütlesi.",
    example: "The ocean was rough during the storm.",
    hint: "Ucu bucağı görünmeyen dalgaları ve tuzlu rüzgârı hayal et.",
  },
  {
    word: "Beach",
    difficulty: "beginner",
    meaning: "Sahil; deniz veya göl kıyısındaki kumlu ya da çakıllı alan.",
    example: "We stayed on the beach until sunset.",
    hint: "Ayaklarının altında sıcak kum ve uzaktan gelen dalga sesi düşün.",
  },
  {
    word: "Rain",
    difficulty: "beginner",
    meaning: "Yağmur; atmosferdeki su buharının yoğunlaşarak damlacıklar hâlinde yeryüzüne düşmesi.",
    example: "It started to rain in the evening.",
    hint: "Camda tık tık ses çıkaran damlaları ve ıslak asfalt kokusunu hayal et.",
  },
  {
    word: "Snow",
    difficulty: "beginner",
    meaning: "Kar; su buharının donarak kristaller hâlinde yeryüzüne düşmesiyle oluşan yağış türü.",
    example: "Snow covered the streets overnight.",
    hint: "Sessizce yağan beyaz tanelerin her şeyi yumuşattığı bir manzarayı düşün.",
  },
  {
    word: "Wind",
    difficulty: "beginner",
    meaning: "Rüzgâr; hava kütlelerinin basınç farkı nedeniyle yatay yönde hareket etmesi.",
    example: "The wind was strong near the coast.",
    hint: "Saçlarını uçuran, ağaç yapraklarını hışırdatan serin bir esintiyi hayal et.",
  },
  {
    word: "Cloud",
    difficulty: "beginner",
    meaning: "Bulut; atmosferde asılı duran su damlacıkları veya buz kristallerinden oluşan kütle.",
    example: "Dark clouds filled the sky.",
    hint: "Gökyüzünde pamuk gibi dolaşan şekilleri ve gölgelerini düşün.",
  },
  {
    word: "Storm",
    difficulty: "intermediate",
    meaning: "Fırtına; şiddetli rüzgârla birlikte yağış ve elektriksel olayların görülebildiği hava olayı.",
    example: "The storm knocked down a few branches.",
    hint: "Gök gürültüsü, hızlanan rüzgâr ve aniden kararan gökyüzünü gözünde canlandır.",
  },
  {
    word: "Thunder",
    difficulty: "intermediate",
    meaning: "Gök gürültüsü; yıldırımın oluşturduğu ani ısınmanın yarattığı ses olayı.",
    example: "We heard thunder in the distance.",
    hint: "Uzakta patlayan derin bir ses ve ardından gelen kısa bir sessizlik düşün.",
  },
  {
    word: "Lightning",
    difficulty: "intermediate",
    meaning: "Yıldırım; bulutlar arasında veya bulut ile yer arasında gerçekleşen güçlü elektrik boşalması.",
    example: "Lightning flashed across the sky.",
    hint: "Bir anda gökyüzünü yarıp geçen parlak bir çizgiyi hayal et.",
  },
  {
    word: "Fog",
    difficulty: "intermediate",
    meaning: "Sis; havadaki su buharının yoğunlaşarak görüş mesafesini azaltacak biçimde yere yakın bir tabaka oluşturması.",
    example: "The fog made the road hard to see.",
    hint: "Her şeyin yumuşakça silikleştiği, sessiz bir sabah sahnesi düşün.",
  },
  {
    word: "Sunlight",
    difficulty: "intermediate",
    meaning: "Güneş ışığı; Güneş’ten gelen ve yeryüzünü aydınlatan ışınım.",
    example: "Sunlight warmed the room through the window.",
    hint: "Perdeden süzülen altın rengi ışık çizgilerini hayal et.",
  },
  {
    word: "Shade",
    difficulty: "intermediate",
    meaning: "Gölge; ışığın bir cisim tarafından engellenmesi sonucu oluşan karanlık alan.",
    example: "We sat in the shade under a tree.",
    hint: "Sıcak bir günde ağacın altında serin bir köşeyi düşün.",
  },
  {
    word: "Soil",
    difficulty: "intermediate",
    meaning: "Toprak; bitkilerin yetiştiği, mineral ve organik maddeler içeren yer kabuğu tabakası.",
    example: "The soil is rich and good for gardening.",
    hint: "Avucuna aldığında hafif nemli, kokusu belirgin bir toprak parçasını hayal et.",
  },
  {
    word: "Seed",
    difficulty: "intermediate",
    meaning: "Tohum; bitkilerin çoğalmasını sağlayan, yeni bitkiyi oluşturabilecek yapıda üreme birimi.",
    example: "She planted a seed in the pot.",
    hint: "Minik bir şeyin zamanla kocaman bir bitkiye dönüştüğünü düşün.",
  },
  {
    word: "Tree",
    difficulty: "beginner",
    meaning: "Ağaç; genellikle odunsu gövdeye sahip, uzun ömürlü ve çok yıllık bitki.",
    example: "A tall tree stands near the house.",
    hint: "Dallarıyla gökyüzüne uzanan, altında dinlenilen bir dev hayal et.",
  },
  {
    word: "Leaf",
    difficulty: "beginner",
    meaning: "Yaprak; bitkilerde fotosentez gibi temel işlevleri üstlenen, genellikle yeşil renkli organ.",
    example: "A leaf fell gently to the ground.",
    hint: "Rüzgârla süzülen ince bir yeşil parçayı gözünde canlandır.",
  },
  {
    word: "Wildlife",
    difficulty: "intermediate",
    meaning: "Yaban hayatı; doğal ortamında yaşayan hayvan ve bitkilerin oluşturduğu yaşam topluluğu.",
    example: "This park is home to rich wildlife.",
    hint: "Şehirden uzakta, kendi düzeninde yaşayan hayvanları ve seslerini hayal et.",
  },
  {
    word: "Recycling",
    difficulty: "intermediate",
    meaning: "Geri dönüşüm; atık materyallerin yeniden işlenerek tekrar kullanılabilir hâle getirilmesi süreci.",
    example: "Recycling helps reduce waste.",
    hint: "Boş bir şişenin çöpe gitmek yerine yeni bir şeye dönüşmesini düşün.",
  },
  {
    word: "Pollution",
    difficulty: "intermediate",
    meaning: "Kirlilik; hava, su veya toprağın zararlı maddelerle kirlenmesi sonucu çevresel kalitenin bozulması durumu.",
    example: "Air pollution can affect our health.",
    hint: "Gökyüzünü gri yapan dumanı ve nefes almayı zorlaştıran havayı hayal et.",
  },
  {
    word: "Climate",
    difficulty: "intermediate",
    meaning: "İklim; bir bölgenin uzun yıllar boyunca gözlenen ortalama hava koşulları düzeni.",
    example: "The climate here is mild in spring.",
    hint: "Bir yerin yıllar boyunca nasıl bir havaya sahip olduğunu anlatan büyük resmi düşün.",
  },
  {
    word: "Desert",
    difficulty: "intermediate",
    meaning: "Çöl; çok az yağış alan, bitki örtüsü son derece sınırlı olan geniş kara alanı.",
    example: "The desert is extremely hot during the day.",
    hint: "Gündüz kavurucu sıcak, gece serin bir kum denizini hayal et.",
  },
  {
    word: "Island",
    difficulty: "beginner",
    meaning: "Ada; etrafı tamamen suyla çevrili kara parçası.",
    example: "They spent their holiday on a small island.",
    hint: "Dört yanı suyla çevrili sakin bir kaçış noktası düşün.",
  },
  {
    word: "Waterfall",
    difficulty: "intermediate",
    meaning: "Şelale; akarsuyun yüksek bir noktadan serbestçe dökülmesiyle oluşan doğal oluşum.",
    example: "The waterfall attracts many visitors.",
    hint: "Yukarıdan dökülen güçlü su ve çıkan serin sisi hayal et.",
  },
  {
    word: "Cave",
    difficulty: "intermediate",
    meaning: "Mağara; doğal yollarla oluşmuş yer altı boşluğu.",
    example: "The cave was dark and quiet.",
    hint: "Işığın zor ulaştığı serin ve gizemli bir alan düşün.",
  },
  {
    word: "Volcano",
    difficulty: "intermediate",
    meaning: "Yanardağ; magma, kül ve gaz püskürtebilen yer kabuğu açıklığı.",
    example: "The volcano is no longer active.",
    hint: "İçinde büyük bir güç saklayan dağ gibi bir yapıyı hayal et.",
  },
  {
    word: "Glacier",
    difficulty: "intermediate",
    meaning: "Buzul; uzun yıllar boyunca biriken ve hareket eden büyük buz kütlesi.",
    example: "Glaciers are melting due to warming.",
    hint: "Yavaşça akan devasa bir buz nehrini düşün.",
  },
  {
    word: "Earthquake",
    difficulty: "intermediate",
    meaning: "Deprem; yer kabuğunda ani enerji boşalması sonucu oluşan sarsıntı.",
    example: "The earthquake was felt across the city.",
    hint: "Yerin hafifçe titrediği o ürkütücü anı hayal et.",
  },
  {
    word: "Drought",
    difficulty: "intermediate",
    meaning: "Kuraklık; uzun süreli yağış eksikliği nedeniyle oluşan su kıtlığı durumu.",
    example: "The region suffered from drought.",
    hint: "Toprağın çatladığı ve yağmurun özlendiği bir manzarayı düşün.",
  },
  {
    word: "Flood",
    difficulty: "intermediate",
    meaning: "Sel; suyun normal sınırlarını aşarak çevreyi kaplaması.",
    example: "The flood damaged many houses.",
    hint: "Taşan suların sokakları doldurduğu bir sahneyi hayal et.",
  },
  {
    word: "Breeze",
    difficulty: "intermediate",
    meaning: "Hafif rüzgâr; düşük hızda esen serin hava akımı.",
    example: "A cool breeze came from the sea.",
    hint: "Yüzünü okşayan hafif ve ferah bir esinti düşün.",
  },
  {
    word: "Ecosystem",
    difficulty: "intermediate",
    meaning: "Ekosistem; canlılar ile çevreleri arasındaki etkileşim sistemi.",
    example: "The forest ecosystem is fragile.",
    hint: "Canlıların bir denge içinde birlikte yaşadığı büyük bir düzen hayal et.",
  },
  {
    word: "Habitat",
    difficulty: "intermediate",
    meaning: "Habitat; bir canlının doğal yaşam alanı.",
    example: "This beach is a bird habitat.",
    hint: "Bir canlının kendini evinde hissettiği ortamı düşün.",
  },
  {
    word: "Oxygen",
    difficulty: "intermediate",
    meaning: "Oksijen; canlıların solunum için ihtiyaç duyduğu kimyasal element.",
    example: "Oxygen is essential for life.",
    hint: "Her nefeste fark etmeden aldığın hayati gazı düşün.",
  },
  {
    word: "Carbon",
    difficulty: "intermediate",
    meaning: "Karbon; canlı yaşamının temelini oluşturan kimyasal element.",
    example: "Carbon exists in all living things.",
    hint: "Yaşamın yapı taşlarından birini hayal et.",
  },
  {
    word: "Energy",
    difficulty: "intermediate",
    meaning: "Enerji; iş yapabilme yeteneği.",
    example: "The sun provides clean energy.",
    hint: "Güneşten gelen görünmez gücü düşün.",
  },
  {
    word: "Solar",
    difficulty: "intermediate",
    meaning: "Güneşle ilgili; Güneş’ten kaynaklanan.",
    example: "Solar panels produce electricity.",
    hint: "Güneş ışığını yakalayan panelleri hayal et.",
  },
  {
    word: "Rainforest",
    difficulty: "intermediate",
    meaning: "Yağmur ormanı; yıl boyunca yoğun yağış alan sık orman.",
    example: "Rainforests host diverse species.",
    hint: "Her yerin yeşil olduğu, canlılarla dolu bir orman düşün.",
  },
  {
    word: "Temperature",
    difficulty: "intermediate",
    meaning: "Sıcaklık; bir ortamın ne kadar sıcak veya soğuk olduğunu gösteren ölçü.",
    example: "The temperature dropped at night.",
    hint: "Termometrede yavaşça değişen sayıyı hayal et.",
  },
  {
    word: "Season",
    difficulty: "intermediate",
    meaning: "Mevsim; yılın benzer hava koşullarına sahip dönemlerinden biri.",
    example: "Spring is my favorite season.",
    hint: "Yılın ruhunu belirleyen zaman dilimini düşün.",
  },
  {
    word: "Spring",
    difficulty: "beginner",
    meaning: "İlkbahar; doğanın canlandığı mevsim.",
    example: "Flowers bloom in spring.",
    hint: "Renklerin geri döndüğü, havanın yumuşadığı zamanı hayal et.",
  },
  {
    word: "Summer",
    difficulty: "beginner",
    meaning: "Yaz; yılın en sıcak mevsimi.",
    example: "Summer days are long.",
    hint: "Uzun günler ve sıcak güneşli saatleri düşün.",
  },
  {
    word: "Autumn",
    difficulty: "intermediate",
    meaning: "Sonbahar; yaprakların döküldüğü geçiş mevsimi.",
    example: "Leaves fall in autumn.",
    hint: "Sarı ve turuncu yapraklarla dolu yolları hayal et.",
  },
  {
    word: "Winter",
    difficulty: "beginner",
    meaning: "Kış; yılın en soğuk mevsimi.",
    example: "Winter nights are cold.",
    hint: "Soğuk hava ve kalın giysilerle geçen günleri düşün.",
  },
  {
    word: "Air",
    difficulty: "beginner",
    meaning: "Hava; Dünya’yı saran gaz karışımı.",
    example: "Clean air is important for health.",
    hint: "Derin bir nefes aldığında hissettiğin ferahlığı düşün.",
  },
  {
    word: "Nature",
    difficulty: "beginner",
    meaning: "Doğa; insan müdahalesi olmadan var olan tüm canlı ve cansız varlıklar.",
    example: "Nature helps us relax.",
    hint: "Şehirden uzak, sade ve dengeli bir dünya hayal et.",
  },
  {
    word: "Environment",
    difficulty: "intermediate",
    meaning: "Çevre; canlıların içinde yaşadığı doğal ve yapay koşullar bütünü.",
    example: "We must protect the environment.",
    hint: "Etrafındaki her şeyin bir bütün oluşturduğunu düşün.",
  },
  {
    word: "Green",
    difficulty: "beginner",
    meaning: "Yeşil; doğayı ve bitkileri çağrıştıran renk.",
    example: "Green spaces improve cities.",
    hint: "Bol ağaçlı ve ferah bir alan hayal et.",
  },
  {
    word: "Sustainability",
    difficulty: "intermediate",
    meaning: "Sürdürülebilirlik; doğal kaynakları gelecek nesilleri tehlikeye atmadan kullanma yaklaşımı.",
    example: "Sustainability is a global goal.",
    hint: "Bugünü yaşarken yarını da korumayı düşün.",
  },
  {
    word: "Weather",
    difficulty: "beginner",
    meaning: "Hava durumu; belirli bir zamanda atmosferin durumu.",
    example: "The weather changed suddenly.",
    hint: "Güne başlamadan önce dışarı bakıp hissettiğin havayı düşün.",
  },
] as const;
