export const SPORTS_WORDS = [
  {
    word: "Sport",
    difficulty: "beginner",
    meaning: "Spor; fiziksel beceriyi, dayanıklılığı veya rekabeti içeren düzenli aktivite.",
    example: "Sport helps me feel energetic and focused.",
    hint: "Terlediğin, hareket ettiğin ve kendini daha canlı hissettiğin o anı düşün.",
  },
  {
    word: "Exercise",
    difficulty: "beginner",
    meaning: "Egzersiz; sağlığı korumak veya geliştirmek için yapılan planlı fiziksel çalışma.",
    example: "I do exercise every morning.",
    hint: "Vücudunu çalıştırdığın kısa bir rutin hayal et: nefes, tempo, hareket.",
  },
  {
    word: "Workout",
    difficulty: "beginner",
    meaning: "Antrenman; belirli bir amaç için yapılan egzersiz seansı.",
    example: "My workout takes 30 minutes.",
    hint: "Süre tutup “başlıyorum” dediğin bir spor seansını gözünde canlandır.",
  },
  {
    word: "Warm-up",
    difficulty: "beginner",
    meaning: "Isınma; ana aktiviteye hazırlanmak için yapılan hafif egzersizler.",
    example: "We always do a warm-up before running.",
    hint: "Vücudunun yavaş yavaş açıldığı, kaslarının “tamam, hazırım” dediği an.",
  },
  {
    word: "Stretch",
    difficulty: "beginner",
    meaning: "Esnemek; kasları uzatarak esnekliği artırmak için yapılan hareket.",
    example: "I stretch after my workout.",
    hint: "Kollarını yukarı uzatıp rahatladığın o uzun esneme hissini düşün.",
  },
  {
    word: "Run",
    difficulty: "beginner",
    meaning: "Koşmak; belirli bir hızda ayakla ilerleme eylemi.",
    example: "I run in the park on weekends.",
    hint: "Ayak seslerin ritim tutuyor; rüzgâr yüzüne geliyor—o koşu anını düşün.",
  },
  {
    word: "Jog",
    difficulty: "beginner",
    meaning: "Hafif tempoda koşmak; koşu ile yürüyüş arasında, düşük yoğunluklu koşu.",
    example: "I jog for 15 minutes to warm up.",
    hint: "Konuşabilecek kadar rahat, ama nabzın yükselmiş—hafif tempo koşu.",
  },
  {
    word: "Walk",
    difficulty: "beginner",
    meaning: "Yürümek; adım atarak ilerleme eylemi.",
    example: "We walk to cool down after training.",
    hint: "Antrenman sonrası sakinleştiğin, temponu düşürdüğün yürüyüşü düşün.",
  },
  {
    word: "Jump",
    difficulty: "beginner",
    meaning: "Zıplamak; yerden kısa süreli yükselme hareketi.",
    example: "I jump rope to improve my cardio.",
    hint: "Yerden hafifçe yükselip tekrar indiğin o “hop!” anını hayal et.",
  },
  {
    word: "Push-up",
    difficulty: "beginner",
    meaning: "Şınav; vücut ağırlığıyla yapılan, üst vücut kuvveti geliştiren egzersiz.",
    example: "I can do ten push-ups.",
    hint: "Eller yerde, gövden düz—kendini yukarı itip kontrollü indiğin hareket.",
  },
  {
    word: "Squat",
    difficulty: "beginner",
    meaning: "Squat; diz ve kalça eklemlerini bükerek çömelme esaslı kuvvet egzersizi.",
    example: "Squats make my legs stronger.",
    hint: "Sanki sandalyeye oturacakmış gibi çömelip tekrar kalktığını düşün.",
  },
  {
    word: "Lunge",
    difficulty: "beginner",
    meaning: "Lunge; bir bacağı öne alıp dizleri bükerek yapılan denge ve bacak egzersizi.",
    example: "I do lunges to train my legs.",
    hint: "Bir adım öne, dizler bükülü—dengeyi bulup tekrar toparlandığın hareket.",
  },
  {
    word: "Plank",
    difficulty: "beginner",
    meaning: "Plank; gövdeyi düz tutarak yapılan, core kaslarını güçlendiren izometrik egzersiz.",
    example: "I hold a plank for one minute.",
    hint: "Vücudun tahta gibi düz; zaman geçtikçe titremeye başlayan o duruşu düşün.",
  },
  {
    word: "Team",
    difficulty: "beginner",
    meaning: "Takım; ortak amaç için birlikte çalışan oyuncu veya sporcu grubu.",
    example: "Our team practices twice a week.",
    hint: "Herkes aynı hedef için birlikte—paslaşma, destek, uyum…",
  },
  {
    word: "Coach",
    difficulty: "beginner",
    meaning: "Antrenör; sporcuyu eğiten, yönlendiren ve hazırlayan kişi.",
    example: "My coach gives me helpful tips.",
    hint: "Kenardan taktik veren, seni motive eden o sesi düşün.",
  },
  {
    word: "Practice",
    difficulty: "beginner",
    meaning: "Antrenman yapmak; beceriyi geliştirmek için düzenli tekrar ve çalışma.",
    example: "We practice passing drills.",
    hint: "Aynı hareketi tekrar tekrar yapıp “daha iyi oldu” dediğin anı düşün.",
  },
  {
    word: "Match",
    difficulty: "beginner",
    meaning: "Maç; kurallar çerçevesinde iki tarafın karşılaştığı spor müsabakası.",
    example: "The match starts at 6 p.m.",
    hint: "Başlama düdüğü, heyecan, skor… maç havasını gözünde canlandır.",
  },
  {
    word: "Game",
    difficulty: "beginner",
    meaning: "Oyun; kuralları olan sportif veya rekabetçi etkinlik.",
    example: "We played a friendly game after school.",
    hint: "Eğlenceli ama ciddi: kazanmak da var, keyif de!",
  },
  {
    word: "Score",
    difficulty: "beginner",
    meaning: "Skor; maçtaki sayısal sonuç veya puan durumu.",
    example: "The score is 2–1.",
    hint: "Tabelaya baktığında gördüğün o sayıların heyecanını düşün.",
  },
  {
    word: "Goal",
    difficulty: "beginner",
    meaning: "Gol; topun kaleye çizgiyi geçmesiyle kazanılan sayı.",
    example: "He scored a goal in the last minute.",
    hint: "Top ağlara gidiyor ve herkes bir anda coşuyor—o an!",
  },
  {
    word: "Ball",
    difficulty: "beginner",
    meaning: "Top; birçok sporda kullanılan yuvarlak oyun ekipmanı.",
    example: "Pass the ball, please.",
    hint: "Ayağında ya da elinde dönen o topu düşün; oyun onunla başlıyor.",
  },
  {
    word: "Racket",
    difficulty: "beginner",
    meaning: "Raket; tenis ve benzeri sporlarda topa vurmak için kullanılan ekipman.",
    example: "I bought a new racket yesterday.",
    hint: "Elinde hafif sallanan raketi, topa vurduğunda çıkan sesi düşün.",
  },
  {
    word: "Net",
    difficulty: "beginner",
    meaning: "File; bazı sporlarda alanı ayıran veya hedefi belirleyen ağ yapı.",
    example: "The ball hit the net.",
    hint: "İki tarafı ayıran o ince çizgi gibi fileyi hayal et.",
  },
  {
    word: "Shoes",
    difficulty: "beginner",
    meaning: "Spor ayakkabısı; antrenman sırasında destek ve tutuş sağlayan ayakkabı.",
    example: "Good shoes help prevent injuries.",
    hint: "Zemine daha sağlam bastığın, kaymadığın o rahat ayakkabıları düşün.",
  },
  {
    word: "Gym",
    difficulty: "beginner",
    meaning: "Spor salonu; egzersiz ekipmanlarının bulunduğu antrenman alanı.",
    example: "I go to the gym after work.",
    hint: "Ağırlıklar, koşu bandı ve motivasyon kokusu… salon atmosferi.",
  },
  {
    word: "Weight",
    difficulty: "beginner",
    meaning: "Ağırlık; direnç sağlamak için kullanılan kütle (dambıl, bar vb.).",
    example: "I lifted a heavier weight today.",
    hint: "Eline aldığında “tam kıvamında zor” dediğin o ağırlığı düşün.",
  },
  {
    word: "Reps",
    difficulty: "beginner",
    meaning: "Tekrar sayısı; bir egzersiz hareketinin arka arkaya yapılma adedi.",
    example: "I did 12 reps of squats.",
    hint: "Bir, iki, üç… sayarak yaptığın tekrarları hayal et.",
  },
  {
    word: "Set",
    difficulty: "beginner",
    meaning: "Set; belirli tekrarların oluşturduğu egzersiz grubu.",
    example: "I completed three sets.",
    hint: "Kısa mola—sonra tekrar: “bir set daha” dediğin düzeni düşün.",
  },
  {
    word: "Rest",
    difficulty: "beginner",
    meaning: "Dinlenme; performansı ve toparlanmayı desteklemek için aktiviteye ara verme.",
    example: "I rest for one minute between sets.",
    hint: "Nefesini topladığın, kalbinin sakinleştiği o kısa molayı düşün.",
  },
  {
    word: "Hydrate",
    difficulty: "beginner",
    meaning: "Sıvı almak; vücudun su ihtiyacını karşılamak (hidrasyonu sağlamak).",
    example: "Remember to hydrate during training.",
    hint: "Antrenmanda bir yudum su içip kendine geldiğin anı düşün.",
  },
  {
    word: "Injury",
    difficulty: "beginner",
    meaning: "Sakatlık; spor veya fiziksel aktivite sırasında oluşan yaralanma.",
    example: "He missed the game due to an injury.",
    hint: "Kendini korumayı hatırla: vücut sinyal verince dinlenmek gerek.",
  },
  {
    word: "Helmet",
    difficulty: "beginner",
    meaning: "Kask; başı darbelerden koruyan güvenlik ekipmanı.",
    example: "Always wear a helmet when cycling.",
    hint: "Bisiklete binerken başına taktığın o güvenli kalkanı düşün.",
  },
  {
    word: "Bicycle",
    difficulty: "beginner",
    meaning: "Bisiklet; pedallarla ilerleyen iki tekerlekli araç.",
    example: "I ride my bicycle to stay fit.",
    hint: "Pedal çevirdikçe rüzgârın yüzüne vurduğu o özgür hissi hayal et.",
  },

  {
    word: "Endurance",
    difficulty: "intermediate",
    meaning: "Dayanıklılık; uzun süre fiziksel veya zihinsel eforu sürdürebilme yeteneği.",
    example: "Endurance is important for long-distance running.",
    hint: "Yorulsan bile devam edebildiğin o uzun eforu hayal et.",
  },
  {
    word: "Strength",
    difficulty: "intermediate",
    meaning: "Kuvvet; kasların direnç karşısında güç üretebilme kapasitesi.",
    example: "Strength training helps prevent injuries.",
    hint: "Ağırlığı kaldırırken kaslarının aktifleştiği anı düşün.",
  },
  {
    word: "Agility",
    difficulty: "intermediate",
    meaning: "Çeviklik; hızlı ve kontrollü şekilde yön değiştirebilme yeteneği.",
    example: "Agility is essential in many team sports.",
    hint: "Hızlı adımlar, ani dönüşler—hafif ve kontrollü hareketleri hayal et.",
  },
  {
    word: "Balance",
    difficulty: "intermediate",
    meaning: "Denge; vücudu sabit veya kontrollü şekilde tutabilme becerisi.",
    example: "Balance improves overall athletic performance.",
    hint: "Tek ayak üzerinde durup kontrolü koruduğun o anı düşün.",
  },
  {
    word: "Coordination",
    difficulty: "intermediate",
    meaning: "Koordinasyon; farklı kas gruplarının uyum içinde çalışması.",
    example: "Good coordination helps you move efficiently.",
    hint: "El, göz ve ayakların aynı anda uyumla çalıştığını hayal et.",
  },
  {
    word: "Pace",
    difficulty: "intermediate",
    meaning: "Tempo; bir aktivitenin hızını ve ritmini belirleyen hız düzeyi.",
    example: "She maintained a steady pace throughout the race.",
    hint: "Ne çok hızlı ne çok yavaş—ritmini bulduğun o hızı düşün.",
  },
  {
    word: "Stamina",
    difficulty: "intermediate",
    meaning: "Kondisyon; uzun süre yorulmadan performans gösterebilme gücü.",
    example: "Cycling builds stamina over time.",
    hint: "Başladığın enerjiyi sona kadar koruyabildiğin hissi hayal et.",
  },
  {
    word: "Flexibility",
    difficulty: "intermediate",
    meaning: "Esneklik; eklem ve kasların geniş hareket açıklığına sahip olması.",
    example: "Yoga improves flexibility.",
    hint: "Kaslarının rahatça uzayıp seni kısıtlamadığı o hissi düşün.",
  },
  {
    word: "Intensity",
    difficulty: "intermediate",
    meaning: "Yoğunluk; egzersizin zorluk ve efor seviyesi.",
    example: "High intensity workouts burn more calories.",
    hint: "Nefesinin hızlandığı, odağının arttığı o yoğun anı hayal et.",
  },
  {
    word: "Recovery",
    difficulty: "intermediate",
    meaning: "Toparlanma; egzersiz sonrası vücudun yenilenme süreci.",
    example: "Recovery is as important as training.",
    hint: "Antrenman sonrası rahatlayıp yeniden güç topladığın zamanı düşün.",
  },
  {
    word: "Performance",
    difficulty: "intermediate",
    meaning: "Performans; bir sporcunun ortaya koyduğu fiziksel ve teknik düzey.",
    example: "Her performance improved this season.",
    hint: "Elinden gelenin en iyisini ortaya koyduğun o anı düşün.",
  },
  {
    word: "Technique",
    difficulty: "intermediate",
    meaning: "Teknik; bir hareketin doğru ve etkili uygulanma biçimi.",
    example: "Good technique reduces injury risk.",
    hint: "Hareketi doğru yaptığında daha az zorlandığın hissi düşün.",
  },
  {
    word: "Resistance",
    difficulty: "intermediate",
    meaning: "Direnç; kaslara karşı koyan yük veya kuvvet.",
    example: "Resistance bands are great for training.",
    hint: "Seni zorlayan ama geliştiren o karşı kuvveti hayal et.",
  },
  {
    word: "Sprint",
    difficulty: "intermediate",
    meaning: "Sprint; kısa mesafede maksimum hızla koşma.",
    example: "He finished the race with a sprint.",
    hint: "Son gücünle hızlandığın o patlayıcı anı düşün.",
  },
  {
    word: "Circuit",
    difficulty: "intermediate",
    meaning: "Dairesel antrenman; farklı egzersizlerin arka arkaya yapıldığı çalışma türü.",
    example: "We did a full-body circuit.",
    hint: "İstasyondan istasyona geçtiğin tempolu antrenmanı hayal et.",
  },
  {
    word: "Mobility",
    difficulty: "intermediate",
    meaning: "Hareketlilik; eklemlerin kontrollü ve rahat hareket edebilme kapasitesi.",
    example: "Mobility exercises help joint health.",
    hint: "Hareketlerin akıcı ve rahat olduğu o hissi düşün.",
  },
  {
    word: "Conditioning",
    difficulty: "intermediate",
    meaning: "Kondisyon çalışması; genel fiziksel uygunluğu artırmaya yönelik antrenman.",
    example: "Conditioning is key for athletes.",
    hint: "Vücudunu genel olarak daha hazır hissettiğin süreci hayal et.",
  },
  {
    word: "Breathing",
    difficulty: "intermediate",
    meaning: "Nefes kontrolü; egzersiz sırasında nefesi bilinçli yönetme.",
    example: "Proper breathing improves endurance.",
    hint: "Nefes alıp verişini ritme soktuğun o sakin kontrolü düşün.",
  },
  {
    word: "Posture",
    difficulty: "intermediate",
    meaning: "Duruş; vücudun egzersiz veya günlük hayattaki hizalanma şekli.",
    example: "Good posture prevents back pain.",
    hint: "Dik ama rahat durduğun o dengeli duruşu hayal et.",
  },
  {
    word: "Warm-down",
    difficulty: "intermediate",
    meaning: "Soğuma; egzersiz sonrası vücudu yavaşça dinlenme hâline getirme süreci.",
    example: "A warm-down helps recovery.",
    hint: "Temponu düşürüp vücudunu sakinleştirdiğin o kapanışı düşün.",
  },

  {
    word: "Periodization",
    difficulty: "advanced",
    meaning: "Periyodizasyon; antrenman yüklerinin belirli dönemlere planlı şekilde dağıtılması yöntemi.",
    example: "Periodization helps athletes peak at the right time.",
    hint: "Antrenmanın yıl boyunca bilinçli dalgalar hâlinde planlandığını düşün.",
  },
  {
    word: "Hypertrophy",
    difficulty: "advanced",
    meaning: "Hipertrofi; kas liflerinin hacimsel olarak büyümesi süreci.",
    example: "Hypertrophy training focuses on muscle growth.",
    hint: "Kaslarının zamanla daha dolgun ve güçlü hâle geldiğini hayal et.",
  },
  {
    word: "Biomechanics",
    difficulty: "advanced",
    meaning: "Biyomekanik; insan hareketlerini fizik kurallarıyla inceleyen bilim dalı.",
    example: "Biomechanics improves movement efficiency.",
    hint: "Bir hareketin arkasındaki kuvvetleri ve açıları düşündüğünü hayal et.",
  },
  {
    word: "Anaerobic",
    difficulty: "advanced",
    meaning: "Anaerobik; oksijen kullanılmadan gerçekleşen yüksek yoğunluklu enerji üretimi.",
    example: "Sprints rely heavily on anaerobic energy.",
    hint: "Nefes nefese kaldığın ama kısa sürede patlayıcı güç ürettiğin anı düşün.",
  },
  {
    word: "Aerobic",
    difficulty: "advanced",
    meaning: "Aerobik; oksijen kullanılarak sürdürülebilir enerji üretimine dayalı aktivite.",
    example: "Aerobic exercise improves heart health.",
    hint: "Uzun süre devam edebildiğin, ritmik ve kontrollü eforu hayal et.",
  },
  {
    word: "Proprioception",
    difficulty: "advanced",
    meaning: "Propriosepsiyon; vücudun uzaydaki konumunu algılama yeteneği.",
    example: "Balance training improves proprioception.",
    hint: "Gözlerin kapalıyken bile vücudunun nerede olduğunu bildiğin hissi düşün.",
  },
  {
    word: "Eccentric",
    difficulty: "advanced",
    meaning: "Eksantrik; kasın uzayarak kuvvet ürettiği kasılma türü.",
    example: "Eccentric movements increase muscle control.",
    hint: "Ağırlığı yavaşça indirirken kaslarının gerildiğini hayal et.",
  },
  {
    word: "Isometric",
    difficulty: "advanced",
    meaning: "İzometrik; kas uzunluğu değişmeden yapılan kasılma türü.",
    example: "Planks are isometric exercises.",
    hint: "Hareketsiz kalıp kaslarını sürekli aktif tuttuğun o duruşu düşün.",
  },
  {
    word: "VO2 Max",
    difficulty: "advanced",
    meaning: "VO₂ max; vücudun kullanabildiği maksimum oksijen kapasitesi.",
    example: "Elite athletes usually have high VO2 max values.",
    hint: "Dayanıklılığının sayılarla ölçüldüğünü hayal et.",
  },
  {
    word: "Neuromuscular",
    difficulty: "advanced",
    meaning: "Nöromüsküler; sinir sistemi ile kasların birlikte çalışmasıyla ilgili.",
    example: "Neuromuscular training improves reaction time.",
    hint: "Beyninle kaslarının milisaniyeler içinde iletişim kurduğunu düşün.",
  },
];
