export const TRAVEL_WORDS = [
  {
    word: "Airport",
    difficulty: "beginner",
    meaning: "Uçakların iniş kalkış yaptığı ve yolcu işlemlerinin yürütüldüğü tesis.",
    example: "We arrived at the airport two hours early.",
    hint: "Uçağa binmeden önce gittiğin büyük terminali düşün.",
  },
  {
    word: "Airplane",
    difficulty: "beginner",
    meaning: "Havada uçabilen, yolcu veya yük taşıyan hava aracı.",
    example: "The airplane took off on time.",
    hint: "Gökyüzünde seyahat ettiğin aracı hatırla.",
  },
  {
    word: "Ticket",
    difficulty: "beginner",
    meaning: "Bir yolculuk veya etkinlik için giriş ve kullanım hakkı veren belge.",
    example: "I bought a ticket online.",
    hint: "Otobüse, trene ya da uçağa binmek için gereken belge.",
  },
  {
    word: "Passport",
    difficulty: "intermediate",
    meaning: "Yurt dışına çıkış ve kimlik doğrulama için kullanılan resmî seyahat belgesi.",
    example: "Don’t forget your passport.",
    hint: "Sınır kapısında gösterdiğin resmî defteri düşün.",
  },
  {
    word: "Visa",
    difficulty: "intermediate",
    meaning: "Bir ülkeye giriş için verilen resmî izin belgesi.",
    example: "She applied for a visa.",
    hint: "Bazı ülkelere girmek için pasaporta eklenen izin.",
  },
  {
    word: "Luggage",
    difficulty: "intermediate",
    meaning: "Seyahat sırasında taşınan eşya ve valizlerin genel adı.",
    example: "My luggage is very heavy.",
    hint: "Valiz, çanta ve eşyalarının tamamı.",
  },
  {
    word: "Suitcase",
    difficulty: "intermediate",
    meaning: "Seyahat eşyalarının taşındığı, genellikle sert kapaklı valiz.",
    example: "He packed his suitcase quickly.",
    hint: "Tekerlekli valizini hayal et.",
  },
  {
    word: "Backpack",
    difficulty: "beginner",
    meaning: "Sırtta taşınan, iki askılı çanta.",
    example: "I carried a backpack during the trip.",
    hint: "Sırtına taktığın çanta.",
  },
  {
    word: "Map",
    difficulty: "beginner",
    meaning: "Bir bölgenin yerleşimini ve yollarını gösteren çizim veya dijital araç.",
    example: "We used a map to find the hotel.",
    hint: "Kaybolmamak için baktığın çizim.",
  },
  {
    word: "Direction",
    difficulty: "beginner",
    meaning: "Bir yere nasıl gidileceğini belirten yol tarifi veya yön.",
    example: "Can you give me directions?",
    hint: "Sağa-sola dönme gibi yol tariflerini düşün.",
  },
  {
    word: "Left",
    difficulty: "beginner",
    meaning: "Yön bildiren, sağın karşıtı olan taraf.",
    example: "Turn left at the corner.",
    hint: "Kalbinin olduğu tarafı hatırla.",
  },
  {
    word: "Right",
    difficulty: "beginner",
    meaning: "Yön bildiren, solun karşıtı olan taraf.",
    example: "Turn right after the bridge.",
    hint: "Yazı yazdığın elin tarafını düşün.",
  },
  {
    word: "Straight",
    difficulty: "beginner",
    meaning: "Eğrilik olmadan, doğrudan ileri yönde.",
    example: "Go straight for two blocks.",
    hint: "Hiç sapmadan ileri gitmek.",
  },
  {
    word: "Stop",
    difficulty: "beginner",
    meaning: "Hareketi sona erdirmek veya bir yerde durmak.",
    example: "Please stop here.",
    hint: "Dur işaretini veya kırmızı ışığı düşün.",
  },
  {
    word: "Go",
    difficulty: "beginner",
    meaning: "Bir yere hareket etmek; gitmek.",
    example: "Let’s go to the station.",
    hint: "Bir yerden başka bir yere hareket etmek.",
  },
  {
    word: "Arrive",
    difficulty: "beginner",
    meaning: "Bir yere varmak; ulaşmak.",
    example: "We arrived late.",
    hint: "Hedefe ulaştığın an.",
  },
  {
    word: "Leave",
    difficulty: "beginner",
    meaning: "Bir yerden ayrılmak; çıkmak.",
    example: "We leave at 7 a.m.",
    hint: "Otelden çıkıp yola koyulmak gibi.",
  },
  {
    word: "Departure",
    difficulty: "intermediate",
    meaning: "Bir yolculuğun başladığı çıkış zamanı veya noktası.",
    example: "The departure time is 9:30.",
    hint: "Uçağın ya da otobüsün kalkış saati.",
  },
  {
    word: "Arrival",
    difficulty: "intermediate",
    meaning: "Bir yolculuğun bittiği varış zamanı veya noktası.",
    example: "Our arrival was delayed.",
    hint: "Ulaşacağın şehrin zamanı.",
  },
  {
    word: "Gate",
    difficulty: "intermediate",
    meaning: "Havalimanı veya istasyonda binişin yapıldığı kapı.",
    example: "Our gate changed suddenly.",
    hint: "Uçağa geçmeden önceki numaralı kapı.",
  },
  {
    word: "Terminal",
    difficulty: "intermediate",
    meaning: "Ulaşım merkezlerinde yolcu işlemlerinin yapıldığı ana bina.",
    example: "The terminal was crowded.",
    hint: "Havalimanındaki büyük salon.",
  },
  {
    word: "Boarding",
    difficulty: "intermediate",
    meaning: "Uçağa, trene veya otobüse binme işlemi.",
    example: "Boarding starts at 8:10.",
    hint: "Anonsla birlikte sıraya girip araca binmek.",
  },
  {
    word: "Seat",
    difficulty: "beginner",
    meaning: "Oturma yeri; koltuk.",
    example: "My seat is near the window.",
    hint: "Biletindeki koltuk numarasını düşün.",
  },
  {
    word: "Window",
    difficulty: "beginner",
    meaning: "Dışarıyı görmeye yarayan camlı açıklık.",
    example: "I want a window seat.",
    hint: "Uçakta dışarıyı izlediğin taraf.",
  },
  {
    word: "Aisle",
    difficulty: "intermediate",
    meaning: "Sıra arası geçiş yolu.",
    example: "He chose an aisle seat.",
    hint: "Koltuğundan kalkıp yürüdüğün koridor.",
  },
  {
    word: "Pilot",
    difficulty: "intermediate",
    meaning: "Uçağı kullanan görevli.",
    example: "The pilot welcomed everyone.",
    hint: "Uçağı yöneten kişi.",
  },
  {
    word: "Crew",
    difficulty: "intermediate",
    meaning: "Bir taşıtın işletilmesi için görev yapan ekip.",
    example: "The crew was very helpful.",
    hint: "Uçakta hizmet eden ekip.",
  },
  {
    word: "Baggage",
    difficulty: "intermediate",
    meaning: "Yolcunun yanında veya kargo bölümünde taşıdığı eşyalar.",
    example: "Baggage claim is downstairs.",
    hint: "Valizini teslim aldığın alanı düşün.",
  },
  {
    word: "Carry-on",
    difficulty: "intermediate",
    meaning: "Kabin içine alınabilen el bagajı.",
    example: "My carry-on fits in the bin.",
    hint: "Üst dolaba koyduğun küçük çanta.",
  },
  {
    word: "Check-in",
    difficulty: "intermediate",
    meaning: "Yolculuk öncesi kayıt ve bilet işlemlerinin yapılması.",
    example: "We checked in at the counter.",
    hint: "Bavul teslim edip biniş kartı aldığın işlem.",
  },
  {
    word: "Counter",
    difficulty: "intermediate",
    meaning: "Hizmet verilen banko; gişe.",
    example: "Go to the check-in counter.",
    hint: "Görevlinin arkasında durduğu banko.",
  },
  {
    word: "Security",
    difficulty: "intermediate",
    meaning: "Güvenlik kontrolü ve denetim işlemleri.",
    example: "Security was quick today.",
    hint: "Çanta taramasından geçtiğin kontrol noktası.",
  },
  {
    word: "Queue",
    difficulty: "intermediate",
    meaning: "Sıra; bekleme kuyruğu.",
    example: "There was a long queue.",
    hint: "Arka arkaya beklediğin çizgi.",
  },
  {
    word: "Delay",
    difficulty: "intermediate",
    meaning: "Planlanan zamandan sonra gerçekleşme; gecikme.",
    example: "The flight had a delay.",
    hint: "Kalkış saatinin ileri alınması.",
  },
  {
    word: "Cancel",
    difficulty: "intermediate",
    meaning: "Planı iptal etmek; geçersiz kılmak.",
    example: "They canceled the train.",
    hint: "Seferin artık yapılmaması.",
  },
  {
    word: "Schedule",
    difficulty: "intermediate",
    meaning: "Zaman planı; sefer saatleri listesi.",
    example: "Check the bus schedule.",
    hint: "Saatlere bakıp plan yaptığın liste.",
  },
  {
    word: "Platform",
    difficulty: "intermediate",
    meaning: "Tren veya metroya binilen peron.",
    example: "The train is on platform 3.",
    hint: "Treni beklediğin numaralı alan.",
  },
  {
    word: "Station",
    difficulty: "beginner",
    meaning: "Tren, metro veya otobüs için durak ve hizmet alanı.",
    example: "Meet me at the station.",
    hint: "Ulaşım araçlarının toplandığı yer.",
  },
  {
    word: "Stopover",
    difficulty: "intermediate",
    meaning: "Aktarma sırasında kısa süreli bekleme ve ara duraklama.",
    example: "We have a stopover in Doha.",
    hint: "Uçuş arası başka şehirde kısa bekleme.",
  },
  {
    word: "Transfer",
    difficulty: "intermediate",
    meaning: "Bir araçtan diğerine geçiş; aktarma.",
    example: "We need a transfer at the next station.",
    hint: "Metro değiştirir gibi araç değiştirmek.",
  },
  {
    word: "Connection",
    difficulty: "intermediate",
    meaning: "Aktarmalı ulaşım bağlantısı.",
    example: "I missed my connection.",
    hint: "Bir sonraki araca yetişme planı.",
  },
  {
    word: "Bus",
    difficulty: "beginner",
    meaning: "Toplu taşıma amacıyla kullanılan motorlu taşıt.",
    example: "The bus is late today.",
    hint: "Şehir içi ulaşımda sık kullandığın araç.",
  },
  {
    word: "Coach",
    difficulty: "intermediate",
    meaning: "Uzun mesafe yolculuk yapan otobüs.",
    example: "We took a coach to Ankara.",
    hint: "Şehirler arası büyük otobüs.",
  },
  {
    word: "Train",
    difficulty: "beginner",
    meaning: "Raylar üzerinde hareket eden toplu taşıma aracı.",
    example: "The train arrived on time.",
    hint: "Rayların üzerinde giden uzun araç.",
  },
  {
    word: "Metro",
    difficulty: "beginner",
    meaning: "Şehir içi yer altı veya yer üstü hızlı tren sistemi.",
    example: "I take the metro to work.",
    hint: "İstasyonlar arasında hızlı giden tren.",
  },
  {
    word: "Tram",
    difficulty: "intermediate",
    meaning: "Şehir içinde raylı, kısa mesafeli toplu taşıma aracı.",
    example: "The tram stops near the museum.",
    hint: "Cadde üzerinde giden kısa raylı araç.",
  },
  {
    word: "Taxi",
    difficulty: "beginner",
    meaning: "Ücret karşılığında yolcu taşıyan otomobil.",
    example: "We took a taxi to the hotel.",
    hint: "Kapıdan alıp götüren sarı araç.",
  },
  {
    word: "Ride",
    difficulty: "beginner",
    meaning: "Bir araçla yolculuk; biniş.",
    example: "Can I get a ride to the airport?",
    hint: "Biriyle araca binip gitmek.",
  },
  {
    word: "Driver",
    difficulty: "beginner",
    meaning: "Aracı kullanan kişi; şoför.",
    example: "The driver was polite.",
    hint: "Direksiyondaki kişi.",
  },
  {
    word: "Car",
    difficulty: "beginner",
    meaning: "Genellikle özel kullanım için üretilmiş motorlu taşıt.",
    example: "We rented a car for the weekend.",
    hint: "Kendi kullandığın otomobil.",
  },
  {
    word: "Rental",
    difficulty: "intermediate",
    meaning: "Belirli süre için ücretle kiralama işlemi.",
    example: "The rental was affordable.",
    hint: "Aracı kısa süreliğine ödünç almak.",
  },
  {
    word: "Rent",
    difficulty: "beginner",
    meaning: "Ücret karşılığında belirli süre kullanmak üzere kiralamak.",
    example: "We rented a small car.",
    hint: "Satın almadan, geçici kullanmak.",
  },
  {
    word: "Reservation",
    difficulty: "intermediate",
    meaning: "Bir hizmeti önceden ayırtma işlemi.",
    example: "I made a reservation online.",
    hint: "Yerini önceden garantiye almak.",
  },
  {
    word: "Book",
    difficulty: "beginner",
    meaning: "Önceden ayırtmak; rezervasyon yapmak.",
    example: "We booked the tickets yesterday.",
    hint: "Son dakikaya kalmadan yer ayırmak.",
  },
  {
    word: "Hotel",
    difficulty: "beginner",
    meaning: "Konaklama hizmeti sunan işletme.",
    example: "The hotel is near the beach.",
    hint: "Gece kalacağın yer.",
  },
  {
    word: "Hostel",
    difficulty: "intermediate",
    meaning: "Genellikle daha ekonomik, ortak alanlı konaklama yeri.",
    example: "They stayed in a hostel.",
    hint: "Uygun bütçeli konaklama seçeneği.",
  },
  {
    word: "Room",
    difficulty: "beginner",
    meaning: "Konaklamada kalınan oda.",
    example: "Our room has two beds.",
    hint: "Anahtarını aldığın alan.",
  },
  {
    word: "Key",
    difficulty: "beginner",
    meaning: "Kapıları açmaya yarayan araç; anahtar.",
    example: "I can’t find my room key.",
    hint: "Odaya girmek için gereken şey.",
  },
  {
    word: "Check out",
    difficulty: "intermediate",
    meaning: "Konaklamayı bitirip otelden ayrılma işlemi.",
    example: "We check out at noon.",
    hint: "Odayı teslim edip çıkmak.",
  },
  {
    word: "Check in",
    difficulty: "intermediate",
    meaning: "Konaklamaya başlamak için kayıt işlemi.",
    example: "We check in after 2 p.m.",
    hint: "Odaya giriş için resepsiyona uğramak.",
  },
  {
    word: "Reception",
    difficulty: "intermediate",
    meaning: "Misafir karşılama ve işlem yapılan otel bölümü.",
    example: "Ask at the reception.",
    hint: "Otele girince danıştığın masa.",
  },
  {
    word: "Guide",
    difficulty: "intermediate",
    meaning: "Bir yeri gezdiren ve bilgi veren kişi veya kaynak.",
    example: "The guide explained the history.",
    hint: "Şehri anlatan kişi.",
  },
  {
    word: "Tour",
    difficulty: "intermediate",
    meaning: "Gezilecek yerleri kapsayan planlı gezi.",
    example: "We joined a city tour.",
    hint: "Rehberle yapılan gezi programı.",
  },
  {
    word: "Tourist",
    difficulty: "intermediate",
    meaning: "Gezmek amacıyla bir yere giden kişi.",
    example: "Many tourists visit in summer.",
    hint: "Sadece gezmek için gelen kişi.",
  },
  {
    word: "Trip",
    difficulty: "beginner",
    meaning: "Kısa süreli yolculuk; gezi.",
    example: "The trip was relaxing.",
    hint: "Hafta sonu kaçamağı gibi.",
  },
  {
    word: "Journey",
    difficulty: "intermediate",
    meaning: "Genellikle daha uzun ve süreç odaklı yolculuk.",
    example: "The journey took five hours.",
    hint: "Yolda geçen uzun süreyi düşün.",
  },
  {
    word: "Travel",
    difficulty: "beginner",
    meaning: "Bir yerden başka bir yere gitmek; seyahat etmek.",
    example: "I love to travel by train.",
    hint: "Yeni yerler görme fikri.",
  },
  {
    word: "Visit",
    difficulty: "beginner",
    meaning: "Bir yeri görmek amacıyla gitmek; ziyaret etmek.",
    example: "We visited the old castle.",
    hint: "Gezip görmek için gitmek.",
  },
  {
    word: "Explore",
    difficulty: "intermediate",
    meaning: "Bir yeri keşfetmek; ayrıntılı incelemek.",
    example: "We explored the local streets.",
    hint: "Haritasız dolaşıp yeni şeyler bulmak.",
  },
  {
    word: "Plan",
    difficulty: "beginner",
    meaning: "Önceden düzenlenmiş program veya tasarı.",
    example: "Let’s plan our route.",
    hint: "Ne zaman, nereye gideceğini düşünmek.",
  },
  {
    word: "Route",
    difficulty: "intermediate",
    meaning: "İzlenecek yol; güzergâh.",
    example: "This route is faster.",
    hint: "Haritada çizdiğin yol.",
  },
  {
    word: "Distance",
    difficulty: "intermediate",
    meaning: "İki nokta arasındaki mesafe.",
    example: "The distance is only two kilometers.",
    hint: "Ne kadar yol var sorusunun cevabı.",
  },
  {
    word: "Near",
    difficulty: "beginner",
    meaning: "Yakın mesafede bulunan.",
    example: "The station is near the hotel.",
    hint: "Yürüme mesafesinde olan.",
  },
  {
    word: "Far",
    difficulty: "beginner",
    meaning: "Uzak mesafede bulunan.",
    example: "The airport is far from here.",
    hint: "Gitmek için daha çok zaman gereken.",
  },
  {
    word: "Corner",
    difficulty: "beginner",
    meaning: "İki yolun kesiştiği köşe nokta.",
    example: "Turn at the next corner.",
    hint: "Sokağın döndüğü yer.",
  },
  {
    word: "Bridge",
    difficulty: "beginner",
    meaning: "İki tarafı birbirine bağlayan geçit; köprü.",
    example: "We crossed the bridge.",
    hint: "Suyun üstünden geçen yapı.",
  },
  {
    word: "Crosswalk",
    difficulty: "intermediate",
    meaning: "Yayaların karşıya geçmesi için ayrılmış yol bölümü.",
    example: "Use the crosswalk, please.",
    hint: "Zebra çizgilerini hatırla.",
  },
  {
    word: "Traffic",
    difficulty: "intermediate",
    meaning: "Yol üzerindeki araç ve insan hareketliliği; trafik.",
    example: "There is heavy traffic today.",
    hint: "Yolun kalabalık olduğu durum.",
  },
  {
    word: "Traffic light",
    difficulty: "intermediate",
    meaning: "Araç ve yaya akışını düzenleyen ışıklı sistem.",
    example: "Stop at the traffic light.",
    hint: "Kırmızı-sarı-yeşil ışık.",
  },
  {
    word: "Sign",
    difficulty: "beginner",
    meaning: "Yol veya bilgi işareti; tabela.",
    example: "Follow the signs to baggage claim.",
    hint: "Oklarla yön gösteren tabelalar.",
  },
  {
    word: "Speed",
    difficulty: "beginner",
    meaning: "Hız; hareketin sürati.",
    example: "The bus increased speed.",
    hint: "Ne kadar hızlı gittiğini düşün.",
  },
  {
    word: "Slow",
    difficulty: "beginner",
    meaning: "Yavaş; düşük hızda.",
    example: "The train was slow today.",
    hint: "Acele etmeden ilerlemek.",
  },
  {
    word: "Fast",
    difficulty: "beginner",
    meaning: "Hızlı; yüksek hızda.",
    example: "This is the fastest route.",
    hint: "Daha çabuk ulaştıran yol.",
  },
  {
    word: "Ferry",
    difficulty: "intermediate",
    meaning: "Araç veya yolcu taşıyan deniz ulaşım aracı; vapur.",
    example: "We took a ferry across the bay.",
    hint: "Denizde giden toplu taşıma.",
  },
  {
    word: "Boat",
    difficulty: "beginner",
    meaning: "Su üzerinde kullanılan küçük veya orta boy taşıt.",
    example: "They rented a small boat.",
    hint: "Su üstünde giden araç.",
  },
  {
    word: "Ship",
    difficulty: "intermediate",
    meaning: "Denizde uzun yol yapan büyük gemi.",
    example: "The ship left the port.",
    hint: "Büyük deniz aracı.",
  },
  {
    word: "Port",
    difficulty: "intermediate",
    meaning: "Gemi ve feribotların yanaştığı liman.",
    example: "We waited at the port.",
    hint: "Deniz ulaşımının istasyonu gibi.",
  },
  {
    word: "Subway",
    difficulty: "intermediate",
    meaning: "Metro; şehir içi yer altı ulaşım sistemi.",
    example: "Take the subway to downtown.",
    hint: "Yer altından giden tren.",
  },
  {
    word: "Bicycle",
    difficulty: "intermediate",
    meaning: "Pedal gücüyle hareket eden iki tekerlekli araç.",
    example: "She traveled by bicycle.",
    hint: "Pedallayarak gittiğin araç.",
  },
  {
    word: "Helmet",
    difficulty: "intermediate",
    meaning: "Baş koruması sağlayan güvenlik ekipmanı; kask.",
    example: "Wear a helmet when you ride.",
    hint: "Bisiklet sürerken başını koruyan şey.",
  },
  {
    word: "Walk",
    difficulty: "beginner",
    meaning: "Yürümek; yaya olarak gitmek.",
    example: "We walked to the museum.",
    hint: "Kısa mesafede en basit ulaşım.",
  },
  {
    word: "Foot",
    difficulty: "beginner",
    meaning: "Yürüme ile ilgili; ayak.",
    example: "It’s a five-minute walk on foot.",
    hint: "Arabaya binmeden yürümek.",
  },
  {
    word: "Hike",
    difficulty: "intermediate",
    meaning: "Doğada yürüyüş yapmak; trekking.",
    example: "We went for a hike in the hills.",
    hint: "Doğa yürüyüşünü düşün.",
  },
  {
    word: "Beach",
    difficulty: "beginner",
    meaning: "Deniz kenarında kumlu veya çakıllı alan; plaj.",
    example: "The beach is crowded in July.",
    hint: "Deniz tatilindeki kıyı.",
  },
  {
    word: "Museum",
    difficulty: "beginner",
    meaning: "Tarihî, sanatsal veya bilimsel eserlerin sergilendiği yer.",
    example: "We visited a museum today.",
    hint: "Eserleri gezdiğin büyük bina.",
  },
  {
    word: "City",
    difficulty: "beginner",
    meaning: "Nüfusun yoğun olduğu yerleşim birimi; şehir.",
    example: "This city is very lively.",
    hint: "Gezdiğin büyük yerleşim.",
  },
  {
    word: "Downtown",
    difficulty: "intermediate",
    meaning: "Şehrin merkez bölgesi; şehir merkezi.",
    example: "Let’s meet downtown.",
    hint: "Mağazaların ve kalabalığın olduğu merkez.",
  },
  {
    word: "Local",
    difficulty: "intermediate",
    meaning: "Bir bölgeye ait; yerel.",
    example: "We tried local food.",
    hint: "Oranın insanına ve kültürüne ait.",
  },
  {
    word: "Street",
    difficulty: "beginner",
    meaning: "Cadde veya sokak; yol.",
    example: "This street is quiet at night.",
    hint: "Evlerin ve dükkânların olduğu yol.",
  },
  {
    word: "Road",
    difficulty: "beginner",
    meaning: "Araçların kullandığı yol.",
    example: "The road is closed.",
    hint: "Araba ile gidilen ana yol.",
  },
] as const;
