export const WORDS = [
  {
    word: "Work",
    meaning: "Çalışmak; bir işi yapmak veya emek harcamak.",
    example: "I work in an office.",
    hint: "Bir iş yaptığını veya emek verdiğini düşün.",
  },
  {
    word: "Office",
    meaning: "Ofis; işlerin yürütüldüğü çalışma ortamı.",
    example: "The office opens at 9 a.m.",
    hint: "Masa, bilgisayar ve sandalyelerin olduğu yer.",
  },
  {
    word: "Job",
    meaning: "İş; düzenli olarak yapılan meslek veya görev.",
    example: "She has a new job.",
    hint: "Para kazanmak için yaptığın şey.",
  },
  {
    word: "Boss",
    meaning: "Patron; iş yerindeki yönetici kişi.",
    example: "My boss is very kind.",
    hint: "Sana görev veren kişi.",
  },
  {
    word: "Manager",
    meaning: "Yönetici; bir ekibi veya işi yöneten kişi.",
    example: "The manager called a meeting.",
    hint: "İnsanları ve işleri organize eden kişi.",
  },
  {
    word: "Employee",
    meaning: "Çalışan; bir iş yerinde görev yapan kişi.",
    example: "The company has many employees.",
    hint: "Bir yerde çalışan insan.",
  },
  {
    word: "Team",
    meaning: "Ekip; birlikte çalışan grup.",
    example: "Our team is very productive.",
    hint: "Aynı hedef için çalışan insanlar.",
  },
  {
    word: "Task",
    meaning: "Görev; yapılması gereken iş.",
    example: "I finished my task.",
    hint: "Yapman gereken küçük iş.",
  },
  {
    word: "Meeting",
    meaning: "Toplantı; iş konularının konuşulduğu görüşme.",
    example: "We have a meeting at 10.",
    hint: "Herkesin bir araya gelip konuştuğu zaman.",
  },
  {
    word: "Email",
    meaning: "E-posta; dijital yazılı mesaj.",
    example: "I sent an email to my manager.",
    hint: "Bilgisayardan gönderilen mektup gibi düşün.",
  },
  {
    word: "Computer",
    meaning: "Bilgisayar; iş ve iletişim için kullanılan cihaz.",
    example: "I use my computer all day.",
    hint: "Ekranı ve klavyesi olan cihaz.",
  },
  {
    word: "Desk",
    meaning: "Masa; çalışmak için kullanılan masa.",
    example: "My desk is near the window.",
    hint: "Bilgisayarının durduğu masa.",
  },
  {
    word: "Chair",
    meaning: "Sandalye; oturmak için kullanılan eşya.",
    example: "This chair is comfortable.",
    hint: "Masada oturduğun şey.",
  },
  {
    word: "Schedule",
    meaning: "Program; yapılacak işlerin zamanı.",
    example: "My schedule is very busy.",
    hint: "Günlük planın.",
  },
  {
    word: "Deadline",
    meaning: "Son tarih; bir işin bitmesi gereken zaman.",
    example: "The deadline is tomorrow.",
    hint: "İşi bitirmen gereken son gün.",
  },
  {
    word: "Project",
    meaning: "Proje; planlı ve uzun süreli çalışma.",
    example: "We started a new project.",
    hint: "Birden fazla adımı olan iş.",
  },
  {
    word: "Break",
    meaning: "Mola; kısa dinlenme zamanı.",
    example: "I take a break at noon.",
    hint: "Çalışmayı bırakıp dinlendiğin an.",
  },
  {
    word: "Lunch",
    meaning: "Öğle yemeği; gün ortasında yenilen yemek.",
    example: "We eat lunch together.",
    hint: "Öğlen yediğin yemek.",
  },
  {
    word: "Time",
    meaning: "Zaman; saat ve süre kavramı.",
    example: "Time is very important at work.",
    hint: "Saatine baktığında gördüğün şey.",
  },
  {
    word: "Clock",
    meaning: "Saat; zamanı gösteren araç.",
    example: "The clock shows 9 a.m.",
    hint: "Duvara asılı zamanı gösteren şey.",
  },
  {
    word: "Start",
    meaning: "Başlamak; bir işi yapmaya başlamak.",
    example: "We start work at 9.",
    hint: "Bir işin ilk anı.",
  },
  {
    word: "Finish",
    meaning: "Bitirmek; bir işi tamamlamak.",
    example: "I finish work at 6.",
    hint: "İşin sonu.",
  },
  {
    word: "Call",
    meaning: "Arama; telefonla konuşma.",
    example: "I have a call with my team.",
    hint: "Telefonla konuşmak.",
  },
  {
    word: "Client",
    meaning: "Müşteri; hizmet alan kişi.",
    example: "The client is waiting.",
    hint: "İş yaptığın kişi.",
  },
  {
    word: "Company",
    meaning: "Şirket; ticari kuruluş.",
    example: "The company is growing fast.",
    hint: "Birçok kişinin çalıştığı iş yeri.",
  },
  {
    word: "Salary",
    meaning: "Maaş; düzenli alınan ücret.",
    example: "My salary is paid monthly.",
    hint: "Ay sonunda aldığın para.",
  },
  {
    word: "Money",
    meaning: "Para; alışverişte kullanılan değer.",
    example: "I earn money from my job.",
    hint: "Kazandığın ve harcadığın şey.",
  },
  {
    word: "Report",
    meaning: "Rapor; yazılı iş bilgisi.",
    example: "I wrote a report.",
    hint: "Yaptığın işi yazıyla anlatmak.",
  },
  {
    word: "Plan",
    meaning: "Plan; önceden yapılan düzenleme.",
    example: "We made a plan.",
    hint: "Önceden düşündüğün yol.",
  },
  {
    word: "Goal",
    meaning: "Hedef; ulaşılmak istenen sonuç.",
    example: "Our goal is success.",
    hint: "Ulaşmak istediğin nokta.",
  },
  {
    word: "Idea",
    meaning: "Fikir; zihinde oluşan düşünce.",
    example: "She has a great idea.",
    hint: "Aklına gelen düşünce.",
  },
  {
    word: "Problem",
    meaning: "Sorun; çözülmesi gereken durum.",
    example: "We solved the problem.",
    hint: "Can sıkan ve çözüm isteyen şey.",
  },
  {
    word: "Solution",
    meaning: "Çözüm; bir sorunun cevabı.",
    example: "This is a good solution.",
    hint: "Sorunu ortadan kaldıran şey.",
  },
  {
    word: "Help",
    meaning: "Yardım; destek olma durumu.",
    example: "Can you help me?",
    hint: "Birine destek olmak.",
  },
  {
    word: "Busy",
    meaning: "Meşgul; çok işi olan.",
    example: "I am busy today.",
    hint: "Yapacak çok işin olduğu zaman.",
  },
  {
    word: "Free",
    meaning: "Boş; işi olmayan.",
    example: "I am free now.",
    hint: "Yapacak işin olmadığı an.",
  },
  {
    word: "Early",
    meaning: "Erken; zamanından önce.",
    example: "I arrive early.",
    hint: "Saat daha küçükken.",
  },
  {
    word: "Late",
    meaning: "Geç; olması gerekenden sonra.",
    example: "I was late today.",
    hint: "Saatin geçtiği an.",
  },
  {
    word: "Weekday",
    meaning: "Hafta içi; pazartesiden cumaya kadar olan günler.",
    example: "I work on weekdays.",
    hint: "Hafta sonu olmayan günler.",
  },
  {
    word: "Weekend",
    meaning: "Hafta sonu; cumartesi ve pazar.",
    example: "I rest on the weekend.",
    hint: "Çalışmadığın günler.",
  },
  {
    word: "Office life",
    meaning: "Ofis hayatı; ofiste çalışma düzeni.",
    example: "Office life can be busy.",
    hint: "Her gün ofiste geçen zaman.",
  },
];
