export const WORK_WORDS = [
  {
    word: "Work",
    difficulty: "beginner",
    meaning: "Çalışmak; bir işi yapmak veya emek harcamak.",
    example: "I work in an office.",
    hint: "Bir iş yaptığını veya emek verdiğini düşün.",
  },
  {
    word: "Office",
    difficulty: "beginner",
    meaning: "Ofis; işlerin yürütüldüğü çalışma ortamı.",
    example: "The office opens at 9 a.m.",
    hint: "Masa, bilgisayar ve sandalyelerin olduğu yer.",
  },
  {
    word: "Job",
    difficulty: "beginner",
    meaning: "İş; düzenli olarak yapılan meslek veya görev.",
    example: "She has a new job.",
    hint: "Para kazanmak için yaptığın şey.",
  },
  {
    word: "Boss",
    difficulty: "beginner",
    meaning: "Patron; iş yerindeki yönetici kişi.",
    example: "My boss is very kind.",
    hint: "Sana görev veren kişi.",
  },
  {
    word: "Manager",
    difficulty: "intermediate",
    meaning: "Yönetici; bir ekibi veya işi yöneten kişi.",
    example: "The manager called a meeting.",
    hint: "İnsanları ve işleri organize eden kişi.",
  },
  {
    word: "Employee",
    difficulty: "intermediate",
    meaning: "Çalışan; bir iş yerinde görev yapan kişi.",
    example: "The company has many employees.",
    hint: "Bir yerde çalışan insan.",
  },
  {
    word: "Team",
    difficulty: "beginner",
    meaning: "Ekip; birlikte çalışan grup.",
    example: "Our team is very productive.",
    hint: "Aynı hedef için çalışan insanlar.",
  },
  {
    word: "Task",
    difficulty: "intermediate",
    meaning: "Görev; yapılması gereken iş.",
    example: "I finished my task.",
    hint: "Yapman gereken küçük iş.",
  },
  {
    word: "Meeting",
    difficulty: "intermediate",
    meaning: "Toplantı; iş konularının konuşulduğu görüşme.",
    example: "We have a meeting at 10.",
    hint: "Herkesin bir araya gelip konuştuğu zaman.",
  },
  {
    word: "Email",
    difficulty: "beginner",
    meaning: "E-posta; dijital yazılı mesaj.",
    example: "I sent an email to my manager.",
    hint: "Bilgisayardan gönderilen mektup gibi düşün.",
  },
  {
    word: "Computer",
    difficulty: "beginner",
    meaning: "Bilgisayar; iş ve iletişim için kullanılan cihaz.",
    example: "I use my computer all day.",
    hint: "Ekranı ve klavyesi olan cihaz.",
  },
  {
    word: "Desk",
    difficulty: "beginner",
    meaning: "Masa; çalışmak için kullanılan masa.",
    example: "My desk is near the window.",
    hint: "Bilgisayarının durduğu masa.",
  },
  {
    word: "Chair",
    difficulty: "beginner",
    meaning: "Sandalye; oturmak için kullanılan eşya.",
    example: "This chair is comfortable.",
    hint: "Masada oturduğun şey.",
  },
  {
    word: "Schedule",
    difficulty: "intermediate",
    meaning: "Program; yapılacak işlerin zamanı.",
    example: "My schedule is very busy.",
    hint: "Günlük planın.",
  },
  {
    word: "Deadline",
    difficulty: "intermediate",
    meaning: "Son tarih; bir işin bitmesi gereken zaman.",
    example: "The deadline is tomorrow.",
    hint: "İşi bitirmen gereken son gün.",
  },
  {
    word: "Project",
    difficulty: "intermediate",
    meaning: "Proje; planlı ve uzun süreli çalışma.",
    example: "We started a new project.",
    hint: "Birden fazla adımı olan iş.",
  },
  {
    word: "Break",
    difficulty: "beginner",
    meaning: "Mola; kısa dinlenme zamanı.",
    example: "I take a break at noon.",
    hint: "Çalışmayı bırakıp dinlendiğin an.",
  },
  {
    word: "Lunch",
    difficulty: "beginner",
    meaning: "Öğle yemeği; gün ortasında yenilen yemek.",
    example: "We eat lunch together.",
    hint: "Öğlen yediğin yemek.",
  },
  {
    word: "Time",
    difficulty: "beginner",
    meaning: "Zaman; saat ve süre kavramı.",
    example: "Time is very important at work.",
    hint: "Saatine baktığında gördüğün şey.",
  },
  {
    word: "Clock",
    difficulty: "beginner",
    meaning: "Saat; zamanı gösteren araç.",
    example: "The clock shows 9 a.m.",
    hint: "Duvara asılı zamanı gösteren şey.",
  },
  {
    word: "Start",
    difficulty: "beginner",
    meaning: "Başlamak; bir işi yapmaya başlamak.",
    example: "We start work at 9.",
    hint: "Bir işin ilk anı.",
  },
  {
    word: "Finish",
    difficulty: "beginner",
    meaning: "Bitirmek; bir işi tamamlamak.",
    example: "I finish work at 6.",
    hint: "İşin sonu.",
  },
  {
    word: "Call",
    difficulty: "beginner",
    meaning: "Arama; telefonla konuşma.",
    example: "I have a call with my team.",
    hint: "Telefonla konuşmak.",
  },
  {
    word: "Client",
    difficulty: "intermediate",
    meaning: "Müşteri; hizmet alan kişi.",
    example: "The client is waiting.",
    hint: "İş yaptığın kişi.",
  },
  {
    word: "Company",
    difficulty: "intermediate",
    meaning: "Şirket; ticari kuruluş.",
    example: "The company is growing fast.",
    hint: "Birçok kişinin çalıştığı iş yeri.",
  },
  {
    word: "Salary",
    difficulty: "intermediate",
    meaning: "Maaş; düzenli alınan ücret.",
    example: "My salary is paid monthly.",
    hint: "Ay sonunda aldığın para.",
  },
  {
    word: "Money",
    difficulty: "beginner",
    meaning: "Para; alışverişte kullanılan değer.",
    example: "I earn money from my job.",
    hint: "Kazandığın ve harcadığın şey.",
  },
  {
    word: "Report",
    difficulty: "intermediate",
    meaning: "Rapor; yazılı iş bilgisi.",
    example: "I wrote a report.",
    hint: "Yaptığın işi yazıyla anlatmak.",
  },
  {
    word: "Plan",
    difficulty: "beginner",
    meaning: "Plan; önceden yapılan düzenleme.",
    example: "We made a plan.",
    hint: "Önceden düşündüğün yol.",
  },
  {
    word: "Goal",
    difficulty: "intermediate",
    meaning: "Hedef; ulaşılmak istenen sonuç.",
    example: "Our goal is success.",
    hint: "Ulaşmak istediğin nokta.",
  },
  {
    word: "Idea",
    difficulty: "beginner",
    meaning: "Fikir; zihinde oluşan düşünce.",
    example: "She has a great idea.",
    hint: "Aklına gelen düşünce.",
  },
  {
    word: "Problem",
    difficulty: "beginner",
    meaning: "Sorun; çözülmesi gereken durum.",
    example: "We solved the problem.",
    hint: "Can sıkan ve çözüm isteyen şey.",
  },
  {
    word: "Solution",
    difficulty: "intermediate",
    meaning: "Çözüm; bir sorunun cevabı.",
    example: "This is a good solution.",
    hint: "Sorunu ortadan kaldıran şey.",
  },
  {
    word: "Help",
    difficulty: "beginner",
    meaning: "Yardım; destek olma durumu.",
    example: "Can you help me?",
    hint: "Birine destek olmak.",
  },
  {
    word: "Busy",
    difficulty: "beginner",
    meaning: "Meşgul; çok işi olan.",
    example: "I am busy today.",
    hint: "Yapacak çok işin olduğu zaman.",
  },
  {
    word: "Free",
    difficulty: "beginner",
    meaning: "Boş; işi olmayan.",
    example: "I am free now.",
    hint: "Yapacak işin olmadığı an.",
  },
  {
    word: "Early",
    difficulty: "beginner",
    meaning: "Erken; zamanından önce.",
    example: "I arrive early.",
    hint: "Saat daha küçükken.",
  },
  {
    word: "Late",
    difficulty: "beginner",
    meaning: "Geç; olması gerekenden sonra.",
    example: "I was late today.",
    hint: "Saatin geçtiği an.",
  },
  {
    word: "Weekday",
    difficulty: "intermediate",
    meaning: "Hafta içi; pazartesiden cumaya kadar olan günler.",
    example: "I work on weekdays.",
    hint: "Hafta sonu olmayan günler.",
  },
  {
    word: "Weekend",
    difficulty: "beginner",
    meaning: "Hafta sonu; cumartesi ve pazar.",
    example: "I rest on the weekend.",
    hint: "Çalışmadığın günler.",
  },
  {
    word: "Office life",
    difficulty: "intermediate",
    meaning: "Ofis hayatı; ofiste çalışma düzeni.",
    example: "Office life can be busy.",
    hint: "Her gün ofiste geçen zaman.",
  },
  {
    word: "Stakeholder",
    difficulty: "advanced",
    meaning:
      "Paydaş; bir projenin, kararın veya organizasyonun sonucundan doğrudan veya dolaylı olarak etkilenen kişi ya da grup.",
    example: "All stakeholders must approve the final decision.",
    hint: "Masada oturmasa bile karardan etkilenen herkesi düşün.",
  },
  {
    word: "Deliverable",
    difficulty: "advanced",
    meaning:
      "Teslim edilebilir çıktı; bir proje kapsamında belirlenen ve teslim edilmesi gereken somut sonuç.",
    example: "The final report is the main deliverable of this project.",
    hint: "Toplantıdan sonra senden beklenen net çıktıyı hayal et.",
  },
  {
    word: "Scalability",
    difficulty: "advanced",
    meaning:
      "Ölçeklenebilirlik; bir sistemin veya sürecin artan iş yüküne uyum sağlayabilme kapasitesi.",
    example: "Scalability is critical for growing companies.",
    hint: "Küçük başlayan ama büyüdükçe bozulmayan bir sistem düşün.",
  },
  {
    word: "Alignment",
    difficulty: "advanced",
    meaning:
      "Uyum; hedefler, stratejiler veya ekipler arasında tutarlılık sağlanması durumu.",
    example: "We need better alignment between teams.",
    hint: "Herkesin aynı yöne baktığı bir toplantıyı hayal et.",
  },
  {
    word: "Bandwidth",
    difficulty: "advanced",
    meaning:
      "Kapasite; bir kişinin veya ekibin belirli bir zaman diliminde üstlenebileceği iş miktarı.",
    example: "I don’t have the bandwidth to take on more tasks.",
    hint: "Zihinsel enerjinin dolu veya boş olmasını düşün.",
  },
  {
    word: "Escalation",
    difficulty: "advanced",
    meaning:
      "Yetki yükseltme; çözülemeyen bir konunun daha üst bir yönetim seviyesine taşınması.",
    example: "The issue was escalated to senior management.",
    hint: "Sorunun yukarı kata taşındığını hayal et.",
  },
  {
    word: "Roadmap",
    difficulty: "advanced",
    meaning:
      "Yol haritası; bir projenin veya ürünün gelecekteki adımlarını gösteren plan.",
    example: "The product roadmap covers the next six months.",
    hint: "Önünde uzanan bir proje haritasını düşün.",
  },
  {
    word: "Dependency",
    difficulty: "advanced",
    meaning:
      "Bağımlılık; bir görevin başka bir görevin tamamlanmasına bağlı olması durumu.",
    example: "This task has multiple dependencies.",
    hint: "Bir işin başlaması için diğerinin bitmesini beklediğini düşün.",
  },
  {
    word: "Feasibility",
    difficulty: "advanced",
    meaning:
      "Yapılabilirlik; bir fikrin teknik, mali veya operasyonel olarak uygulanabilir olma durumu.",
    example: "We need to assess the feasibility of the proposal.",
    hint: "Bu gerçekten yapılabilir mi diye sorduğun anı düşün.",
  },
  {
    word: "Accountability",
    difficulty: "advanced",
    meaning: "Sorumluluk; bir görev veya sonucun sahipliğini üstlenme durumu.",
    example: "Clear accountability improves team performance.",
    hint: "Bu işin sorumlusu kim sorusunu hatırla.",
  },
  {
    word: "Optimization",
    difficulty: "advanced",
    meaning:
      "Optimizasyon; bir süreci veya sistemi en verimli hale getirme çalışması.",
    example: "We optimized the workflow to save time.",
    hint: "Aynı işi daha az eforla yaptığını hayal et.",
  },
  {
    word: "Onboarding",
    difficulty: "advanced",
    meaning:
      "İşe alıştırma süreci; yeni çalışanların organizasyona uyum sağlamasını amaçlayan süreç.",
    example: "The onboarding process takes two weeks.",
    hint: "Yeni başlayan birinin sisteme alışmasını düşün.",
  },
  {
    word: "Cross-functional",
    difficulty: "advanced",
    meaning:
      "Fonksiyonlar arası; farklı departmanların birlikte çalıştığı yapı.",
    example: "This was a cross-functional effort.",
    hint: "Tasarımcı, yazılımcı ve pazarlamacının aynı masada olduğunu düşün.",
  },
  {
    word: "Bottleneck",
    difficulty: "advanced",
    meaning: "Darboğaz; bir sürecin yavaşlamasına neden olan aşama.",
    example: "Testing has become a bottleneck.",
    hint: "Herkesin beklediği tek bir noktayı hayal et.",
  },
  {
    word: "Delegation",
    difficulty: "advanced",
    meaning: "Yetki devri; görevlerin uygun kişilere aktarılması süreci.",
    example: "Effective delegation saves time.",
    hint: "İşi tek başına yapmamak gerektiğini fark ettiğin an.",
  },
  {
    word: "Milestone",
    difficulty: "advanced",
    meaning: "Kilometre taşı; bir projenin önemli ara hedefi.",
    example: "We reached a major milestone this week.",
    hint: "Yolun ortasında durup ilerlemeyi kontrol ettiğini düşün.",
  },
  {
    word: "Compliance",
    difficulty: "advanced",
    meaning:
      "Uyumluluk; kurallara, yasalara veya standartlara uygunluk durumu.",
    example: "The company must ensure regulatory compliance.",
    hint: "Kurallara uygun hareket ettiğinden emin olmayı düşün.",
  },
  {
    word: "Turnover",
    difficulty: "advanced",
    meaning:
      "Çalışan devri; belirli bir sürede işten ayrılan ve işe alınan çalışan oranı.",
    example: "High turnover affects team stability.",
    hint: "Ekipte insanların sık sık değiştiğini hayal et.",
  },
  {
    word: "Prioritization",
    difficulty: "advanced",
    meaning:
      "Önceliklendirme; yapılacak işler arasında önem sırasına göre düzenleme yapılması.",
    example: "Prioritization is key to productivity.",
    hint: "Önce hangisini yapmalıyım diye düşündüğün an.",
  },
  {
    word: "Alignment meeting",
    difficulty: "advanced",
    meaning:
      "Uyum toplantısı; ekiplerin hedef ve beklentilerini netleştirmek amacıyla yapılan toplantı.",
    example: "We scheduled an alignment meeting for Monday.",
    hint: "Herkesin aynı sayfada olup olmadığını kontrol etmeyi düşün.",
  },
];
