export const WORDS = [
  {
    word: "App",
    meaning: "Uygulama; belirli bir işlevi yerine getirmek için tasarlanmış yazılım programı.",
    example: "I installed a new app to track my habits.",
    hint: "Telefonunun ekranında küçük bir ikon; dokununca açılan mini bir dünya hayal et.",
  },
  {
    word: "Website",
    meaning: "Web sitesi; internet üzerinde erişilebilen sayfalar bütününden oluşan dijital alan.",
    example: "This website loads very fast on my phone.",
    hint: "Bir adres yazıp kapısı açılan sanal bir vitrin düşün.",
  },
  {
    word: "Browser",
    meaning: "Tarayıcı; web sitelerini görüntülemek ve internette gezinmek için kullanılan yazılım.",
    example: "My browser saved my passwords securely.",
    hint: "Sekmeler arasında gezindiğin, internetin “penceresi” gibi düşün.",
  },
  {
    word: "Search",
    meaning: "Arama; bilgiye ulaşmak için anahtar kelimelerle sorgulama işlemi.",
    example: "I search for recipes when I cook.",
    hint: "Bir büyüteç ikonuna yazdığın kelimelerin seni hedefe götürdüğünü hayal et.",
  },
  {
    word: "Download",
    meaning: "İndirmek; internetten bir dosyayı cihazına aktarma işlemi.",
    example: "I download the file and open it later.",
    hint: "Bir dosyanın buluttan cihazına doğru “inmesini” gözünde canlandır.",
  },
  {
    word: "Upload",
    meaning: "Yüklemek; bir dosyayı cihazından internete veya bir platforma aktarma işlemi.",
    example: "Please upload your photo to the form.",
    hint: "Telefonundan yukarı doğru giden bir ok ve dosyanın internete taşınması gibi düşün.",
  },
  {
    word: "Link",
    meaning: "Bağlantı; bir sayfadan başka bir sayfaya yönlendiren tıklanabilir adres.",
    example: "Send me the link so I can join.",
    hint: "Bir zincir halkası gibi; bir yere dokununca başka bir yere ışınlanıyorsun.",
  },
  {
    word: "Email",
    meaning: "E-posta; internet üzerinden gönderilen dijital mesaj.",
    example: "I sent an email to the support team.",
    hint: "Sanal bir zarfın ‘gönder’ ile uçup gittiğini hayal et.",
  },
  {
    word: "Inbox",
    meaning: "Gelen kutusu; e-postaların veya mesajların toplandığı bölüm.",
    example: "My inbox is full of newsletters.",
    hint: "Posta kutuna düşen yeni mesajları tek tek açtığını düşün.",
  },
  {
    word: "Attachment",
    meaning: "Ek; e-posta veya mesajla birlikte gönderilen dosya.",
    example: "The attachment includes the invoice.",
    hint: "Mesajın yanında küçük bir ataç işareti ve ekli dosyayı hayal et.",
  },
  {
    word: "Password",
    meaning: "Parola; bir hesaba erişim sağlamak için kullanılan gizli karakter dizisi.",
    example: "Never share your password with anyone.",
    hint: "Kapıyı açan gizli anahtar gibi; sadece sende olsun.",
  },
  {
    word: "Username",
    meaning: "Kullanıcı adı; bir hizmette seni tanımlayan ad.",
    example: "Choose a unique username.",
    hint: "Dijital dünyada seni çağırdıkları isim etiketi gibi düşün.",
  },
  {
    word: "Login",
    meaning: "Giriş yapmak; kullanıcı adı ve parola ile hesaba erişmek.",
    example: "I login to check my messages.",
    hint: "Kapıdan içeri girmek gibi; doğru anahtarla açılıyor.",
  },
  {
    word: "Logout",
    meaning: "Çıkış yapmak; oturumu sonlandırmak ve hesaptan ayrılmak.",
    example: "I always logout on shared computers.",
    hint: "Kapıyı kapatıp güvenle dışarı çıkmak gibi hayal et.",
  },
  {
    word: "Account",
    meaning: "Hesap; bir hizmeti kullanmak için oluşturulan kişisel kayıt.",
    example: "My account has two-factor authentication.",
    hint: "Sana ait küçük bir dijital kimlik kartı gibi düşün.",
  },
  {
    word: "Profile",
    meaning: "Profil; hesapla ilgili kişisel bilgilerin ve ayarların bulunduğu sayfa.",
    example: "I updated my profile picture today.",
    hint: "Dijital vitrinin; insanlar seni orada görüyor.",
  },
  {
    word: "Settings",
    meaning: "Ayarlar; bir uygulama veya cihazın seçeneklerini düzenleme bölümü.",
    example: "Check the settings to change the language.",
    hint: "Bir kontrol paneli; düğmeleri çevirip her şeyi kendine göre ayarlıyorsun.",
  },
  {
    word: "Update",
    meaning: "Güncelleme; yazılımın daha yeni sürüme yükseltilmesi.",
    example: "An update fixed the battery problem.",
    hint: "Yeni bir parça takılmış gibi; uygulaman tazeleniyor.",
  },
  {
    word: "Install",
    meaning: "Kurmak; bir uygulamayı cihaza yükleyip kullanıma hazır hâle getirmek.",
    example: "I install the app from the store.",
    hint: "Kutudan çıkan yeni bir aleti masaya koyup çalıştırmak gibi düşün.",
  },
  {
    word: "Uninstall",
    meaning: "Kaldırmak; bir uygulamayı cihazdan silmek.",
    example: "I uninstall apps I don't use.",
    hint: "Kullanmıyorsan dolaptan çıkarıp yer açmak gibi hayal et.",
  },
  {
    word: "Device",
    meaning: "Cihaz; bilgisayar, telefon veya tablet gibi elektronik araç.",
    example: "This device supports fast charging.",
    hint: "Elindeki küçük teknoloji yardımcısını düşün.",
  },
  {
    word: "Smartphone",
    meaning: "Akıllı telefon; internet ve uygulama özelliklerine sahip cep telefonu.",
    example: "My smartphone takes great photos.",
    hint: "Cebindeki mini bilgisayar; her an yanında.",
  },
  {
    word: "Tablet",
    meaning: "Tablet; dokunmatik ekranlı taşınabilir bilgisayar.",
    example: "I read books on my tablet.",
    hint: "Büyükçe bir ekran defteri; parmağınla sayfa çeviriyorsun.",
  },
  {
    word: "Laptop",
    meaning: "Dizüstü bilgisayar; taşınabilir kişisel bilgisayar.",
    example: "I carry my laptop to class.",
    hint: "Katlanıp çantaya giren, her yerde açılan çalışma masası gibi düşün.",
  },
  {
    word: "Desktop",
    meaning: "Masaüstü bilgisayar; sabit kullanılan kişisel bilgisayar türü.",
    example: "My desktop is faster for editing videos.",
    hint: "Masanda duran güçlü bir istasyon hayal et.",
  },
  {
    word: "Keyboard",
    meaning: "Klavye; yazı yazmak için kullanılan tuş takımı.",
    example: "The keyboard feels comfortable to type on.",
    hint: "Parmaklarınla ritim tuttuğun tuşlar; sanki piyano gibi.",
  },
  {
    word: "Mouse",
    meaning: "Fare; ekrandaki imleci kontrol etmeye yarayan giriş aygıtı.",
    example: "I use a mouse for precise design work.",
    hint: "Masada kayan küçük bir kontrol taşı gibi düşün.",
  },
  {
    word: "Touchscreen",
    meaning: "Dokunmatik ekran; parmakla kontrol edilen ekran türü.",
    example: "This touchscreen responds quickly.",
    hint: "Ekrana dokununca hemen cevap veren sihirli bir yüzey hayal et.",
  },
  {
    word: "Screen",
    meaning: "Ekran; bilgilerin görüntülendiği yüzey.",
    example: "My screen brightness is too high.",
    hint: "Işığı ve görüntüyü taşıyan bir pencere gibi düşün.",
  },
  {
    word: "Wi-Fi",
    meaning: "Wi‑Fi; kablosuz internet bağlantısı sağlayan ağ teknolojisi.",
    example: "The Wi-Fi is slow in this room.",
    hint: "Havada dolaşan görünmez bir internet hattı hayal et.",
  },
  {
    word: "Network",
    meaning: "Ağ; cihazların veri paylaşımı için birbirine bağlandığı sistem.",
    example: "Our office network is secure.",
    hint: "Bir şehir yolları gibi; veri paketleri gidip geliyor.",
  },
  {
    word: "Router",
    meaning: "Yönlendirici; ağ trafiğini yöneten cihaz.",
    example: "Restart the router to fix the issue.",
    hint: "Evindeki internetin küçük trafik polisi gibi düşün.",
  },
  {
    word: "Modem",
    meaning: "Modem; internet sağlayıcısından gelen hattı ağa çeviren cihaz.",
    example: "The modem lights are blinking.",
    hint: "Duvara bağlı küçük kutu; internetin kapısı gibi.",
  },
  {
    word: "Hotspot",
    meaning: "Erişim noktası; bir cihazın internetini başkalarıyla paylaşması.",
    example: "I turned on my hotspot for my friend.",
    hint: "Telefonunu küçük bir Wi‑Fi dağıtıcıya çevirdiğini düşün.",
  },
  {
    word: "Bluetooth",
    meaning: "Bluetooth; kısa mesafede kablosuz bağlantı teknolojisi.",
    example: "Bluetooth connects my headphones instantly.",
    hint: "İki cihazın birbirine görünmez bir kabloyla bağlandığını hayal et.",
  },
  {
    word: "Cable",
    meaning: "Kablo; cihazları bağlayan fiziksel iletken.",
    example: "This cable charges my phone fast.",
    hint: "İki noktayı birbirine bağlayan bir köprü gibi düşün.",
  },
  {
    word: "Charger",
    meaning: "Şarj aleti; bataryayı dolduran cihaz.",
    example: "I forgot my charger at home.",
    hint: "Enerji veren küçük bir pompa gibi hayal et.",
  },
  {
    word: "Battery",
    meaning: "Batarya; cihazın enerji depolayan bölümü.",
    example: "The battery lasts all day.",
    hint: "Cihazının içindeki minik enerji deposunu düşün.",
  },
  {
    word: "Storage",
    meaning: "Depolama; verilerin saklandığı alan.",
    example: "I need more storage for photos.",
    hint: "Dijital bir dolap; dosyalarını oraya yerleştiriyorsun.",
  },
  {
    word: "Cloud",
    meaning: "Bulut; internet üzerinden veri saklama ve erişim hizmeti.",
    example: "My photos are saved in the cloud.",
    hint: "Dosyalarının gökyüzünde güvenli bir kasada durduğunu hayal et.",
  },
  {
    word: "Backup",
    meaning: "Yedek; verilerin kaybolmaması için alınan kopya.",
    example: "I make a backup every week.",
    hint: "Önemli şeylerin ikinci bir kopyasını güvenli bir çekmeceye koymak gibi.",
  },
  {
    word: "File",
    meaning: "Dosya; bilgisayarda saklanan veri birimi.",
    example: "I renamed the file to find it easily.",
    hint: "Bir klasörün içinde duran tek bir belge gibi düşün.",
  },
  {
    word: "Folder",
    meaning: "Klasör; dosyaları düzenlemek için kullanılan dizin.",
    example: "Put the photos in a folder.",
    hint: "Masanın üstünde etiketli bir dosya zarfı hayal et.",
  },
  {
    word: "Document",
    meaning: "Belge; yazılı veya görsel içeriği barındıran dosya.",
    example: "I opened the document and edited it.",
    hint: "Sayfalarca bilgi içeren dijital bir kağıt gibi.",
  },
  {
    word: "Data",
    meaning: "Veri; işlenebilen ve saklanabilen bilgi.",
    example: "Data helps us make decisions.",
    hint: "Küçük bilgi parçacıkları; bir araya gelince anlam kazanıyor.",
  },
  {
    word: "Cache",
    meaning: "Önbellek; hızlı erişim için geçici olarak saklanan veri.",
    example: "Clear the cache to fix loading problems.",
    hint: "Hız için tutulan küçük bir “hızlı çekmece” düşün.",
  },
  {
    word: "Cookie",
    meaning: "Çerez; web sitelerinin tarayıcıda sakladığı küçük veri parçası.",
    example: "This site uses cookies to remember your preferences.",
    hint: "Sitenin seni hatırlaması için cebine bıraktığı küçük not gibi.",
  },
  {
    word: "History",
    meaning: "Geçmiş; tarayıcıda ziyaret edilen sayfaların kaydı.",
    example: "I deleted my browsing history.",
    hint: "Gittiğin yerlerin listesi; sanki dijital bir seyahat günlüğü.",
  },
  {
    word: "Bookmark",
    meaning: "Yer imi; bir web sayfasını hızlıca bulmak için kaydetme.",
    example: "I bookmarked the article for later.",
    hint: "Kitapta sayfa arasına koyduğun ayraç gibi düşün.",
  },
  {
    word: "Tab",
    meaning: "Sekme; tarayıcıda aynı anda açık tutulan sayfa alanı.",
    example: "I keep too many tabs open.",
    hint: "Üstte dizilen küçük kartlar; her biri başka bir sayfa.",
  },
  {
    word: "Window",
    meaning: "Pencere; ekranda açılan uygulama veya görünüm alanı.",
    example: "I moved the window to the second monitor.",
    hint: "Ekranda açılan bir çerçeve; içinden başka bir dünya görünüyor.",
  },
  {
    word: "URL",
    meaning: "URL; bir web sayfasının internet adresi.",
    example: "Copy the URL and paste it here.",
    hint: "Bir ev adresi gibi; doğru yazınca doğru yere gidiyorsun.",
  },
  {
    word: "Domain",
    meaning: "Alan adı; bir web sitesinin isimle ifade edilen adres kısmı.",
    example: "This domain is easy to remember.",
    hint: "Sitenin tabelası gibi; insanların hatırladığı isim.",
  },
  {
    word: "Server",
    meaning: "Sunucu; hizmet ve verileri kullanıcılara sağlayan bilgisayar sistemi.",
    example: "The server is down right now.",
    hint: "Arka planda çalışan büyük bir mutfak; siparişleri hazırlıyor.",
  },
  {
    word: "Client",
    meaning: "İstemci; sunucudan hizmet alan uygulama veya cihaz.",
    example: "The client connects to the server securely.",
    hint: "Sipariş veren taraf; sunucudan cevap bekleyen kullanıcı gibi.",
  },
  {
    word: "Database",
    meaning: "Veritabanı; düzenli biçimde saklanan ve sorgulanabilen veri deposu.",
    example: "The app stores users in a database.",
    hint: "Dev bir arşiv odası; raf raf kayıtlar düşün.",
  },
  {
    word: "Query",
    meaning: "Sorgu; veritabanından bilgi isteme ifadesi.",
    example: "I ran a query to find the latest orders.",
    hint: "Arşive gidip “şu dosyayı bul” demek gibi hayal et.",
  },
  {
    word: "API",
    meaning: "API; yazılımların birbiriyle iletişim kurmasını sağlayan arayüz.",
    example: "Our app uses an API to get weather data.",
    hint: "İki uygulama arasında konuşmayı sağlayan bir tercüman gibi.",
  },
  {
    word: "JSON",
    meaning: "JSON; veriyi anahtar-değer yapısıyla temsil eden metin biçimi.",
    example: "The server returns data as JSON.",
    hint: "Küçük kutucuklar içinde düzenli bilgi listesi hayal et.",
  },
  {
    word: "Code",
    meaning: "Kod; bilgisayara ne yapacağını söyleyen talimatlar dizisi.",
    example: "I write code every day.",
    hint: "Bir tarife gibi; adımları yazınca bilgisayar uygular.",
  },
  {
    word: "Bug",
    meaning: "Hata; yazılımın beklenmeyen şekilde çalışmasına neden olan sorun.",
    example: "A small bug broke the login screen.",
    hint: "Çarkın arasına kaçan minicik bir taş gibi; sistemi aksatıyor.",
  },
  {
    word: "Fix",
    meaning: "Düzeltmek; bir sorunu giderip doğru çalışmayı sağlamak.",
    example: "They fixed the crash in the new version.",
    hint: "Bozulan bir parçayı yerine oturtmak gibi düşün.",
  },
  {
    word: "Feature",
    meaning: "Özellik; bir yazılımın sunduğu belirli işlev.",
    example: "This feature saves time.",
    hint: "Uygulamaya eklenen yeni bir yetenek; sanki yeni bir düğme.",
  },
  {
    word: "Version",
    meaning: "Sürüm; yazılımın belirli bir yayımlanmış hâli.",
    example: "I updated to the latest version.",
    hint: "Aynı uygulamanın farklı “baskıları” gibi düşün.",
  },
  {
    word: "Release",
    meaning: "Yayın; bir sürümün kullanıcılara sunulması.",
    example: "The release is scheduled for Friday.",
    hint: "Paketlenip vitrine konan yeni ürün gibi hayal et.",
  },
  {
    word: "Beta",
    meaning: "Beta; test amaçlı, tam tamamlanmamış sürüm.",
    example: "I joined the beta to try new features early.",
    hint: "Herkesten önce denediğin deneme sürümü; biraz sürprizli olabilir.",
  },
  {
    word: "Patch",
    meaning: "Yama; küçük bir düzeltme veya güncelleme paketi.",
    example: "A patch solved the security issue.",
    hint: "Yırtığı kapatan küçük bir parça gibi; hızlı onarım.",
  },
  {
    word: "Security",
    meaning: "Güvenlik; sistem ve verileri tehditlere karşı koruma durumu.",
    example: "Security is important for online banking.",
    hint: "Dijital bir kilit ve alarm sistemi hayal et.",
  },
  {
    word: "Privacy",
    meaning: "Gizlilik; kişisel bilgilerin kontrol altında tutulması ilkesi.",
    example: "Privacy settings protect your data.",
    hint: "Perdeleri kapatıp sadece istediğini gösterdiğin bir oda gibi.",
  },
  {
    word: "Encryption",
    meaning: "Şifreleme; veriyi yetkisiz erişime karşı okunamaz hâle getirme yöntemi.",
    example: "Encryption keeps messages safe.",
    hint: "Mesajını gizli bir koda çeviren görünmez bir kasa düşün.",
  },
  {
    word: "Firewall",
    meaning: "Güvenlik duvarı; ağ trafiğini filtreleyen koruma sistemi.",
    example: "A firewall blocks suspicious traffic.",
    hint: "Kapıda duran bir güvenlik görevlisi; şüpheliyi içeri almıyor.",
  },
  {
    word: "Antivirus",
    meaning: "Antivirüs; zararlı yazılımları tespit edip engelleyen program.",
    example: "An antivirus scan found a threat.",
    hint: "Bilgisayarını tarayan bir doktor gibi düşün.",
  },
  {
    word: "Malware",
    meaning: "Zararlı yazılım; sistemi bozmak veya veri çalmak için tasarlanmış yazılım.",
    example: "Malware can steal your passwords.",
    hint: "Bilgisayara sızmaya çalışan kötü niyetli bir misafir gibi.",
  },
  {
    word: "Phishing",
    meaning: "Kimlik avı; sahte mesajlarla bilgi çalma yöntemi.",
    example: "Phishing emails often look real.",
    hint: "Gerçek gibi görünen sahte bir olta; bilgini yakalamaya çalışır.",
  },
  {
    word: "Spam",
    meaning: "İstenmeyen ileti; gereksiz veya reklam içerikli mesajlar.",
    example: "My spam folder catches most ads.",
    hint: "Gereksiz broşürler gibi; kutunu dolduran çöpler.",
  },
  {
    word: "Notification",
    meaning: "Bildirim; bir uygulamanın kullanıcıya gönderdiği uyarı.",
    example: "I got a notification about a new message.",
    hint: "Ekranda beliren küçük bir not; “hey, bak buraya” diyor.",
  },
  {
    word: "Message",
    meaning: "Mesaj; dijital olarak gönderilen kısa ileti.",
    example: "I sent a message in the group chat.",
    hint: "Hızlı bir not; anında karşıya gidiyor.",
  },
  {
    word: "Chat",
    meaning: "Sohbet; anlık mesajlaşma iletişimi.",
    example: "Let's chat after the meeting.",
    hint: "Yan yana oturmasan da yazıyla konuşmak gibi düşün.",
  },
  {
    word: "Video call",
    meaning: "Görüntülü arama; ses ve görüntüyle yapılan çevrim içi görüşme.",
    example: "We had a video call with the team.",
    hint: "Ekranda karşı tarafın yüzü; sanki aynı odadaymışsın.",
  },
  {
    word: "Streaming",
    meaning: "Akış; içeriğin indirilmeksizin anlık olarak izlenmesi/dinlenmesi.",
    example: "I watched the game via streaming.",
    hint: "Bir nehir gibi akan video; durmadan sana geliyor.",
  },
  {
    word: "Buffer",
    meaning: "Arabellek; akışın kesilmemesi için geçici veri biriktirme işlemi.",
    example: "The video paused to buffer.",
    hint: "Video, devam etmek için nefes alıp su içiyor gibi düşün.",
  },
  {
    word: "Podcast",
    meaning: "Podcast; internet üzerinden yayımlanan ses programı.",
    example: "I listen to a podcast while walking.",
    hint: "Kulaklığında akan bir radyo gibi; istediğin zaman açılıyor.",
  },
  {
    word: "Feed",
    meaning: "Akış; platformda içeriklerin sıralandığı liste.",
    example: "My feed shows posts from friends.",
    hint: "Ekranda aşağı doğru akan içerik nehrini hayal et.",
  },
  {
    word: "Timeline",
    meaning: "Zaman tüneli; içeriklerin zamana göre sıralandığı bölüm.",
    example: "My timeline is full of travel photos.",
    hint: "Zaman boyunca dizilmiş fotoğraf ve yazı şeridi gibi düşün.",
  },
  {
    word: "Post",
    meaning: "Gönderi; platformda paylaşılan içerik.",
    example: "I posted a photo yesterday.",
    hint: "Duvara asılan bir ilan gibi; herkes görebiliyor.",
  },
  {
    word: "Comment",
    meaning: "Yorum; bir içeriğe yazılan görüş veya tepki.",
    example: "I left a comment under the video.",
    hint: "Bir sohbetin altına küçük bir not bırakmak gibi.",
  },
  {
    word: "Like",
    meaning: "Beğeni; bir içeriği olumlu işaretleme.",
    example: "I gave the post a like.",
    hint: "Kalp ikonuna dokunup ‘bunu sevdim’ demek gibi.",
  },
  {
    word: "Share",
    meaning: "Paylaşmak; içeriği başkalarına iletmek.",
    example: "Please share this article with your team.",
    hint: "Bir şeyi elden ele uzatmak gibi; dijitalde gönderiyorsun.",
  },
  {
    word: "Subscribe",
    meaning: "Abone olmak; bir kanalı veya hizmeti düzenli takip etmeyi seçmek.",
    example: "I subscribe to get updates.",
    hint: "Bir kapıyı çalıp ‘beni listene ekle’ demek gibi düşün.",
  },
  {
    word: "Follower",
    meaning: "Takipçi; hesabını düzenli izleyen kişi.",
    example: "She gained new followers quickly.",
    hint: "Arkana takılan bir kalabalık; içeriklerini izliyorlar.",
  },
  {
    word: "Hashtag",
    meaning: "Etiket; içerikleri konuya göre gruplamak için kullanılan # işareti.",
    example: "Use a hashtag to reach more people.",
    hint: "Bir dosya etiketi; aynı konudakiler aynı çekmecede toplanıyor.",
  },
  {
    word: "Emoji",
    meaning: "Emoji; duyguları veya nesneleri temsil eden küçük simgeler.",
    example: "I added an emoji to make it friendly.",
    hint: "Yazıya küçük bir yüz ifadesi eklemek gibi düşün.",
  },
  {
    word: "Screenshot",
    meaning: "Ekran görüntüsü; ekrandaki görüntünün kaydı.",
    example: "I took a screenshot of the error.",
    hint: "Ekranı fotoğraflayıp saklamak gibi; kanıt bırakıyorsun.",
  },
  {
    word: "Clipboard",
    meaning: "Pano; kopyalanan verilerin geçici tutulduğu alan.",
    example: "The text is in my clipboard now.",
    hint: "Kopyaladığın şeylerin kısa süre durduğu görünmez bir not kağıdı.",
  },
  {
    word: "Copy",
    meaning: "Kopyalamak; veriyi çoğaltıp panoya almak.",
    example: "Copy the code and paste it.",
    hint: "Bir şeyi aynen çoğaltıp cebine koymak gibi düşün.",
  },
  {
    word: "Paste",
    meaning: "Yapıştırmak; panodaki veriyi hedef yere eklemek.",
    example: "Paste the link into the chat.",
    hint: "Cebindeki notu çıkarıp sayfaya yapıştırmak gibi.",
  },
  {
    word: "Shortcut",
    meaning: "Kısayol; bir işlemi hızlıca yapmak için kullanılan hızlı yol.",
    example: "Use this shortcut to save time.",
    hint: "İki sokak yerine kestirme bir ara sokak düşün.",
  },
  {
    word: "QR code",
    meaning: "QR kodu; kamerayla okunabilen kare desenli kod.",
    example: "Scan the QR code to open the menu.",
    hint: "Telefon kameranı tutunca kapı açan kare bir desen hayal et.",
  },
  {
    word: "Barcode",
    meaning: "Barkod; ürünleri tanımlamak için kullanılan çizgili kod.",
    example: "The cashier scanned the barcode.",
    hint: "Çizgilerin altında saklı bir kimlik numarası gibi düşün.",
  },
  {
    word: "GPS",
    meaning: "GPS; konum belirleme sistemi.",
    example: "GPS helped me find the address.",
    hint: "Haritada küçük bir nokta: ‘buradasın’ diyor.",
  },
  {
    word: "Map",
    meaning: "Harita; konum ve yön bulmaya yarayan dijital veya fiziksel gösterim.",
    example: "The map shows the fastest route.",
    hint: "Yolların çizildiği bir plan; seni hedefe götürüyor.",
  },
  {
    word: "Algorithm",
    meaning: "Algoritma; bir problemi çözmek için izlenen adım adım yöntem.",
    example: "The algorithm sorts the list quickly.",
    hint: "Adım adım tarif; doğru sırayla yapınca sonuç çıkıyor.",
  },
  {
    word: "Automation",
    meaning: "Otomasyon; işlemlerin insan müdahalesi az olacak şekilde otomatik yürütülmesi.",
    example: "Automation saves hours of manual work.",
    hint: "Sen izlemeden çalışan bir robot asistan hayal et.",
  },
  {
    word: "Login page",
    meaning: "Giriş sayfası; kullanıcı bilgileriyle erişimin sağlandığı ekran.",
    example: "The login page asked for my password.",
    hint: "Kapı önü gibi; içeri girmek için bilgini yazıyorsun.",
  },
  {
    word: "Two-factor authentication",
    meaning: "İki faktörlü doğrulama; girişte ikinci bir doğrulama adımı kullanma yöntemi.",
    example: "Two-factor authentication protects my account.",
    hint: "Anahtar + kapı zili gibi; iki adımda güvenli giriş.",
  },
  {
    word: "Extension",
    meaning: "Eklenti; tarayıcıya veya uygulamaya yeni özellik ekleyen küçük yazılım.",
    example: "I installed an extension to block ads.",
    hint: "Tarayıcına takılan küçük bir aparat; yeni güç veriyor.",
  },
  {
    word: "Plugin",
    meaning: "Eklenti modülü; ana yazılıma ek işlev kazandıran bileşen.",
    example: "This plugin adds a new export option.",
    hint: "Ana programa takılan bir parça; yeni butonlar getiriyor.",
  },
  {
    word: "Framework",
    meaning: "Çatı; yazılım geliştirmede temel yapı ve kuralları sağlayan sistem.",
    example: "This framework speeds up development.",
    hint: "İnşaat iskelesi gibi; üzerine hızlıca yapı kuruyorsun.",
  },
  {
    word: "Library",
    meaning: "Kütüphane; belirli görevler için hazır kod koleksiyonu.",
    example: "We use a library to handle dates.",
    hint: "Raftaki hazır araçlar; ihtiyacın olunca alıp kullanıyorsun.",
  },
  {
    word: "Repository",
    meaning: "Depo; kaynak kodun saklandığı ve yönetildiği alan.",
    example: "The repository contains the project code.",
    hint: "Projeni koyduğun dijital kasa; herkes oradan bakıyor.",
  },
  {
    word: "Commit",
    meaning: "Kaydetme; sürüm kontrolünde yapılan değişikliği kayıt altına alma.",
    example: "I made a commit after fixing the bug.",
    hint: "Bir fotoğraf çekip ‘bu an böyle’ diye arşive koymak gibi.",
  },
  {
    word: "Branch",
    meaning: "Dal; ana koddan ayrılan paralel çalışma hattı.",
    example: "Create a new branch for the feature.",
    hint: "Ağaçtan çıkan yeni bir dal; farklı bir yolda ilerliyorsun.",
  },
  {
    word: "Merge",
    meaning: "Birleştirmek; dallardaki değişiklikleri tek bir hatta toplamak.",
    example: "We will merge the feature branch today.",
    hint: "İki yolu tekrar tek yola bağlamak gibi düşün.",
  },
  {
    word: "Debug",
    meaning: "Hata ayıklamak; bir sorunun nedenini bulup düzeltme süreci.",
    example: "I debugged the crash with logs.",
    hint: "Dedektif gibi ipuçlarını takip edip hatayı yakalamak.",
  },
  {
    word: "Compile",
    meaning: "Derlemek; kaynak kodu çalıştırılabilir hâle dönüştürmek.",
    example: "The code compiles without errors.",
    hint: "Tarifin malzemelerini pişirip yemeğe dönüştürmek gibi.",
  },
  {
    word: "Log",
    meaning: "Kayıt; sistemin çalışmasıyla ilgili not edilen bilgiler.",
    example: "Check the log to see what happened.",
    hint: "Olan biteni yazan bir günlük; geriye dönüp okuyorsun.",
  },
  {
    word: "Bandwidth",
    meaning: "Bant genişliği; bir ağın veri taşıma kapasitesi.",
    example: "High bandwidth helps with streaming.",
    hint: "Otoyol genişliği gibi; daha çok veri aynı anda geçiyor.",
  },
  {
    word: "Latency",
    meaning: "Gecikme; veri iletimindeki zaman farkı.",
    example: "Low latency matters in online games.",
    hint: "Tuşa basınca olan tepki süresi; ne kadar azsa o kadar iyi.",
  },
  {
    word: "Ping",
    meaning: "Ping; ağ gecikmesini ölçmek için gönderilen kontrol paketi.",
    example: "My ping is high today.",
    hint: "Karşıya ‘orada mısın?’ diye seslenip dönüş süresini ölçmek gibi.",
  },
  {
    word: "IP address",
    meaning: "IP adresi; ağ üzerindeki cihazı tanımlayan sayısal adres.",
    example: "Every device has an IP address on the network.",
    hint: "Her cihazın posta adresi gibi; nerede olduğunu söyler.",
  },
  {
    word: "Firmware",
    meaning: "Donanım yazılımı; cihazın içinde çalışan temel yazılım.",
    example: "A firmware update improved stability.",
    hint: "Cihazın içindeki küçük beyin; güncellenince daha iyi çalışır.",
  },
  {
    word: "Operating system",
    meaning: "İşletim sistemi; donanımı yöneten ve uygulamaları çalıştıran temel yazılım.",
    example: "The operating system updated overnight.",
    hint: "Cihazın yöneticisi; her şeyi o organize ediyor.",
  }
];
